### ISSUE TITLE
hping3 plugin request.

### ISSUE THREAD

**Issue by ChrisFernandez** [infobyte/faraday#100]
Sometimes is better to use hping3 than nmap, mostly when you want to create your own crafted packages... # @

**Comment by Ezequieltbh** [comment]
Hi ChrisFernanez!.
We will add your request to the list of plugins and get back to you. 
Cheers!

**Comment by ChrisFernandez** [comment]
Thank you @Ezequieltbh

**Comment by Ezequieltbh** [comment]
Good news!
#154 Pull request for hping3.
We merge this soon, thanks for waiting!
Regards!

**Comment by WinnaZ** [comment]
This plugin has been added to Faraday!
We hope you enjoy it,
Cheers.
