### ISSUE TITLE
Docker & run.sh

### ISSUE THREAD

**Issue by stillinsecure** [infobyte/faraday#107]
When I start the docker image with docker run -t -i infobyte/faraday /root/run.sh, I receive the following error,

ImportError: cannot import name CONST_FARADAY_ZSH_OUTPUT_PATH

I have attached the complete log from the container
[docker.txt](https://github.com/infobyte/faraday/files/409491/docker.txt)

**Comment by joaquinlpereyra** [comment]
Hello @stillinsecure! We're sorry you're having trouble. Could you provide us with the output of ```cat $FARADAY/config/globals.py```? Thank you!

**Comment by stillinsecure** [comment]
Looks like that constant is not defined in the globals.py file. I have attached the output.
[output.txt](https://github.com/infobyte/faraday/files/409550/output.txt)

**Comment by stillinsecure** [comment]
But i noticed that CONST_FARADAT_ZSH_OUTPUT_PATH is present in the latest version of globals.py in git.

**Comment by joaquinlpereyra** [comment]
@stillinsecure Looks like something went wrong with the update mechanism. Are you able to install Faraday without Docker? We shall be looking into this problem a releasing an updated version of the docker image in the near future.

**Comment by stillinsecure** [comment]
Yep that shouldnt be a problem. Thanks for the quick response

**Comment by evilpacket** [comment]
Similar to this issue, but a different error when using docker / run.sh I get the following.
Full log [docker_log.txt](https://github.com/infobyte/faraday/files/428970/docker_log.txt)


```
2016-08-21 17:24:47,193 - faraday.launcher - INFO - No updates available, enjoy Faraday
Traceback (most recent call last):
  File "./faraday.py", line 582, in <module>

  File "./faraday.py", line 576, in main

  File "./faraday.py", line 274, in startFaraday
    port_rest = CONF.getApiRestfulConInfoPort() if str(CONF.getApiRestfulConInfoPort()) != "None" else FARADAY_DEFAULT_PORT_REST
  File "/root/faraday/model/application.py", line 17, in <module>
    from managers.workspace_manager import WorkspaceManager
  File "/root/faraday/managers/workspace_manager.py", line 18, in <module>
    from config.globals import CONST_BLACKDBS
ImportError: cannot import name CONST_BLACKDBS
```

**Comment by Ezequieltbh** [comment]
Hi people!
Our docker image is now updated, with the last version of Faraday (2.0)
For more information about Faraday in Docker, you can read this ...
[Docker - Faraday Blog](http://blog.infobytesec.com/2015/08/official-faraday-docker-images.html)
And in our wiki...
[Docker - Wiki Faraday](https://github.com/infobyte/faraday/wiki/installation-client#docker)

**Comment by stillinsecure** [comment]
Cool I will check it out.

**Comment by Ezequieltbh** [comment]
HI!
Any feedback about this problem?
Thanks!
