### ISSUE TITLE
ProtocolError for *IP*:*PORT*/: 500 Internal Server Error

### ISSUE THREAD

**Issue by immanot** [infobyte/faraday#108]
Everytime when I'm trying to make RPC calls 
"createAndAddVulnToService" 
    or 
"createAndAddVulnToInterface"  
I got "ProtocolError for *IP*:*PORT*/: 500 Internal Server Error".
I've tried to send a lot of different variables inside this functions, but no difference. Everytime I got this error, so I can't add some vulns from my script to faraday DB (couch I mean)

**Comment by Ezequieltbh** [comment]
Hi immanot!
Are you sure RPC API is up? 
You can see this in the faraday output ....

>  faraday - INFO - XMLRPC API server configured on ('localhost', 9881)

Can you paste your script here? Maybe is a error in this...
Regards!

**Comment by immanot** [comment]
Hey. Sure. Another methods like createAndAddVulnToHost works well
faraday - INFO - XMLRPC API server configured on ('localhost', 9876)

I removed this calls from my script, but here is same example that I used in my script:
```
h_id = api.createAndAddHost("TestHostName")
i_id = api.createAndAddInterface(h_id,"TestIfaceName","00:00:00:00:00:00", "127.0.0.1", "0.0.0.0", "0.0.0.0",[],0000:0000:0000:0000:0000:0000:0000","00","0000:0000:0000:0000:0000:0000:0000:0000",
                                  [],"",[])
v_id = createAndAddVulnToInterface(h_id, i_id, "TestVulnName", "", [], "")
```
I was trying to "play" with parameters inside createAndAddVulnToInterface function, but no difference..

**Comment by Ezequieltbh** [comment]
Hi again!
createAndAddVulnToInterface is not a valid method in our XML RPC API, this is a list with all valid methods...

```
createAndAddApplication
createAndAddHost
createAndAddInterface
createAndAddNoteToHost
createAndAddNoteToNote
createAndAddNoteToService
createAndAddServiceToApplication
createAndAddServiceToInterface
createAndAddVulnToHost
createAndAddVulnToService
createAndAddVulnWebToService
```
 
You can create vulns associate to hosts or services, not to interface.
So, you need create a service with 'createAndAddServiceToInterface' and later 'createAndAddVulnToService',
or you can use 'createAndAddVulnToHost'

Regards!

**Comment by immanot** [comment]
Thanks for answer, but I was trying to do so and it didn't work. I mean method 'createAndAddVulnToService'.
Example code:
```
h_id = api.createAndAddHost("TestHostName")
i_id = api.createAndAddInterface(h_id,"TestIfaceName","00:00:00:00:00:00", "127.0.0.1", "0.0.0.0", "0.0.0.0",[],"0000:0000:0000:0000:0000:0000:0000","00","0000:0000:0000:0000:0000:0000:0000:0000",
                                  [],"",[])
s_id = api.createAndAddServiceToInterface(h_id, i_id, "TestServiceName", "tcp", 
                [], "running", "unknown", "")
test_id = api.createAndAddVulnToService(h_id, s_id, "TestVulnName", "", [], "")
```
And this code doesn't work either...
But as I said before, method "createAndAddVulnToHost" works fine

**Comment by immanot** [comment]
I realized what was the problem.
I need to use 
`test_id = api.createAndAddVulnToService(h_id, s_id, "TestVulnName", "", [], "", '')`

What file responds to XML RPC API methods? Api.py or guiapi.py?

**Comment by Ezequieltbh** [comment]
Our Rest API, is coded in apis/rest/*
And our XML RPC API is coded in model/api.py

You can use the '-w' parameter in Faraday.py for select a workspace, and all Information sent to Faraday is loaded in this workspace.
Right now, you can't specify a workspace using our XML RPC API.

Regards!
