### ISSUE TITLE
[BUG][DEPRECATE][FIXED][Faraday_v2] Internal paths reliant upon current working directory

### ISSUE THREAD

**Issue by caoimhinp** [infobyte/faraday#11]
If a user is not in the /opt/faraday-dev/ directory the application will not start.
There is a separate issue concerning a non-privileged user versus root but I will address that in another post.

This was tested on: 
Linux Caeli 3.14-kali1-amd64 #1 SMP Debian 3.14.5-1kali1 (2014-06-07) x86_64 GNU/Linux

###Output from user not in /opt/faraday-dev:###

user:~$ /opt/faraday-dev/faraday

[+] Starting faraday IDE
[*] QTconfig in place
cp: cannot stat `/home/user/zsh/faraday.zsh': No such file or directory
cp: cannot stat `/home/user/zsh/plugin_controller_client.py': No such file or directory
[*] Running under plugin development mode!
[-] Deleting old user directory: /home/user/.faraday
[+] Creating user directory: /home/user/.faraday
cp: cannot stat `/home/user/plugins/repo/*': No such file or directory
[*] Loading Plugins
[*] Using images/icons set from user
[*] Using custom user configuration
[+] Setting up for: x86_64 on Linux
ln: failed to create symbolic link `/home/user/shell/core/_helpers.so': No such file or directory
[+] Using python2.7 to run faraday.
python2.7: can't open file 'main.py': [Errno 2] No such file or directory

**Comment by Ezequieltbh** [comment]
Hi caoimhinp !
Our QT interface is now deprecated.
GTK is the new Graphical interface for Faraday.
We are closing this ticket for this.
Cheers!
