### ISSUE TITLE
WebUI not showing all data

### ISSUE THREAD

**Issue by Dargin** [infobyte/faraday#110]
I'm having an issue where we are running a server/client. The connection looks good, no errors in the server log or on the client. What happens is when i run nmap/nikto/etc from the ZSH (python on linux, ZSH term on mac) i see it capturing the data and in the application i can see my host and vulnerabilities. However, in the Web Dashboard i don't see that it's getting the host or vulnerability information. It does show my commands in the command history and from the ZSH if i hit "edit host" it brings me to the Web page and has the host, open ports, vulnerabilities, etc but if i click on any of those it goes back to "no data". 

Loving the new updates though :+1: 
![dashboard](https://cloud.githubusercontent.com/assets/6153549/17931108/acf418ae-69d7-11e6-8c76-de2ee96a8819.png)
![host](https://cloud.githubusercontent.com/assets/6153549/17931109/acf4ed74-69d7-11e6-88b3-0c80d1fcc29e.png)
![host_in_faraday](https://cloud.githubusercontent.com/assets/6153549/17931110/acf9fe54-69d7-11e6-8728-bb5ced65feea.png)

**Comment by joaquinlpereyra** [comment]
@Dargin Hello! We're sorry you're having trouble. 

Just to check: what URL are you trying to access? You should be trying to access something like SERVER_URL:SERVER_PORT/_ui. Is that correct? As of Faraday 2.0, you should always be connecting to the server, never to CouchDB directly. 

Also, and just to be sure there's nothing weird going on with the browser, you could try accessing that URL in incognito mode? So we rule out weird cookies, caché, and stuff.

**Comment by Dargin** [comment]
@joaquinlpereyra Thanks for the quick response. Yes, the url is as you said Server_URL:Server_port/_UI - this is also the same server/port configuration i put into the ZSH to connect (the Faraday server is running on port 5984 and CouchDB is running on 5985 just to ensure i'm not directly connecting to the DB).

I've tried from other machines and incognito and get the same results, the dashboard only shows the command history, but if i get the full URL to a device i can see the info shown in the Viewing host screenshot above.

**Comment by joaquinlpereyra** [comment]
@Dargin Do you have credentials set for couchdb database? If so, check they are correctly configured in ~/.faraday/config/server.xml. 

Also, if case have you restarted CouchDB, you need to restart the server too. 

You could also try posting the output of ~/.faraday/log/faraday-server.log and ~/.faraday/log/faraday.log after you try accessing the dashboard? Keep in mind these could contain sensitive information, so redact them as you see fit. The last ~20 lines after you try accessing the dashboard should be enough, if there's too much sensitive data to paste the whole thing :)

**Comment by Dargin** [comment]
I'll grab that in just a second. yea i've verified the creds. One interesting thing, if i put in a nexpose report (xml) into the handler for it on my machine (the same one i'm running my commands from) it gets uploaded to the server and shows up in the WebUI as we would expect. The only issue appears to be with commands ran from the ZSH, they get up to the DB from everything i see, they just don't get into the full Web UI. thanks.

**Comment by Dargin** [comment]
Logs from faraday-server from the server. The faraday.log on the server didn't have any data in it, i restarted it today with they command ./faraday-server.py --start so the only info on the server for faraday.log is the shutdown from yesterday.

the faraday.txt attached is the log from my box connected to the server. Thanks again.
[faraday.txt](https://github.com/infobyte/faraday/files/434993/faraday.txt)
[faraday-server.txt](https://github.com/infobyte/faraday/files/434994/faraday-server.txt)

**Comment by joaquinlpereyra** [comment]
@Dargin Dargin, this is probably related to a known issue we have with the --start option in the server. This will be fixed in the next release. 

In the meanwhile, you should now close the server and start it again with ./faraday-server.py (without the --start flag).

Please do report back if this solved your problem! :)

**Comment by Dargin** [comment]
@joaquinlpereyra  That did it!! thanks a million.
