### ISSUE TITLE
Problem in starting the faraday server.

### ISSUE THREAD

**Issue by aksh7sharma** [infobyte/faraday#111]
I have already installed all the dependencies on my kali linux. Have also installed couchDB but I cannot run the server. It keeps on giving the error:

 **_file_handler = logging.handlers.RotatingFileHandler(
AttributeError: 'module' object has no attribute 'handlers'_**

Here are the steps I followed after installing couchdb:
1. $ git clone https://github.com/infobyte/faraday.git faraday-dev
2. $ cd faraday-dev
3. $ ./install.sh
4. $ ./faraday-server.py

After executing the last command I get the mentioned error. Complete log of error:

root@kali:~/faraday-dev# ./faraday-server.py 
Traceback (most recent call last):
  File "./faraday-server.py", line 105, in <module>
    main()
  File "./faraday-server.py", line 17, in main
    setup_logging()
  File "/faraday-dev/server/utils/logger.py", line 29, in setup_logging
    setup_file_logging(formatter)
  File "/faraday-dev/server/utils/logger.py", line 40, in setup_file_logging
    file_handler = logging.handlers.RotatingFileHandler(
AttributeError: 'module' object has no attribute 'handlers'

Can someone help me with this.

**Comment by rgerman** [comment]
Hi @aksh7sharma, thanks for reporting the issue!

Try this: edit the file `/faraday-dev/server/utils/logger.py`, and add the following line at the top:
`import logging.handlers`

**Comment by aksh7sharma** [comment]
Hi @rgerman , thanks for the timely reply. Really appreciate it.
I am able to start the server now. 
However, now when I proceed to run ./faraday.py , I get the error:
**AttributeError: 'module' object has no attribute 'require_version'**

Complete log of error:

Traceback (most recent call last):
  File "./faraday.py", line 571, in <module>
    main()
  File "./faraday.py", line 565, in main
    startFaraday()
  File "./faraday.py", line 299, in startFaraday
    main_app = MainApplication(args)
  File "/faraday-dev/model/application.py", line 99, in __init__
    self.args.gui)
  File "/faraday-dev/gui/gui_app.py", line 19, in create
    from gui.gtk.application import GuiApp
  File "/faraday-dev/gui/gtk/application.py", line 23, in <module>
    gi.require_version('Gtk', '3.0')
AttributeError: 'module' object has no attribute 'require_version'

Can someone help with this?

**Comment by joaquinlpereyra** [comment]
Hi @aksh7sharma! It seems like something is wrong with your Python Gobject library. Would you mind reinstalling py-gobject? Make your system is up to date before with a ```sudo apt-get update && sudo apt-get upgrade```.  Then run a simple: ```sudo apt-get install gir1.2-gtk-3.0 gir1.2-vte-2.91 python-gobject```.

Please post the output of that last command here if the problem persists.

**Comment by aksh7sharma** [comment]
Hi @joaquinlpereyra !
Thanks for the reply.
I have run the first 2 commands i.e. sudo apt-get update && sudo apt-get upgrade.
However, when I run the last command it gives an error. Log of the error:

**root@kali:~# sudo apt-get install gir1.2-gtk-3.0 gir1.2-vte-2.91 python-gobject
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package gir1.2-vte-2.91
E: Couldn't find any package by regex 'gir1.2-vte-2.91'**

Can you help me with this?

**Comment by joaquinlpereyra** [comment]
Hey @aksh7sharma! Can you try ```sudo apt-get install gir1.2-vte-2.90```? That should work fine. It seems like you are on a somewhat older version of Kali, maybe Kali 2.0 and not rolling? We're sorry for this inconvenience and the install will be fixed in the next release!

**Comment by aksh7sharma** [comment]
I tried this but it is already installed. The output:

**root@kali:~# sudo apt-get install gir1.2-vte-2.90
Reading package lists... Done
Building dependency tree       
Reading state information... Done
gir1.2-vte-2.90 is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 8 not upgraded.**
When I tried to run ./faraday.py after this it gave the same error:

**Traceback (most recent call last):
 File "./faraday.py", line 571, in 
 main()
 File "./faraday.py", line 565, in main
 startFaraday()
 File "./faraday.py", line 299, in startFaraday
 main_app = MainApplication(args)
 File "/faraday-dev/model/application.py", line 99, in init
 self.args.gui)
 File "/faraday-dev/gui/gui_app.py", line 19, in create
 from gui.gtk.application import GuiApp
 File "/faraday-dev/gui/gtk/application.py", line 23, in 
 gi.require_version('Gtk', '3.0')
 AttributeError: 'module' object has no attribute 'require_version'**

**Comment by joaquinlpereyra** [comment]
@aksh7sharma Seems like there something wrong with Python Gobject. Are you sure python gobject is installed? Try ```sudo apt-get install --ignore-missing python-gobject py-gobject ```

**Comment by aksh7sharma** [comment]
This command is not running. output:
**E: Unable to locate package py-gobject**
So, I tried this:

**sudo apt-get install --ignore-missing python-gobject**

But then again the output is:

**Reading package lists... Done
Building dependency tree       
Reading state information... Done
python-gobject is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 8 not upgraded.**

Running ./faraday.py still gives the same error:

**AttributeError: 'module' object has no attribute 'require_version'**

Any solution?

**Comment by joaquinlpereyra** [comment]
@aksh7sharma What Kali version are you using? These two issues seems to be related, neither your cffi package nor your python-gobject seem to be up to date. It looks like you have some upgrades to do, judging from the output of apt-get. Upgrade the packages and then try again. We've just checked on the Kali repositories and the last version of cffi seems to be 1.7, you are on 0.8

**Comment by f-amato** [comment]
Any feedback regarding this issue?

Thanks
