### ISSUE TITLE
Issue Starting Faraday Server - Unauthorized Access to CouchDB

### ISSUE THREAD

**Issue by cgalligan** [infobyte/faraday#112]
When I run ./faraday-server it outputs: "faraday-server.server.database - ERROR - Unauthorized access to CouchDB. Make sure faraday-server's configuration file has CouchDB admin's credentials set"

How can I correct this?

**Comment by Ezequieltbh** [comment]
Hi!
Server.ini File Not Present in Current Project #113
Is This issue duplicated?

**Comment by f-amato** [comment]
Any feedback regarding this issue?

Thanks

**Comment by mrevros** [comment]
Hi All,
I got same error "faraday-server.server.database - ERROR - Unauthorized access to CouchDB. Make sure faraday-server's configuration file has CouchDB admin's credentials set"

Any help?

**Comment by Ezequieltbh** [comment]
Hi mrevros!
You have any user and password for couchdb? If this is the case, you need set this in the Faraday Server configuration.
[](https://github.com/infobyte/faraday/wiki/First-steps#setup)
