### ISSUE TITLE
Server.ini File Not Present in Current Project

### ISSUE THREAD

**Issue by cgalligan** [infobyte/faraday#113]
The First Steps: https://github.com/infobyte/faraday/wiki/First-steps references "Next edit ~/.faraday/config/server.ini"; I cannot locate that file in the current version of the code. Where is this located?

**Comment by joaquinlpereyra** [comment]
@cgalligan Hi! We're sorry you're having trouble. Can you try running faraday-server.py in the faraday folder? This will most probably fail, but it will force Faraday to create the ~/.faraday folder and you'll find config/server.ini inside it :)

**Comment by f-amato** [comment]
Any feedback regarding this issue?

Thanks

**Comment by cgalligan** [comment]
I haven't been able to get this working, but a colleague reported that faraday is included in the latest kali linux build so I'm going to try that

**Comment by f-amato** [comment]
Excellent @cgalligan let us know if you need help with anything!
Best
