### ISSUE TITLE
Faraday ui not loading data

### ISSUE THREAD

**Issue by ricardojcampo** [infobyte/faraday#116]
Hello,

I am trying out the community version of Faraday and it has been journey. For obvious reasons I want faraday to be password protected so I have settup a few admin accounts on the couchdb database, I have faraday server running and connecting to the database and Faraday is running and loading my test data. However when I try to see it on the ui it does not show the data.

**Comment by joaquinlpereyra** [comment]
Hello @ricardojcampo! When you say the UI is now showing the data, do you mean the Web UI or the client? Are you sure you're going to the correct URL? You should be connecting to http://faraday-server:port/_ui.

We have a known bug right now where Faraday will tell you to connect to the old Couch url, and this could result in the problem you're facing.

We're sorry for the trouble! This should be fixed in the next release.

**Comment by ricardojcampo** [comment]
Hello@joaquinlpereyra. Thank you for your reply, I mean the web ui. I have followed the first steps to the letter and have successfully shared information across the net between two clients :-); which is fantastic. Unfortunately, the cool thing (for management) which is the web ui and what I can show to my boss to make a case to this program is not working :-(. The way I have configured it is:
- I have the couchdb database bind to my server ip 
- I have local faraday servers running connecting to the couchdb on each client; Ihave tried a farday server and clients connecting to it, but it does not work. 
- I have the couchdb password portected. 

The GTK interface works fine, except I cannot add anything to it directly, only import reports, that is a minor thing, but the Web ui does not load the data even though its asking me for the password.

Does the config.xml file has anything to do with this? I have look over it and changed the couchuri tag to no avail. Anywhere else I could look at to fix the issue? 

Thank you for your help.

**Comment by joaquinlpereyra** [comment]
@ricardojcampo Hi! Thanks for this information. You should take into account that the Community version doesn't support authentication at the moment. You can try to log in directly to CouchDB via the http://couchdb:port/_utils page and then use the WebUI, that should work. Our Corporate versions do have better authorization and authentication options :) 

Let me know of any other problems you have!

**Comment by ricardojcampo** [comment]
Hello Joaquilpereyra, I am surprised to hear that, as I was under the impressions it did or it is supposed to. In www.faradaysec.com - Let's talk business page it says that the community version support users. I imagine most of us in the pen testing business, would take this as authorisations. Are there any plans to fix this serious deficiency or change the page on the website? I imagine there are a few pen testers using this tool that are unaware of this.

**Comment by f-amato** [comment]
Hi @ricardojcampo, you have to configure your connection server using http[s]://user:pass@faradayserver:port
Faraday Community doesn't support ABM of users and different profiles but authentication is supported.

If you click on Web UI icon on GTK that will open your browser user the right address if you want to enter directly you have to use  http[s]://user:pass@faraday-server:port/_ui

There are some users that use an extra layer of security for example using Apache Nginx adding a global authentication.

Let us know if this fix your problem.

**Comment by f-amato** [comment]
Hi @ricardojcampo 
Let us know if you have any feedback regarding this issue?

Thanks
