### ISSUE TITLE
couchdb and sqlite

### ISSUE THREAD

**Issue by jorge-1** [infobyte/faraday#119]
Why do you use sqlight and couchdb together?

**Comment by joaquinlpereyra** [comment]
@jorge-1 It's just a transition stage, we're planning on fully moving towards sqlite in the very near future :)

**Comment by jorge-1** [comment]
Please tell my why you migrate from no sql couchdb to sqlite?

**Comment by joaquinlpereyra** [comment]
@jorge-1 We were having trouble scaling up with a non-relational database. Are you interested in developing something for Faraday which required CouchDB?
