### ISSUE TITLE
[BUG][DEPRECATE][FIXED][Faraday_v2] QPainter Cannot paint null pixmap error as non-privileged user

### ISSUE THREAD

**Issue by caoimhinp** [infobyte/faraday#12]
If a non-privileged user starts faraday the following output is obvserved.
The gui does start but it doesn't have the menus and has a default style.

###Output from non-privileged user in /opt/faraday-dev:###

user:/opt/faraday-dev$ ./faraday

[+] Starting faraday IDE
[*] QTconfig in place
[*] Running under plugin development mode!
[-] Deleting old user directory: /home/user/.faraday
[+] Creating user directory: /home/user/.faraday
[*] Loading Plugins
[*] Using images/icons set from user
[*] Using custom user configuration
[*] Cleaning up
rm: cannot remove `/opt/faraday-dev/shell/core/_helpers.so': Permission denied
[+] Setting up for: x86_64 on Linux
ln: failed to create symbolic link `/opt/faraday-dev/shell/core/_helpers.so': File exists
[+] Using python2.7 to run faraday.
2014-07-10 11:58:42,347 - CouchdbManager - DEBUG - Initializing CouchDBManager for url 

[http://admin:faradaypassword@127.0.0.1:5984]
2014-07-10 11:58:42,348 - CouchdbManager - DEBUG - Setting user,pass admin faradaypassword
QPainter::begin: Cannot paint null pixmap
QPainter::setPen: Will be reset by begin()

**Comment by Ezequieltbh** [comment]
Hi caoimhinp !
Our QT interface is now deprecated.
GTK is the new Graphical interface for Faraday.
We are closing this ticket for this.
Cheers!
