### ISSUE TITLE
MAC OSX 10.11.6 error

### ISSUE THREAD

**Issue by hktalent** [infobyte/faraday#120]
sudo ./install.sh
Password:
[+] Install Darwin 15.6.0 x86_64
./install.sh: line 56: apt-get: command not found
./install.sh: line 60: apt-get: command not found
Traceback (most recent call last):
  File "/usr/local/bin/pip2", line 9, in <module>
    load_entry_point('pip==8.1.2', 'console_scripts', 'pip2')()
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 565, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2597, in load_entry_point
    raise ImportError("Entry point %r not found" % ((group, name),))
ImportError: Entry point ('console_scripts', 'pip2') not found
You can now run Faraday, enjoy!

**Comment by hktalent** [comment]
brew install CouchDB
cd /usr/local/etc/couchdb
vi default.ini
port to 5985

sudo pip install --ignore-installed --trusted-host pypi.douban.com  -i http://pypi.douban.com/simple -r requirements.txt
sudo pip install --ignore-installed --trusted-host pypi.douban.com  -i http://pypi.douban.com/simple sqlalchemy pyopenssl
sudo pip install --ignore-installed --trusted-host pypi.douban.com  -i http://pypi.douban.com/simple pyopenssl


$ ./faraday-server.py
Checking dependencies
2016-09-15 17:07:39,474 - faraday-server.server.database - ERROR - Unauthorized access to CouchDB. Make sure faraday-server's configuration file has CouchDB admin's credentials set

**Comment by Ezequieltbh** [comment]
Hi!
install.sh is only for debian based distributions, for OS X you need install all manually.
More information here: [Installation OS X](https://github.com/infobyte/faraday/wiki/installation-client#osx)

Also, you need set the Couchdb user and password (Empty if you not configure none user and password in Couchdb) in ~/.faraday/config/server.ini

[couchdb]
user=
password=

Thats is all!
Cheers!

**Comment by f-amato** [comment]
Any feedback regarding this issue?

Thanks

**Comment by hktalent** [comment]
@Ezequieltbh  so ~~ good！thank you

**Comment by Ezequieltbh** [comment]
Hi!
You need set your user and password, if you have one in couchdb.
Remember set this, in the faraday server (~/.faraday/config/server.ini Config file) 
Also, in the client GTK ~/.faraday/config/user.xml

Set **couch_uri** Field : **http://USERNAME:PASSWORD@IP:PORT**

Cheers!

**Comment by Ezequieltbh** [comment]
Any feedback about this?
