### ISSUE TITLE
Ability to add workspace from command line (feature request)

### ISSUE THREAD

**Issue by securisec** [infobyte/faraday#122]
Please add the option to add workspaces from the command line. This would really help with the automation process.

**Comment by lmcthbe** [comment]
Same request with deletion otherwise  I cannot integrate Faraday in my devsecops without this

**Comment by joaquinlpereyra** [comment]
This feature is coming really soon. We'll provide an extensive API to interact with the Faraday Server via Python with no need to have the client up!

**Comment by lmcthbe** [comment]
Great. Thanks

**Comment by securisec** [comment]
Hi faraday, are you guys releasing the new version soon with the extended api?

**Comment by Ezequieltbh** [comment]
Hi people!
We are now in testing phase, in one or two weeks maximum, we can release our last version with these features.
Cheers!

**Comment by Ezequieltbh** [comment]
Hi people!
The library for communicate in the server are in persistence/server/models.py
Documentation are in development but is simple.
That library can communicate with Faraday server and return Faraday ready objects.
If you need more information or examples, take a look the bin folder and his scripts.
Cheers!

**Comment by lmcthbe** [comment]
Hi,

After updating to latest faraday, I looked into the above mentioned files and scripts for example however I was not able to understand how to create new workspace using the new API.

I was expecting to be able to use curl via the rest API server (9977) to do it?
Which script example can I use ?

Regards

**Comment by lmcthbe** [comment]
Hi,

After several tries and errors, I got it to work with the following request:
curl -H 'Content-Type: application/json' -X PUT -d '{"name":"test1234", "type":"Workspace"}' http://user:password@ip:5984/_api/ws/test1234
{"ok":true}

Regards

**Comment by Ezequieltbh** [comment]
Hi @lmcthbe!
/persistence/server/server.py is our library for communicate with Faraday server, this contains all methods for create, update and delete all objects in Faraday.

Here an example for use this.

```
#!/usr/bin/python2.7
from persistence.server import server
import time

server.FARADAY_UP = False
#Change this with your Faraday server url
server.SERVER_URL = "http://faraday:faraday@127.0.0.1:5984"

date_today = int(time.time() * 1000)
server.create_workspace('workspacename', 'DESCRIPTION', date_today, date_today, 'CUSTOMER NAME')
```

**Comment by lmcthbe** [comment]
Great. Thanks for the example in python 
As my security scanning script is in bash I might prefer curl request for now

Regards
/Thierry

**Comment by lmcthbe** [comment]
The workspace created with the curl request could not be activated so I will use your example (that works fine) instead and integrate it.

Last question, is there an API to activate a newly created workspace?

/Thierry

**Comment by lmcthbe** [comment]
I got the following error when running the python script
Traceback (most recent call last):
  File "createws.py", line 5, in <module>
    from persitence.server import server
ImportError: No module named persitence.server

**Comment by Ezequieltbh** [comment]
Hi @lmcthbe!
First question: what do you mean with activate a workspace? Using our library you can create a workspace without any problem, the creation is instant.

Second question: module is named persistence, not persitence :P

**Comment by lmcthbe** [comment]
The API creates the workspace in this example "mdn_3_1_cp04_test" but it is not "active" .

The ~/.faraday/report/mdn_3_1_cp04_test does not exist until from the UI, I double clicked it on "mdn_3_1_cp04_test" so it is not possible to copy any scan result in it for faraday to process them

/Thierry

I noticed the typo with persistence. Thanks

![screenshot from 2017-01-05 16 49 20](https://cloud.githubusercontent.com/assets/1301592/21698903/4688e898-d367-11e6-97f3-2e5516ad65ea.png)

**Comment by Ezequieltbh** [comment]
You're welcome!

One question, later of create that workspace with our library, you double click it workspace in GTK for switch to that and what happen? It should set the active workspace and create workspace folder are you looking for.

**Comment by lmcthbe** [comment]
Yes it does but having an API to active the created workspace will help to automate completely my devsecops that perform the following:

1.deploy the nightly build
2.Create Faraday workspace via API with nightly build name number
3.Active Faraday newly created workspace (workspace folder created) <-- missing piece
4.Run security scanning (nessus, nexpose, nmap, openvas,...) with xml ouput
5.Copy/Move all xml output to workspace folder created with nightly build name number. Faraday parses the data
6.Look at the result when coming to work :-)
7.To be repeated every night using jenkins job
/Thierry

**Comment by Ezequieltbh** [comment]
Oh , i understand now!

We recommend use Faraday cli for this kind of jobs, that free to you of manage active workspaces and copy reports files.
More information about Faraday cli for import reports here: [Faraday cli wiki](https://github.com/infobyte/faraday/wiki/Usage#cli)

I added this issue to our list of tasks for coming iterations, but with faraday cli should are all ok!

**Comment by lmcthbe** [comment]
Great. I did not know about this 

Perfect, I gonna try it tomorrow 

Keep up the good work, Faraday is really great tool and help me a lot to sort out all the information quickly from the security scanning

/Thierry 

Envoyé de mon iPhone

**Comment by Ezequieltbh** [comment]
Thanks @lmcthbe!
We appreciate your support! We are working hard for do of Faraday a better tool!
I close this issue, if you need more help open other again or contact us for IRC.
