### ISSUE TITLE
bug in interface of hosts services

### ISSUE THREAD

**Issue by jorge-1** [infobyte/faraday#124]
In page host/ws/mycompany/hid/_same_id_12345, I`m click to number of vulns on service and then redirect to **status/ws/mycompany/search/service=80**, but this give all hosts with vulns on 80 port, correct is /**status/ws/mycompany/search/service=80&target=192.168.1.15**

**Comment by joaquinlpereyra** [comment]
@jorge-1 Just tested this and could replicate. We'll be fixing this on the near future! Thanks!

**Comment by Ezequieltbh** [comment]
Hi @jorge-1!
That bug is fixed now, in the last version.
Cheers!
