### ISSUE TITLE
Many bugs in web ui

### ISSUE THREAD

**Issue by jorge-1** [infobyte/faraday#125]
I`m find a few bugs in Web UI faraday, example:
1. Filtered host in hosts/ws/mycompany, then select one hosts and click edit I`m receive message "Oops! No hosts were selected to edit"
2. Replication workspace dos`t work correctly, In all my tests I lost 1-20 hosts.

All this bug detecting then using workspace few days, scan multiple scaners, remove and add hosts and vulns. In clear install faraday all is well

**Comment by joaquinlpereyra** [comment]
@jorge-1 I was able to replicate your fist issue. Regarding replication, could you post the output of the process here? Are you following the process listed on our wiki? Thanks for the extra information.

**Comment by Ezequieltbh** [comment]
Any feedback about this issue of replication?
Thanks!
