### ISSUE TITLE
Issue creating workspaces from the web

### ISSUE THREAD

**Issue by securisec** [infobyte/faraday#131]
Hello, it seems like after the update, there may be an issue creating a workspace from the web interface. i am launching the web interface one of two ways, but manually typing the url, but in most cases, but clicking the icon on the gtk. It keeps saying that I am not an admin, but there is no other user besides the admin. Any suggestions?

-- is it possible to create a workspace on demand using python?

**Comment by joaquinlpereyra** [comment]
Hi @securisec! Try going to ```http://faradayserver:port/_utils/index.html```. That index.html part is rather important. Are you logged in there? If not, log in into your couch admin account and try again. You should be able to create and delete workspaces now :)

About creating workspaces on demand using Python, we're working (and pretty much finished all but small details) on an extensive API which will allow you to interact with Faraday Server without even having the client open. So in the very near future you should be able to create workspaces on demand with Python, yes :)

**Comment by securisec** [comment]
Thanks for the solution! That solved my issue! And really really looking forward to that api! Thanks again for the good work you guys do!
