### ISSUE TITLE
Feature request - See / sort results by tools and ability to disable bounty panel

### ISSUE THREAD

**Issue by securisec** [infobyte/faraday#133]
It would be nice to see an option where one can see the output of a certain tool vs all. Sometimes, the findings are duplicated when multiple tools are run and parsed, and that can tend to make the output very confusing as it scales. 

Also, an option to disable the bounty panel for users that do not really use it.

**Comment by joaquinlpereyra** [comment]
@securisec Hi! We're working in the backend so that, hopefully, we can provide both of those features in the near future!  Thanks for the input!

**Comment by securisec** [comment]
Well done on the new update! did you guys add the new extended api or add and manage workspaces from the command line?

**Comment by Ezequieltbh** [comment]
Hi @securisec !
The new api is here!
The library for communicate in the server are in persistence/server/models.py
Documentation are in development but is simple.
That library can communicate with Faraday server and return Faraday ready objects.
If you need more information or examples, take a look the bin folder and his scripts.
Cheers!
