### ISSUE TITLE
{"error":"not_found","reason":"no_db_file"}

### ISSUE THREAD

**Issue by JonLittleIT** [infobyte/faraday#135]
How come this happens?

http://127.0.0.1:5984/reports/_design/reports/index.html

sudo service couchdb start

db was started.

curl http://127.0.0.1:5984/
{"couchdb":"Welcome","uuid":"d9d75ccec5c903944a4861ab82dee07d","version":"1.6.2","vendor":{"name":"The Apache Software Foundation","version":"1.6.2"}}

**Comment by Ezequieltbh** [comment]
Hi!
In Faraday 2.0 we have a Faraday Server now, because this our url to the Web Ui has changed.
https://github.com/infobyte/faraday/wiki/First-steps#setup
Follow this steps for configure server and you can use http://localhost:5984/_ui for go to Web UI.
Cheers!

**Comment by JonLittleIT** [comment]
Thanks!
