### ISSUE TITLE
Request: recon-ng

### ISSUE THREAD

**Issue by vdun** [infobyte/faraday#142]
https://bitbucket.org/LaNMaSteR53/recon-ng/

**Comment by Ezequieltbh** [comment]
Thanks for the suggestion @vdun ! We will add this to the list of plugin requests.
Cheers!

**Comment by captainkyd** [comment]
omg yes... any news on development here?

**Comment by Ezequieltbh** [comment]
@captainkyd Working on it!
It will be ready for the next version 3.0!

**Comment by captainkyd** [comment]
you just made my day :-D

**Comment by llazzaro** [comment]
HI @captainkyd  @vdun,

the plugin for reconng is available.
You can check the code here: https://github.com/infobyte/faraday/blob/master/plugins/repo/reconng/plugin.py
It supports json format of reconng.
