### ISSUE TITLE
Issues running faraday.py

### ISSUE THREAD

**Issue by horusint** [infobyte/faraday#149]
I make instalation according to https://github.com/infobyte/faraday/wiki/installation-client#debian
With netstat i ca see port 5985 its listening
Couchdb is up

On http://127.0.0.1:5985/_ui see "nodbfile"

faraday.GTK - ERROR - Can't find anything on URL http://127.0.0.1:5985/_api/ws

**Comment by Ezequieltbh** [comment]
Hi @horusint !
I think this is a problem with your configuration between couchdb and Faraday server.
5985 is the port with couchdb running, but this should be the faraday server port.
Can you check your configuration of couchdb (/etc/couchdb/local.ini), if the port is 5984?
And check your faraday server config ~/.faraday/config/server.ini, if the port is 5985?
Cheers!

**Comment by horusint** [comment]
Hi, we check and its ok. now after delete  ~/.faraday/config/server.ini and reload faraday server seems to be ok.
Cheers!

**Comment by Ezequieltbh** [comment]
Excelent!
Thanks for contacting us...
Cheers!
