### ISSUE TITLE
Request: Amazon Inspector Results Import

### ISSUE THREAD

**Issue by NoahJaehnert** [infobyte/faraday#150]
Amazon released their own vulnerability scanning tool, called Amazon Inspector. Per Amazon: 

> Amazon Inspector is an automated security assessment service that helps improve the security and compliance of applications deployed on AWS. Amazon Inspector automatically assesses applications for vulnerabilities or deviations from best practices. After performing an assessment, Amazon Inspector produces a detailed list of security findings prioritized by level of severity.
> To help you get started quickly, Amazon Inspector includes a knowledge base of hundreds of rules mapped to common security best practices and vulnerability definitions. Examples of built-in rules include checking for remote root login being enabled, or vulnerable software versions installed. These rules are regularly updated by AWS security researchers.

Rules/check packages include: 

- Common Vulnerabilities and Exposures
- CIS Operating System Security Configuration Benchmarks
- Security Best Practices
- Runtime Behavior Analysis 

More details here: https://aws.amazon.com/inspector/

Inspector results can be dumped to CSV or be queried via the AWS command line using the describe-findings command (http://docs.aws.amazon.com/cli/latest/reference/inspector/describe-findings.html)

Would love the ability to import results to Faraday!

**Comment by Ezequieltbh** [comment]
Hi @NoahJaehnert!
We will add this to the list of plugin requests for development.
If you like, we can help you in the development of this plugin!
Let me know if you are interested in that.
Cheers!
