### ISSUE TITLE
skipfish not woking with parameter -k

### ISSUE THREAD

**Issue by robertfiz** [infobyte/faraday#157]
Utilizando el siguiente comando skipfishr -k 0:1:50 me arrroja el siguiente error:
this command: -skipfish k 0:1:50 
produces:
2016-12-16 00:16:33,605 - faraday - DEBUG - Traceback (most recent call last):
  File "/usr/share/python-faraday/plugins/plugin.py", line 345, in run
    self.plugin.processOutput(output)
  File "/usr/share/python-faraday/plugins/plugin.py", line 112, in processOutput
    self.parseOutputString(output)
  File "/root/.faraday/plugins/skipfish/plugin.py", line 136, in parseOutputString
    p = SkipfishParser(self._output_path)
  File "/root/.faraday/plugins/skipfish/plugin.py", line 51, in __init__
    False)[1] + "]")
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 380, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Invalid \escape: line 7 column 61 (char 457)

**Comment by Ezequieltbh** [comment]
Hola @robertfiz!
Por lo que veo es un problema con el comando en si de skipfish que esta generando un output invalido.
Podes probar el mismo comando en una terminal fuera de Faraday, para revisar que este sea correcto?
Ademas, copia el comando completo por aca, junto con su salida, asi podemos revisarlo mejor
Saludos!

**Comment by robertfiz** [comment]
@Ezequieltbh
El comando que yo escribo tanto en faraday como en skipfish es -k 0:2:0 http://testphp.vulnweb.com
en faraday le agrega el archivo de salida

> 
> salida de faraday:
> skipfish version 2.10b by lcamtuf@google.com
> 
>   - testphp.vulnweb.com -
> 
> Scan statistics:
> 
>       Scan time : 0:02:01.010
>   HTTP requests : 1773 (15.5/s), 847 kB in, 382 kB out (10.2 kB/s)  
>     Compression : 211 kB in, 402 kB out (31.1% gain)    
>     HTTP faults : 0 net errors, 0 proto errors, 0 retried, 0 drops
>  TCP handshakes : 21 total (123.5 req/conn)  
>      TCP faults : 0 failures, 0 timeouts, 1 purged
>  External links : 41 skipped
>    Reqs pending : 820        
> 
> Database statistics:
> 
>          Pivots : 56 total, 14 done (25.00%)    
>     In progress : 15 pending, 20 init, 5 attacks, 2 dict     
>   Missing nodes : 8 spotted
>      Node types : 1 serv, 20 dir, 8 file, 0 pinfo, 16 unkn, 10 par, 1 val
>    Issues found : 28 info, 0 warn, 8 low, 5 medium, 1 high impact
>       Dict size : 47 words (47 new), 5 extensions, 256 candidates
>      Signatures : 77 total
>         
> [!] Scan aborted by user, bailing out!
> [+] Copying static resources...
> [+] Sorting and annotating crawl nodes: 56
> [+] Looking for duplicate entries: 56
> [+] Counting unique nodes: 55
> [+] Saving pivot data for third-party tools...
> [+] Writing scan description...
> [+] Writing crawl tree: 56
> [+] Generating summary views...
> [+] Report saved to '/root/.faraday/data/skipfish_output-9.42129990127/index.html' [0x23227c7e].
> [+] This was a great day for science!
> 
> salida del debug: 
> 
> faraday ui is ready              
> Make sure you got couchdb up and running.
> If couchdb is up, point your browser to: 
> [http://127.0.0.1:5985/_ui]
> 
> 2016-12-16 14:21:59,732 - faraday - DEBUG - Starting application...
> 2016-12-16 14:21:59,733 - faraday - DEBUG - Setting up remote API's...
> 2016-12-16 14:21:59,733 - faraday - DEBUG - starting XMLRPCServer with api_conn_info = ('localhost', 9881)
> 2016-12-16 14:21:59,735 - faraday - INFO - XMLRPC API server configured on ('localhost', 9881)
> 2016-12-16 14:21:59,736 - faraday - DEBUG - Starting model controller daemon...
> 2016-12-16 14:21:59,737 - faraday - DEBUG - starting xmlrpc api server...
> 2016-12-16 14:21:59,872 - faraday - INFO - REST API server configured on ('localhost', 9981)
> 2016-12-16 14:21:59,897 - faraday - DEBUG - Faraday ready...
> 2016-12-16 14:22:22,753 - faraday - INFO - Removing Workspace: vulnweb
> 2016-12-16 14:22:45,740 - faraday - INFO - Creating workspace 'vulnweb'
> 2016-12-16 14:22:45,742 - faraday - DEBUG - Looking for the delegation class
> 2016-12-16 14:25:55,882 - faraday.PluginController - DEBUG - Created plugin_process (2893636012) for plugin instance (2893538604)
> 2016-12-16 14:25:55,919 - faraday - DEBUG - ----------------------------------------
> 2016-12-16 14:25:55,931 - faraday - DEBUG - proc_name = PluginProcess-1
> 2016-12-16 14:25:55,931 - faraday - DEBUG - Starting run method on PluginProcess
> 2016-12-16 14:25:55,932 - faraday - DEBUG - parent process: 5781
> 2016-12-16 14:25:55,935 - faraday - DEBUG - process id: 5870
> 2016-12-16 14:25:55,936 - faraday - DEBUG - ----------------------------------------
> 2016-12-16 14:25:55,988 - faraday - DEBUG - PluginProcess-1: New Output
> 2016-12-16 14:25:55,991 - faraday - DEBUG - Plugin raised an exception:
> 2016-12-16 14:25:56,036 - faraday - DEBUG - Traceback (most recent call last):
>   File "/opt/faraday-dev/plugins/plugin.py", line 345, in run
>     self.plugin.processOutput(output)
>   File "/opt/faraday-dev/plugins/plugin.py", line 112, in processOutput
>     self.parseOutputString(output)
>   File "/root/.faraday/plugins/skipfish/plugin.py", line 141, in parseOutputString
>     p = SkipfishParser(self._output_path)
>   File "/root/.faraday/plugins/skipfish/plugin.py", line 55, in __init__
>     [1] + "];")
>   File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
>     return _default_decoder.decode(s)
>   File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
>     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
>   File "/usr/lib/python2.7/json/decoder.py", line 380, in raw_decode
>     obj, end = self.scan_once(s, idx)
> ValueError: Expecting , delimiter: line 3 column 169 (char 217)
> 
> 2016-12-16 14:25:56,037 - faraday - DEBUG - PluginProcess-1: Exiting
> 2016-12-16 14:25:56,039 - faraday.PluginController - DEBUG - _processAction - 3000 - parameters = ['Skipfish']
> 2016-12-16 14:25:56,065 - faraday.PluginController - DEBUG - _processAction - 3001 - parameters = ['Skipfish']
> 2016-12-16 14:25:56,090 - faraday - DEBUG - _processAction - 3000 - parameters = ('Skipfish',)
> 2016-12-16 14:25:56,091 - faraday.ModelController - INFO - Plugin Started: Skipfish
> 2016-12-16 14:25:56,092 - faraday - DEBUG - _processAction - 3001 - parameters = ('Skipfish',)
> 2016-12-16 14:25:56,097 - faraday.ModelController - INFO - Plugin Ended: Skipfish
> 2016-12-16 14:27:16,176 - faraday - INFO - Closing Faraday...
> 2016-12-16 14:27:16,177 - faraday - DEBUG - stopping model controller thread...
> 2016-12-16 14:27:16,177 - faraday - DEBUG - server stopping...
> 2016-12-16 14:27:16,178 - faraday - DEBUG - called stop on xmlrpc server
> 2016-12-16 14:27:16,980 - faraday - DEBUG - server forever stopped by flag
> 2016-12-16 14:27:16,981 - faraday - DEBUG - serve_forever ended
> 2016-12-16 14:27:16,981 - faraday - DEBUG - xmlrpc thread joined
> 2016-12-16 14:27:18,977 - faraday - DEBUG - Waiting for controller threads to end...
> root@kali:/opt/faraday-dev# 
> 
> salida en el sample.js del skipfish de faraday:
> var mime_samples = [
>   { 'mime': 'application/xhtml+xml', 'samples': [
>     { 'url': 'http://testphp.vulnweb.com/', 'dir': '_m0/0', 'linked': 2, 'len': 4096 },
>     { 'url': 'http://testphp.vulnweb.com/guestbook.php', 'dir': '_m0/1', 'linked': 2, 'len': 4531 },
>     { 'url': 'http://testphp.vulnweb.com/AJAX/', 'dir': '_m0/2', 'linked': 2, 'len': 4236 } ]
>   },
>   { 'mime': 'text/css', 'samples': [
>     { 'url': 'http://testphp.vulnweb.com/AJAX/styles.css', 'dir': '_m1/0', 'linked': 2, 'len': 562 } ]
>   },
>   { 'mime': 'text/html', 'samples': [
>     { 'url': 'http://testphp.vulnweb.com/sfi9876', 'dir': '_m2/0', 'linked': 2, 'len': 168 },
>     { 'url': 'http://testphp.vulnweb.com/hpp/', 'dir': '_m2/1', 'linked': 2, 'len': 203 },
>     { 'url': 'http://testphp.vulnweb.com/Mod_Rewrite_Shop/', 'dir': '_m2/2', 'linked': 2, 'len': 975 } ]
>   },
>   { 'mime': 'text/plain', 'samples': [
>     { 'url': 'http://testphp.vulnweb.com/sfi9876.php', 'dir': '_m3/0', 'linked': 2, 'len': 16 },
>     { 'url': 'http://testphp.vulnweb.com/AJAX/showxml.php', 'dir': '_m3/1', 'linked': 0, 'len': 11 },
>     { 'url': 'http://testphp.vulnweb.com/showimage.php', 'dir': '_m3/2', 'linked': 2, 'len': 1 },
>     { 'url': 'http://testphp.vulnweb.com/showimage.php?file=\x27%20%20%20pict.item(0).firstChild.nodeValue%20%20%20\x27', 'dir': '_m3/3', 'linked': 2, 'len': 377 },
>     { 'url': 'http://testphp.vulnweb.com/userinfo.php', 'dir': '_m3/4', 'linked': 5, 'len': 14 } ]
>   },
>   { 'mime': 'text/xml', 'samples': [
>     { 'url': 'http://testphp.vulnweb.com/showimage.php?file=sfish\x3e\x27\x3e\x22\x3e\x3csfish\x3e\x3c/sfish\x3e', 'dir': '_m4/0', 'linked': 2, 'len': 345 } ]
>   }
> ];
> 
> var issue_samples = [
>   { 'severity': 4, 'type': 50107, 'samples': [
>     { 'url': 'http://testphp.vulnweb.com/showimage.php?file=http://www.google.com/humans.txt%23foo%3D', 'extra': 'remote file inclusion', 'sid': '0', 'dir': '_i0/0' } ]
>   },
>   { 'severity': 3, 'type': 40402, 'samples': [
>     { 'url': 'http://testphp.vulnweb.com/showimage.php?file=\x27%20%20%20pict.item(0).firstChild.nodeValue%20%20%20\x27', 'extra': 'PHP warning (text)', 'sid': '22019', 'dir': '_i1/0' } ]
>   },
>   { 'severity': 3, 'type': 40304, 'samples': [
>     { 'url': 'http://testphp.vulnweb.com/showimage.php?file=.htaccess.aspx--\x3e\x22\x3e\x27\x3e\x27\x22\x3csfi000013v706274\x3e', 'extra': '', 'sid': '0', 'dir': '_i2/0' } ]
>   },
>   { 'severity': 3, 'type': 40301, 'samples': [
>     { 'url': 'http://testphp.vulnweb.com/showimage.php?file=.htaccess.aspx--\x3e\x22\x3e\x27\x3e\x27\x22\x3csfi000013v706274\x3e', 'extra': 'text/plain', 'sid': '0', 'dir': '_i3/0' },
>     { 'url': 'http://testphp.vulnweb.com/showimage.php?file=sfish\x3e\x27\x3e\x22\x3e\x3csfish\x3e\x3c/sfish\x3e', 'extra': 'text/xml', 'sid': '0', 'dir': '_i3/1' } ]
>   },
>   { 'severity': 3, 'type': 40101, 'samples': [
>     { 'url': 'http://testphp.vulnweb.com/showimage.php?file=.htaccess.aspx--\x3e\x22\x3e\x27\x3e\x27\x22\x3csfi000013v706274\x3e', 'extra': 'injected \x27\x3csfi...\x3e\x27 tag seen in HTML', 'sid': '0', 'dir': '_i4/0' } ]
>   },
>   { 'severity': 2, 'type': 30601, 'samples': [
>     { 'url': 'http://testphp.vulnweb.com/search.php?test=query', 'extra': '', 'sid': '0', 'dir': '_i5/0' },
>     { 'url': 'http://testphp.vulnweb.com/guestbook.php', 'extra': '', 'sid': '0', 'dir': '_i5/1' },
>     { 'url': 'http://testphp.vulnweb.com/search.php?test=query', 'extra': '', 'sid': '0', 'dir': '_i5/2' },
>     { 'url': 'http://testphp.vulnweb.com/search.php?test=query', 'extra': '', 'sid': '0', 'dir': '_i5/3' } ]
>   },
>   { 'severity': 2, 'type': 30501, 'samples': [
>     { 'url': 'http://testphp.vulnweb.com/', 'extra': 'http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=6,0,29,0', 'sid': '0', 'dir': '_i6/0' },
>     { 'url': 'http://testphp.vulnweb.com/guestbook.php', 'extra': 'http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=6,0,29,0', 'sid': '0', 'dir': '_i6/1' },
>     { 'url': 'http://testphp.vulnweb.com/login.php', 'extra': 'http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=6,0,29,0', 'sid': '0', 'dir': '_i6/2' },
>     { 'url': 'http://testphp.vulnweb.com/showimage.php?file=404.php', 'extra': 'http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=6,0,29,0', 'sid': '0', 'dir': '_i6/3' } ]
>   },
>   { 'severity': 0, 'type': 10803, 'samples': [
>     { 'url': 'http://testphp.vulnweb.com/sfi9876', 'extra': '', 'sid': '0', 'dir': '_i7/0' },
>     { 'url': 'http://testphp.vulnweb.com/AJAX/.sf/', 'extra': '', 'sid': '0', 'dir': '_i7/1' },
>     { 'url': 'http://testphp.vulnweb.com/AJAX/index.php/.htaccess.aspx--\x3e\x22\x3e\x27\x3e\x27\x22\x3csfi000025v706274\x3e', 'extra': '', 'sid': '0', 'dir': '_i7/2' },
>     { 'url': 'http://testphp.vulnweb.com/AJAX/showxml.php', 'extra': '', 'sid': '0', 'dir': '_i7/3' },
>     { 'url': 'http://testphp.vulnweb.com/AJAX/styles.css', 'extra': '', 'sid': '0', 'dir': '_i7/4' },
>     { 'url': 'http://testphp.vulnweb.com/hj/', 'extra': '', 'sid': '0', 'dir': '_i7/5' },
>     { 'url': 'http://testphp.vulnweb.com/hj/var/', 'extra': '', 'sid': '0', 'dir': '_i7/6' },
>     { 'url': 'http://testphp.vulnweb.com/hj/var/www/', 'extra': '', 'sid': '0', 'dir': '_i7/7' },
>     { 'url': 'http://testphp.vulnweb.com/hj/', 'extra': '', 'sid': '0', 'dir': '_i7/8' },
>     { 'url': 'http://testphp.vulnweb.com/hj/var/', 'extra': '', 'sid': '0', 'dir': '_i7/9' },
>     { 'url': 'http://testphp.vulnweb.com/hj/var/www/', 'extra': '', 'sid': '0', 'dir': '_i7/10' },
>     { 'url': 'http://testphp.vulnweb.com/hpp/', 'extra': '', 'sid': '0', 'dir': '_i7/11' },
>     { 'url': 'http://testphp.vulnweb.com/Mod_Rewrite_Shop/', 'extra': '', 'sid': '0', 'dir': '_i7/12' },
>     { 'url': 'http://testphp.vulnweb.com/showimage.php', 'extra': '', 'sid': '0', 'dir': '_i7/13' },
>     { 'url': 'http://testphp.vulnweb.com/showimage.php?file=\x27%20%20%20pict.item(0).firstChild.nodeValue%20%20%20\x27', 'extra': '', 'sid': '0', 'dir': '_i7/14' },
>     { 'url': 'http://testphp.vulnweb.com/userinfo.php', 'extra': '', 'sid': '0', 'dir': '_i7/15' } ]
>   },
>   { 'severity': 0, 'type': 10801, 'samples': [
>     { 'url': 'http://testphp.vulnweb.com/sfi9876.php', 'extra': 'text/plain', 'sid': '0', 'dir': '_i8/0' },
>     { 'url': 'http://testphp.vulnweb.com/AJAX/showxml.php', 'extra': 'text/plain', 'sid': '0', 'dir': '_i8/1' },
>     { 'url': 'http://testphp.vulnweb.com/showimage.php', 'extra': 'text/plain', 'sid': '0', 'dir': '_i8/2' },
>     { 'url': 'http://testphp.vulnweb.com/showimage.php?file=\x27%20%20%20pict.item(0).firstChild.nodeValue%20%20%20\x27', 'extra': 'text/plain', 'sid': '0', 'dir': '_i8/3' },
>     { 'url': 'http://testphp.vulnweb.com/showimage.php?file=404.php', 'extra': 'application/xhtml+xml', 'sid': '0', 'dir': '_i8/4' },
>     { 'url': 'http://testphp.vulnweb.com/userinfo.php', 'extra': 'text/plain', 'sid': '0', 'dir': '_i8/5' } ]
>   },
>   { 'severity': 0, 'type': 10602, 'samples': [
>     { 'url': 'http://testphp.vulnweb.com/userinfo.php', 'extra': '', 'sid': '0', 'dir': '_i9/0' } ]
>   },
>   { 'severity': 0, 'type': 10505, 'samples': [
>     { 'url': 'http://testphp.vulnweb.com/guestbook.php', 'extra': 'text', 'sid': '0', 'dir': '_i10/0' } ]
>   },
>   { 'severity': 0, 'type': 10405, 'samples': [
>     { 'url': 'http://testphp.vulnweb.com/AJAX/showxml.php', 'extra': '', 'sid': '0', 'dir': '_i11/0' },
>     { 'url': 'http://testphp.vulnweb.com/showimage.php?file=404.php', 'extra': '', 'sid': '0', 'dir': '_i11/1' } ]
>   },
>   { 'severity': 0, 'type': 10205, 'samples': [
>     { 'url': 'http://testphp.vulnweb.com/sfi9876', 'extra': '', 'sid': '0', 'dir': '_i12/0' },
>     { 'url': 'http://testphp.vulnweb.com/sfi9876.php', 'extra': '', 'sid': '0', 'dir': '_i12/1' } ]
>   },
>   { 'severity': 0, 'type': 10204, 'samples': [
>     { 'url': 'http://testphp.vulnweb.com/', 'extra': 'X-Powered-By', 'sid': '0', 'dir': '_i13/0' } ]
>   },
>   { 'severity': 0, 'type': 10202, 'samples': [
>     { 'url': 'http://testphp.vulnweb.com/', 'extra': 'nginx/1.4.1', 'sid': '0', 'dir': '_i14/0' } ]
>   }
> ];
> 
> salida en el sample sin faraday:
> root@kali:~/salida2# cat samples.js
> var mime_samples = [
>   { 'mime': 'application/xhtml+xml', 'samples': [
>     { 'url': 'http://testphp.vulnweb.com/', 'dir': '_m0/0', 'linked': 2, 'len': 4096 },
>     { 'url': 'http://testphp.vulnweb.com/guestbook.php', 'dir': '_m0/1', 'linked': 2, 'len': 4531 },
>     { 'url': 'http://testphp.vulnweb.com/AJAX/', 'dir': '_m0/2', 'linked': 2, 'len': 4236 } ]
>   },
>   { 'mime': 'text/css', 'samples': [
>     { 'url': 'http://testphp.vulnweb.com/AJAX/styles.css', 'dir': '_m1/0', 'linked': 2, 'len': 562 } ]
>   },
>   { 'mime': 'text/html', 'samples': [
>     { 'url': 'http://testphp.vulnweb.com/sfi9876', 'dir': '_m2/0', 'linked': 2, 'len': 168 },
>     { 'url': 'http://testphp.vulnweb.com/showimage.php?file=userinfo.php', 'dir': '_m2/1', 'linked': 2, 'len': 8580 },
>     { 'url': 'http://testphp.vulnweb.com/Flash/', 'dir': '_m2/2', 'linked': 2, 'len': 387 },
>     { 'url': 'http://testphp.vulnweb.com/hpp/', 'dir': '_m2/3', 'linked': 2, 'len': 203 },
>     { 'url': 'http://testphp.vulnweb.com/Mod_Rewrite_Shop/', 'dir': '_m2/4', 'linked': 2, 'len': 975 } ]
>   },
>   { 'mime': 'text/plain', 'samples': [
>     { 'url': 'http://testphp.vulnweb.com/sfi9876.php', 'dir': '_m3/0', 'linked': 2, 'len': 16 },
>     { 'url': 'http://testphp.vulnweb.com/showimage.php', 'dir': '_m3/1', 'linked': 5, 'len': 1 },
>     { 'url': 'http://testphp.vulnweb.com/showimage.php?file=\x27%20%20%20pict.item(0).firstChild.nodeValue%20%20%20\x27', 'dir': '_m3/2', 'linked': 5, 'len': 377 },
>     { 'url': 'http://testphp.vulnweb.com/showimage.php?file=showimage.php', 'dir': '_m3/3', 'linked': 0, 'len': 687 },
>     { 'url': 'http://testphp.vulnweb.com/userinfo.php', 'dir': '_m3/4', 'linked': 5, 'len': 14 } ]
>   },
>   { 'mime': 'text/xml', 'samples': [
>     { 'url': 'http://testphp.vulnweb.com/showimage.php?file=sfish\x3e\x27\x3e\x22\x3e\x3csfish\x3e\x3c/sfish\x3e', 'dir': '_m4/0', 'linked': 5, 'len': 345 } ]
>   }
> ];
> 
> var issue_samples = [
>   { 'severity': 4, 'type': 50107, 'samples': [
>     { 'url': 'http://testphp.vulnweb.com/showimage.php?file=http://www.google.com/humans.txt%23foo%3D', 'extra': 'remote file inclusion', 'sid': '0', 'dir': '_i0/0' } ]
>   },
>   { 'severity': 3, 'type': 40402, 'samples': [
>     { 'url': 'http://testphp.vulnweb.com/showimage.php?file=\x27%20%20%20pict.item(0).firstChild.nodeValue%20%20%20\x27', 'extra': 'PHP warning (text)', 'sid': '22019', 'dir': '_i1/0' } ]
>   },
>   { 'severity': 3, 'type': 40304, 'samples': [
>     { 'url': 'http://testphp.vulnweb.com/showimage.php?file=.htaccess.aspx--\x3e\x22\x3e\x27\x3e\x27\x22\x3csfi000025v869578\x3e', 'extra': '', 'sid': '0', 'dir': '_i2/0' } ]
>   },
>   { 'severity': 3, 'type': 40301, 'samples': [
>     { 'url': 'http://testphp.vulnweb.com/showimage.php?file=.htaccess.aspx--\x3e\x22\x3e\x27\x3e\x27\x22\x3csfi000025v869578\x3e', 'extra': 'text/plain', 'sid': '0', 'dir': '_i3/0' },
>     { 'url': 'http://testphp.vulnweb.com/showimage.php?file=sfish\x3e\x27\x3e\x22\x3e\x3csfish\x3e\x3c/sfish\x3e', 'extra': 'text/xml', 'sid': '0', 'dir': '_i3/1' } ]
>   },
>   { 'severity': 3, 'type': 40101, 'samples': [
>     { 'url': 'http://testphp.vulnweb.com/guestbook.php', 'extra': 'injected \x27\x3csfi...\x3e\x27 tag seen in HTML', 'sid': '0', 'dir': '_i4/0' },
>     { 'url': 'http://testphp.vulnweb.com/guestbook.php', 'extra': 'injected \x27\x3csfi...\x3e\x27 tag seen in HTML', 'sid': '0', 'dir': '_i4/1' },
>     { 'url': 'http://testphp.vulnweb.com/showimage.php?file=.htaccess.aspx--\x3e\x22\x3e\x27\x3e\x27\x22\x3csfi000025v869578\x3e', 'extra': 'injected \x27\x3csfi...\x3e\x27 tag seen in HTML', 'sid': '0', 'dir': '_i4/2' } ]
>   },
>   { 'severity': 2, 'type': 30601, 'samples': [
>     { 'url': 'http://testphp.vulnweb.com/search.php?test=query', 'extra': '', 'sid': '0', 'dir': '_i5/0' },
>     { 'url': 'http://testphp.vulnweb.com/guestbook.php', 'extra': '', 'sid': '0', 'dir': '_i5/1' },
>     { 'url': 'http://testphp.vulnweb.com/search.php?test=query', 'extra': '', 'sid': '0', 'dir': '_i5/2' },
>     { 'url': 'http://testphp.vulnweb.com/showimage.php?file=userinfo.php', 'extra': '', 'sid': '0', 'dir': '_i5/3' },
>     { 'url': 'http://testphp.vulnweb.com/showimage.php?file=userinfo.php', 'extra': '', 'sid': '0', 'dir': '_i5/4' },
>     { 'url': 'http://testphp.vulnweb.com/showimage.php?file=userinfo.php', 'extra': '', 'sid': '0', 'dir': '_i5/5' } ]
>   },
>   { 'severity': 2, 'type': 30501, 'samples': [
>     { 'url': 'http://testphp.vulnweb.com/', 'extra': 'http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=6,0,29,0', 'sid': '0', 'dir': '_i6/0' },
>     { 'url': 'http://testphp.vulnweb.com/guestbook.php', 'extra': 'http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=6,0,29,0', 'sid': '0', 'dir': '_i6/1' },
>     { 'url': 'http://testphp.vulnweb.com/login.php', 'extra': 'http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=6,0,29,0', 'sid': '0', 'dir': '_i6/2' },
>     { 'url': 'http://testphp.vulnweb.com/showimage.php?file=userinfo.php', 'extra': 'http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=6,0,29,0', 'sid': '0', 'dir': '_i6/3' },
>     { 'url': 'http://testphp.vulnweb.com/showimage.php?file=userinfo.php', 'extra': 'http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=6,0,29,0', 'sid': '0', 'dir': '_i6/4' },
>     { 'url': 'http://testphp.vulnweb.com/showimage.php?file=userinfo.php', 'extra': 'http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=6,0,29,0', 'sid': '0', 'dir': '_i6/5' } ]
>   },
>   { 'severity': 0, 'type': 10803, 'samples': [
>     { 'url': 'http://testphp.vulnweb.com/sfi9876', 'extra': '', 'sid': '0', 'dir': '_i7/0' },
>     { 'url': 'http://testphp.vulnweb.com/AJAX/.sf/', 'extra': '', 'sid': '0', 'dir': '_i7/1' },
>     { 'url': 'http://testphp.vulnweb.com/AJAX/index.php/.htaccess.aspx--\x3e\x22\x3e\x27\x3e\x27\x22\x3csfi000033v869578\x3e', 'extra': '', 'sid': '0', 'dir': '_i7/2' },
>     { 'url': 'http://testphp.vulnweb.com/AJAX/styles.css', 'extra': '', 'sid': '0', 'dir': '_i7/3' },
>     { 'url': 'http://testphp.vulnweb.com/Flash/', 'extra': '', 'sid': '0', 'dir': '_i7/4' },
>     { 'url': 'http://testphp.vulnweb.com/hj/', 'extra': '', 'sid': '0', 'dir': '_i7/5' },
>     { 'url': 'http://testphp.vulnweb.com/hj/', 'extra': '', 'sid': '0', 'dir': '_i7/6' },
>     { 'url': 'http://testphp.vulnweb.com/hpp/', 'extra': '', 'sid': '0', 'dir': '_i7/7' },
>     { 'url': 'http://testphp.vulnweb.com/Mod_Rewrite_Shop/', 'extra': '', 'sid': '0', 'dir': '_i7/8' },
>     { 'url': 'http://testphp.vulnweb.com/guestbook.php/.htaccess.aspx--\x3e\x22\x3e\x27\x3e\x27\x22\x3csfi000009v869578\x3e', 'extra': '', 'sid': '0', 'dir': '_i7/9' },
>     { 'url': 'http://testphp.vulnweb.com/showimage.php', 'extra': '', 'sid': '0', 'dir': '_i7/10' },
>     { 'url': 'http://testphp.vulnweb.com/showimage.php?file=\x27%20%20%20pict.item(0).firstChild.nodeValue%20%20%20\x27', 'extra': '', 'sid': '0', 'dir': '_i7/11' },
>     { 'url': 'http://testphp.vulnweb.com/showimage.php?file=showimage.php', 'extra': '', 'sid': '0', 'dir': '_i7/12' },
>     { 'url': 'http://testphp.vulnweb.com/userinfo.php', 'extra': '', 'sid': '0', 'dir': '_i7/13' } ]
>   },
>   { 'severity': 0, 'type': 10801, 'samples': [
>     { 'url': 'http://testphp.vulnweb.com/sfi9876.php', 'extra': 'text/plain', 'sid': '0', 'dir': '_i8/0' },
>     { 'url': 'http://testphp.vulnweb.com/showimage.php', 'extra': 'text/plain', 'sid': '0', 'dir': '_i8/1' },
>     { 'url': 'http://testphp.vulnweb.com/showimage.php?file=\x27%20%20%20pict.item(0).firstChild.nodeValue%20%20%20\x27', 'extra': 'text/plain', 'sid': '0', 'dir': '_i8/2' },
>     { 'url': 'http://testphp.vulnweb.com/showimage.php?file=showimage.php', 'extra': 'text/plain', 'sid': '0', 'dir': '_i8/3' },
>     { 'url': 'http://testphp.vulnweb.com/showimage.php?file=userinfo.php', 'extra': 'text/html', 'sid': '0', 'dir': '_i8/4' },
>     { 'url': 'http://testphp.vulnweb.com/showimage.php?file=userinfo.php', 'extra': 'text/html', 'sid': '0', 'dir': '_i8/5' },
>     { 'url': 'http://testphp.vulnweb.com/showimage.php?file=userinfo.php', 'extra': 'text/html', 'sid': '0', 'dir': '_i8/6' },
>     { 'url': 'http://testphp.vulnweb.com/userinfo.php', 'extra': 'text/plain', 'sid': '0', 'dir': '_i8/7' } ]
>   },
>   { 'severity': 0, 'type': 10602, 'samples': [
>     { 'url': 'http://testphp.vulnweb.com/userinfo.php', 'extra': '', 'sid': '0', 'dir': '_i9/0' } ]
>   },
>   { 'severity': 0, 'type': 10505, 'samples': [
>     { 'url': 'http://testphp.vulnweb.com/guestbook.php', 'extra': 'text', 'sid': '0', 'dir': '_i10/0' },
>     { 'url': 'http://testphp.vulnweb.com/showimage.php?file=userinfo.php', 'extra': 'uaddress', 'sid': '0', 'dir': '_i10/1' } ]
>   },
>   { 'severity': 0, 'type': 10405, 'samples': [
>     { 'url': 'http://testphp.vulnweb.com/showimage.php?file=showimage.php', 'extra': '', 'sid': '0', 'dir': '_i11/0' },
>     { 'url': 'http://testphp.vulnweb.com/showimage.php?file=userinfo.php', 'extra': '', 'sid': '0', 'dir': '_i11/1' } ]
>   },
>   { 'severity': 0, 'type': 10404, 'samples': [
>     { 'url': 'http://testphp.vulnweb.com/Flash/', 'extra': 'Directory listing', 'sid': '0', 'dir': '_i12/0' } ]
>   },
>   { 'severity': 0, 'type': 10205, 'samples': [
>     { 'url': 'http://testphp.vulnweb.com/sfi9876', 'extra': '', 'sid': '0', 'dir': '_i13/0' },
>     { 'url': 'http://testphp.vulnweb.com/sfi9876.php', 'extra': '', 'sid': '0', 'dir': '_i13/1' } ]
>   },
>   { 'severity': 0, 'type': 10204, 'samples': [
>     { 'url': 'http://testphp.vulnweb.com/', 'extra': 'X-Powered-By', 'sid': '0', 'dir': '_i14/0' },
>     { 'url': 'http://testphp.vulnweb.com/Flash/', 'extra': 'X-Powered-By', 'sid': '0', 'dir': '_i14/1' } ]
>   },
>   { 'severity': 0, 'type': 10202, 'samples': [
>     { 'url': 'http://testphp.vulnweb.com/', 'extra': 'nginx/1.4.1', 'sid': '0', 'dir': '_i15/0' } ]
>   },
>   { 'severity': 0, 'type': 10201, 'samples': [
>     { 'url': 'http://testphp.vulnweb.com/logout.php', 'extra': 'login', 'sid': '0', 'dir': '_i16/0' } ]
>   }
> ];
> 
> 
> 
> 
> 
> 
> 
> 
>

**Comment by Ezequieltbh** [comment]
Hola @robertfiz!
Estuve revisando tu issue, al parecer el problema esta en los strings que contienen secuencias de escape como el siguiente:
`http://testphp.vulnweb.com/showimage.php?file=\x27%20%20%20pict.item(0).firstChild.nodeValue%20%20%20\x27'`

Esto rompe el JSON decode que hacemos en el plugin, en la proxima version estaremos actualizando el plugin para que funcione correctamente.
Si lo necesitas ahora, puedes ir al archivo /plugins/repo/skipfish/plugin.py y aplicar este diff:
```
diff --git a/plugins/repo/skipfish/plugin.py b/plugins/repo/skipfish/plugin.py
index 58ba7f50..a446f766 100644
--- a/plugins/repo/skipfish/plugin.py
+++ b/plugins/repo/skipfish/plugin.py
@@ -45,14 +45,15 @@ class SkipfishParser(object):
         self.filepath = skipfish_filepath
 
         tmp = open(skipfish_filepath + "/samples.js", "r").read()
-        issues = json.loads(
-            self.extract_data(
-                tmp,
-                "var issue_samples =", "];",
-                lambda x: x.replace("'", '"'),
-                False,
-                False)
-            [1] + "]")
+        data = self.extract_data(
+                    tmp,
+                    "var issue_samples =", "];",
+                    lambda x: x.replace("'", '"'),
+                    False,
+                    False)
+        # Escape characters not allowed in JSON, repr fix this with double Escape
+        # Also remove \n character and space for have a valid JSON.
+        issues = json.loads(repr(data[1]).replace("\\n"," ").replace("'","") + "]")
 
         tmp = open(skipfish_filepath + "/index.html", "r").read()
         err_msg = json.loads(
```
Gracias por esperar y avisame si este fix funciona!

**Comment by robertfiz** [comment]
Funciona 10 puntos. Gracias.
