### ISSUE TITLE
faraday docker image not starting properly

### ISSUE THREAD

**Issue by rebbdohr** [infobyte/faraday#160]
Hello everybody,

I just downloaded and tried the official faraday docker image and it fails starting 
run_service.sh
at the command
/usr/bin/couchdb > /root/couchdb.log &

Im using macOS 10.12.12 and the official docker client in version 1.12.5
my /root/couchdb.log:
Apache CouchDB 1.5.0 (LogLevel=info) is starting.
Failure to start Mochiweb: eaddrinuse
[error] [<0.105.0>] {error_report,<0.31.0>,
                     {<0.105.0>,crash_report,
                      [[{initial_call,
                         {mochiweb_socket_server,init,['Argument__1']}},
                        {pid,<0.105.0>},
                        {registered_name,[]},
                        {error_info,
                         {exit,eaddrinuse,
                          [{gen_server,init_it,6,
                            [{file,"gen_server.erl"},{line,320}]},
                           {proc_lib,init_p_do_apply,3,
                            [{file,"proc_lib.erl"},{line,239}]}]}},
                        {ancestors,
                         [couch_secondary_services,couch_server_sup,<0.32.0>]},
                        {messages,[]},
                        {links,[<0.93.0>]},
                        {dictionary,[]},
                        {trap_exit,true},
                        {status,running},
                        {heap_size,987},
                        {stack_size,27},
                        {reductions,593}],
                       []]}}
{"init terminating in do_boot",{{badmatch,{error,{bad_return,{{couch_app,start,[normal,["/etc/couchdb/default.ini","/etc/couchdb/local.ini"]]},{'EXIT',{{badmatch,{error,{shutdown,{failed_to_start_child,couch_secondary_services,{shutdown,{failed_to_start_child,httpd,eaddrinuse}}}}}},[{couch_server_sup,start_server,1,[{file,"couch_server_sup.erl"},{line,98}]},{application_master,start_it_old,4,[{file,"application_master.erl"},{line,269}]}]}}}}}},[{couch,start,0,[{file,"couch.erl"},{line,18}]},{init,start_it,1,[]},{init,start_em,1,[]}]}}

**Comment by f-amato** [comment]
Hi @rebbdohr  
If you are using docker on macOS you have to bind the ports and use the docker-machine IP address to connecting to the docker container.

You have to run the following command:
$ docker run -it -p **5984:5984** -p **44:22** infobyte/faraday /root/run.sh

Then you have to get your default IP:
$ docker-machine ip default                                                                                                                                                    192.168.99.100

And then you will get access the Web UI using that IP:
http://192.168.99.100:5984/_ui

If you like to enter in the SSH you have to use ssh root@192.168.99.100 -p 44

Let us know if that help to get fix your connection problem.

You can read more info on:
https://forums.docker.com/t/using-localhost-for-to-access-running-container/3148/3
https://docs.docker.com/machine/reference/ip/

**Comment by rebbdohr** [comment]
thanks, thats the information i needed :) its working like a charm now, thanks for your really fast help!

**Comment by f-amato** [comment]
Thanks! Happy Holidays!
