### ISSUE TITLE
ImportError: cannot import name DependencyWarning

### ISSUE THREAD

**Issue by oladipo** [infobyte/faraday#164]
Error attempting to launch faraday-server.

root@kali:~/faraday-dev# ./faraday-server.py 
Traceback (most recent call last):
  File "./faraday-server.py", line 14, in <module>
    from utils.dependencies import DependencyChecker
  File "/root/faraday-dev/utils/dependencies.py", line 8, in <module>
    import pip
  File "/usr/lib/python2.7/dist-packages/pip/__init__.py", line 21, in <module>
    from pip._vendor.requests.packages.urllib3.exceptions import DependencyWarning
ImportError: cannot import name DependencyWarning
root@kali:~/faraday-dev#

**Comment by Ezequieltbh** [comment]
Hi @oladipo!
You have a problem with pip of python, i recommend upgrade pip and also urllib3 to last version for fix this problem.
If you are using kali linux distro, execute this commands:
```
apt-get install --only-upgrade python-pip
pip2 install -- upgrade urllib3
```

**Comment by f-amato** [comment]
@oladipo do you have any updates on this?
Best

**Comment by nmaxcom** [comment]
Same issue here. Upgrading and urllib3 didn't help.
