### ISSUE TITLE
error en plugins w3af, no carga el report

### ISSUE THREAD

**Issue by robertfiz** [infobyte/faraday#166]
El debug me tira este error:
2017-01-20 09:51:34,175 - faraday - DEBUG - Traceback (most recent call last):
  File "/opt/faraday-dev/plugins/plugin.py", line 343, in run
    self.plugin.processReport(output)
  File "/opt/faraday-dev/plugins/plugin.py", line 117, in processReport
    self.parseOutputString(output)
  File "/root/.faraday/plugins/w3af/plugin.py", line 228, in parseOutputString
    h_id = self.createAndAddHost(ip)
  File "/opt/faraday-dev/plugins/plugin.py", line 149, in createAndAddHost
    name, os=os, parent_id=None)
  File "/opt/faraday-dev/model/common.py", line 106, in createModelObject
    raise Exception("Object name parameter missing. Cannot create object class: %s" % classname)
Exception: Object name parameter missing. Cannot create object class: Host
y no carga el report generado por w3af
Quizá tenga que ver con el tamaño del archivo generado por w3af 
https://mega.nz/#!PoBDAAST!TU3_0RB51vyf99OdFJgcjt1pD8eiJf-_N2rrm6Jta0Y

**Comment by Ezequieltbh** [comment]
Hola @robertfiz!
SyntaxError: not well-formed (invalid token): line 138888, column 524. <?xml version="1.0" encoding="UTF-8"?>

Por lo que veo es un problema con el xml que tienes, puedes probar con otro reporte para ver si funciona sin problemas?

**Comment by robertfiz** [comment]
hola @Ezequieltbh,
el problema quizá está en qué cerré mal w3af porque intenté reproducir el problema y tuve problemas al cerrar la ventana y quizá eso hace que escriba mal el xml. Intentaré arreglarlo mañana, pero me parece que el problema no es faraday sino w3af.
Saludos y gracias.

**Comment by Ezequieltbh** [comment]
Genial! cualquier cosa avisanos!

**Comment by Ezequieltbh** [comment]
Alguna novedad @robertfiz ?
Podemos cerrar este ticket?

**Comment by robertfiz** [comment]
pensé que ya lo habían hecho. De todas formas, todavía no me hice tiempo para probar w3af con faraday porque tuve unos problemitas con mi maquina.

**Comment by robertfiz** [comment]
pero sí, cerralo.

**Comment by Ezequieltbh** [comment]
Ok cualquier novedad nos avisas!
