### ISSUE TITLE
Target Field: Filtering and Sorting IP Addresses

### ISSUE THREAD

**Issue by 0xf165** [infobyte/faraday#168]
Is there a workaround for filtering and sorting IP addresses in the _Target_ field?

Right now, if I look up `10.11.1.22`, it will pull records for all IP addresses matching `10.11.1.22*` (e.g. `10.11.1.221`, `10.11.1.222`). I have also tried sorting the column in attempt to organize the IP addresses but that does not work either.

**Comment by Ezequieltbh** [comment]
Hi @0xf165 !
At this time, there is no solution for this.
We know that issue, and we have plans for strict filtering of IPs.
Regards!

**Comment by 0xf165** [comment]
Thanks @Ezequieltbh !
