### ISSUE TITLE
Gobject Instrospection issue

### ISSUE THREAD

**Issue by peterpt** [infobyte/faraday#169]
Hi , i have already installed all the requirements but i still get this message : 
You are missing Gobject Instrospection. Please install version 3.14 or above (recommended) or 3.12
Packages i already installed to try to fix this issue : 
python-gi_3.12.0-1_amd64.deb
python-gi_3.14.0-1_amd64.deb
gobject-introspection_1.32.1-1_amd64.deb

I had also had issues with couchdb that was not listening at his http port , but i already solve that by downgrading couchdb version to : couchdb_1.2.0-5  and erlang to : 15.b.1-dfsg-4+deb7u1
that solved the server problem of faraday , I am on jessie distro , (just to leave that info here ).

I am out of guesses  to solve this last issue :  Gobject Instrospection missing package that indeed is already installed , but somehow faraday does not see it .
Any solutions to test here ?

**Comment by Ezequieltbh** [comment]
Hi @peterpt!
Can you try this?

Open a terminal, execute...
```python2```

and execute
```import gi```

What is the output?

**Comment by peterpt** [comment]
Hi , my first output was : 
`>>> import gi
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named gi
`
the i installed the module using "pip install gi" 
output disapeared :  
 
`Python 2.7.9 (default, Jan 11 2017, 02:03:56) 
[GCC 4.7.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import gi
>>> 
`
I was looking here and i have already the libgtk-3-dev installed
and i decided to install python-gobject-dev and python-gi-dev libraries .

However , now faraday does not tell me that i dont have a missing module , but gives me an error :  

`Traceback (most recent call last):
  File "./faraday.py", line 570, in <module>
    main()
  File "./faraday.py", line 564, in main
    startFaraday()
  File "./faraday.py", line 298, in startFaraday
    main_app = MainApplication(args)
  File "/opt/faraday/model/application.py", line 106, in __init__
    self.args.gui)
  File "/opt/faraday/gui/gui_app.py", line 19, in create
    from gui.gtk.application import GuiApp
  File "/opt/faraday/gui/gtk/application.py", line 21, in <module>
    gi.require_version('Gtk', '3.0')
AttributeError: 'module' object has no attribute 'require_version'
`

**Comment by Ezequieltbh** [comment]
[https://pypi.python.org/pypi/gi/](url)
That module is not necessary, our gi module is Gobject introspection.
You need uninstall that with 
```pip2 uninstall gi```
Have you tried install faraday with install.sh script or manually?

**Comment by peterpt** [comment]
ok i removed module gi using pip2 and the message returned .
i created a pastebin with the log , and yes , i used the first time "install.sh"

the pastebin : 
http://pastebin.com/udGddkei

**Comment by sebikul** [comment]
Could you please try to execute the following command:

    $ sudo apt-get install --reinstall python-gi

And try running Faraday again. If there is any error running the command above, or running Faraday, please paste it here or upload it to pastebin again.

**Comment by peterpt** [comment]
I already tried that before , but here it is the results .
II believe that this is one of that issues that we will never know it is having this results .

here it is the screencapture :  
https://s27.postimg.org/rm48cae03/faraday.png

**Comment by sebikul** [comment]
Okey, let's see what modules the Python2 interpreter has available. Please execute this command and upload the output to pastebin:

    $ python2 -c "help('modules')"

**Comment by peterpt** [comment]
http://pastebin.com/QR2qcWwJ

**Comment by peterpt** [comment]
I believe that the most possible error for this to be happing is that i may have python environments messed up .
By this i mean , that when i installed python-gi , the installation went to /usr/lib/python2.7 instead /usr/local/lib/python2.7 

I already added in bashrc the paths for python 2.7 in /usr/local/lib and i had the same issue in faraday , and if i leave those variables out from bashrc file then the issue continues .
Resuming : 
When i install by apt some python package , by default it must be installed somehow in /usr/lib/python2.7  instead /usr/local/lib/python2.7  , and this is why module GI does not appear in modules list , but if i install it by pip then it will show up .
I am almost for sure that this could be the issue here , however i will install faraday in my clean laptop without additional python source code installations and see if it works there . 

I am only having this issue in python with faraday , i have here many other python tools working perfectly , however this issue happened with faraday only because the tool is using a module that other tools do not need it , if GI module from python pip installation was enough then this issue were already solved , however the pip GI module must be a lower version where faraday is unable to work it , and this is why i have no errors on missing package when i install it , but i get incompatibility issues probably due to version of GI in pip .

**Comment by peterpt** [comment]
Well , i have tested just now faraday on a clean linux OS without any additional python instalations , and it worked perfectly .
By this , it means that i was right pointing that the cause for this issue is related to my python environment paths on the system be messed up with "usr/lib/python2.7" and "usr/local/lib/python2.7" .
Anyway , i will deal with this issue here locally when i get sometime free .
You can close this issue , if i figure out how to fix it here then i will post here the solution even with the issue closed .

Thanks .

**Comment by sebikul** [comment]
Could you please paste the output of the following command:

     echo $PATH

**Comment by peterpt** [comment]
here it goes : 
http://pastebin.com/EaiYfSEN

however , these variables are the ones that bashrc file have , to get the default $paths from python from the OS the command is other .
comm -23 <(set -o posix; set | sort) <(env | sort)
(thanks to digital ocean :  https://www.digitalocean.com/community/tutorials/how-to-read-and-set-environmental-and-shell-variables-on-a-linux-vps

witch i get this output :  
http://pastebin.com/Qr0JEEnx

**Comment by sebikul** [comment]
The problem is that when you are executing Faraday, your system is using your locally compiled Python interpreter, not the one installed from the repositories along with the dependencies we need. You can see that `/usr/local/bin` has a higher priority than `/usr/bin` in the `$PATH` variable.

The only fix that I can think of is to try to execute Faraday like this (this is, if you followed the installation steps correctly):

    $ /usr/bin/python2 faraday.py

Otherwise, I would recommend you not to manually install software outside the package manager of your distribution, as errors like this can happen.

**Comment by peterpt** [comment]
yup , you are right , it worked that way without issues .
I will create a bash script to run that specific startup of faraday at that way .

Thanks for the  patience on this .

**Comment by sebikul** [comment]
Glad that worked! Remember that executing python2 plainly on a console will launch the interpreter you compiled
