### ISSUE TITLE
HP Webinspect tool support request

### ISSUE THREAD

**Issue by Dodocherty** [infobyte/faraday#172]
I Work in the DOD and we currently use both Webinspect and Burp Pro for assesments. Generating reports and metrics is a pain . I would like to be able to use this product to save time and money. If HP WebInspect was supported there would be a big market.

**Comment by Ezequieltbh** [comment]
Hi @Dodocherty!
Can you send us a example report?
And we can add this to our lists of plugins developments!
Thanks!

**Comment by jbrooks-webinspect** [comment]
@Dodocherty ,
I know this is an old post, we have a plugin for Burp that allows you to share findings between Burp and WebInspect:
https://portswigger.net/bappstore/bapps/details/baaae14d08f7475781989ebf7ca70924

I wonder if you could use the plugin to pull your findings from WebInspect into Burp, and then send them to Faraday. It would be a two step process, but it might work for you (and others thinking about this).

**Comment by llazzaro** [comment]
Hi @Dodocherty ,

We have added te webinspect plugin, you can check the code here: https://github.com/infobyte/faraday/blob/master/plugins/repo/webinspect/plugin.py

Thanks for your feedback!
