### ISSUE TITLE
Edit name of Workspace and add a new admin in a workspace created

### ISSUE THREAD

**Issue by LouRvasquez** [infobyte/faraday#175]
Hi, i got a Workspace created by a user Admin and i wanna change that user for another one Admin, and the application doesnt take the change. In addition, I want to edit the name of a workspace already created.

**Comment by Ezequieltbh** [comment]
Hi @LouRvasquez !
Are you using a community version of Faraday, or a commercial version?

**Comment by LouRvasquez** [comment]
@EzequieltbhIt Would be very useful the option, to not eliminate the reports of requiring some change. We got commercial pro version.

**Comment by Ezequieltbh** [comment]
We added 'Edit of workspaces' in our future features list!
Thanks for report this!
About 'change that user for another one Admin', can you give us more details?
Are you trying change the owner of a workspace or users allowed to access?

**Comment by LouRvasquez** [comment]
Yes, i need change the Owner of a workspace for another, both are Admin', when I make the change, it doesn't apply.

**Comment by llazzaro** [comment]
hi @LouRvasquez ,

You can change the workspace name after v3.0.
For changing the owner you can use python manage..py sql_shell
