### ISSUE TITLE
no funciona --scan en el plugins hping3

### ISSUE THREAD

**Issue by robertofocke** [infobyte/faraday#178]
En mi versión de hping3 funcionaba --scan aunque el codigo estuviera desordenado y un poco caotico.
En la versión del repositorio no funciona --scan. Aunque ahora que lo pienso no estoy seguro si habia hecho el pull request.

**Comment by Ezequieltbh** [comment]
Hola @robertfiz!
Por lo que veo a simple vista, el pull request no incluye soporte a --scan.
Podes revisar que esto sea asi? 
Gracias!

**Comment by robertfiz** [comment]
hola @Ezequieltbh 
jaja, todavía no domino github y no sé bien como responder lo que estas preguntando. O quizá estoy un poco cansado a esta hora.
Te aseguro que --scan funciona en mi codigo porque lo probé.
De todas formas, sabés qué es raro?, que la diferencia entre ambos códigos parece estar en la forma en que obtiene la ip. Solo ahí.

**Comment by WinnaZ** [comment]
Hola @robertofocke,
Pudiste descifrar esto o necesitas una mano?
Saludos!

**Comment by robertofocke** [comment]
@WinnaZ  hace tiempo de esto, jaja. No recuerdo mucho, pero me parece que el problema es la forma en que el codigo obtiene la ip. En mi codigo, que funciona, la paresea de forma levemente diferente. https://github.com/robertofocke/faraday/blob/master/plugins/repo/hping3/plugin.py

**Comment by llazzaro** [comment]
@robertofocke si el problema vuelve a surgir avisanos!
