### ISSUE TITLE
tuve problemas al usar fierce en zonetransfer.me

### ISSUE THREAD

**Issue by robertfiz** [infobyte/faraday#181]
tuve problemas al usar fierce en zonetransfer.me y agregué las siguientes lineas para eliminar caracteres que entorpecian el analisis: 
 
output= output.replace('\\$', '')
        r = re.search(
            "Whoah, it worked - misconfigured DNS server found:([^$]+)\There isn't much point continuing, you have  everything.", output)

**Comment by Ezequieltbh** [comment]
Hola @robertfiz !
Gracias por el pull request, lo estaremos mergeando en esta iteracion!
Por el momento cierro el Issue y mantenemos abierto el pull request hasta que sea mergeado!
Saludos!
