### ISSUE TITLE
sqlmap config

### ISSUE THREAD

**Issue by keithschm** [infobyte/faraday#183]
Remember set your Sqlmap Path Setting!...

How do I do that?  How do I configure any plugin?  I am running the latest Kali...

**Comment by f-amato** [comment]
Hi @keithschm 
Thanks for using Faraday, you can check it out in the following video:
https://www.youtube.com/watch?v=45NgXfXbaCI

Take a look to all our videos on:
https://github.com/infobyte/faraday/wiki/Demos
https://www.youtube.com/playlist?list=PLVnFEI9HluLqEAhjFPFTjEFxTzYXlcrle

Best

**Comment by keithschm** [comment]
DOH!!!

Thank you
