### ISSUE TITLE
Nessus plugin gets SSLexception when to access the nessus in other node

### ISSUE THREAD

**Issue by dongtaofei** [infobyte/faraday#184]
If use the "cscan -p nessus.sh" for the local nessus, and it works fine, but if point to other nessus in other node, it gets exception:
./cscan.py -p nessus.sh
Running: ./scripts/network/nessus.sh ips.txt output/
plugin/nessus.py --target 172.29.225.111 --output output/nessus_1490035063.xml
Login
Unexpected error: <class 'requests.exceptions.SSLError'>

and 
pip install urllib3
Requirement already satisfied: urllib3 in /usr/lib/python2.7/dist-packages

I am using community version.

BR/Taofei

**Comment by WinnaZ** [comment]
Hello dongtaofei,
Your issue is probably caused by a problem with the nessus certificates.

This should fix it:
```
~/d/f/scripts ❯❯❯ git diff cscan/plugin/nessus.py                                                                                                                           master ✱
diff --git a/scripts/cscan/plugin/nessus.py b/scripts/cscan/plugin/nessus.py
index 657eded..63e4d43 100755
--- a/scripts/cscan/plugin/nessus.py
+++ b/scripts/cscan/plugin/nessus.py
@@ -38,14 +38,15 @@ def connect(method, resource, data=None):
 
     data = json.dumps(data)
 
+    requests.packages.urllib3.disable_warnings()
     if method == 'POST':
-        r = requests.post(build_url(resource), data=data, headers=headers, verify=verify)
+        r = requests.post(build_url(resource), data=data, headers=headers, verify=False)
     elif method == 'PUT':
-        r = requests.put(build_url(resource), data=data, headers=headers, verify=verify)
+        r = requests.put(build_url(resource), data=data, headers=headers, verify=False)
     elif method == 'DELETE':
-        r = requests.delete(build_url(resource), data=data, headers=headers, verify=verify)
+        r = requests.delete(build_url(resource), data=data, headers=headers, verify=False)
     else:
-        r = requests.get(build_url(resource), params=data, headers=headers, verify=verify)
+        r = requests.get(build_url(resource), params=data, headers=headers, verify=False)
 
     # Exit if there is an error.
     if r.status_code != 200:
```

In the nessus.py file (cscan/plugin/nessus.py) adds this line to your code: 
requests.packages.urllib3.disable_warnings()

Let us know if you are still having this issue or if anything else comes up,
Cheers!

**Comment by dongtaofei** [comment]
HI,
Thanks!
It fixes the problem, but it does not generate any result, because it cannot get the policy we created. If we use Basic Network Scan from template, it works fine.

BR/Taofei

Running: ./scripts/network/nessus.sh ips.txt output/
plugin/nessus.py --target 172.29.225.88 --output output/nessus_1490196983.xml
Login
Adding new scan.e5fe0d9cb02e01745e914fd996d6bb5f79c6196124157d06
172.29.225.88
plugin/nessus.py --target 172.29.225.111 --output output/nessus_1490196988.xml
Login
Adding new scan.26ea5256e396e1d4e61015103a01d5c8e95ccd1d4e96f948
172.29.225.111

BR/Taofei

**Comment by dongtaofei** [comment]
this should be closed. the fix is confirmed. thanks!

**Comment by dongtaofei** [comment]
confirmed.
