### ISSUE TITLE
HackerOne plugin

### ISSUE THREAD

**Issue by reedloden** [infobyte/faraday#185]
Would be awesome to support pulling reports from a [HackerOne](https://hackerone.com) program.

Can use this Python module to help:
https://github.com/uber-common/h1-python
https://pypi.org/project/h1/

**Comment by WinnaZ** [comment]
Hi reedloden,
Could you tell me more about what you want the HackerOne program to do on Faraday?
Cheers!

**Comment by reedloden** [comment]
Hi @WinnaZ,

From my understanding, Faraday is supposed to be a centralized place for a company's vulnerabilities, pulling in information from lots of different places. A company may also have a HackerOne program where they receive reports from security researchers, so would be good to pull those reports into Faraday to track as well.

Does that help explain the use case?

**Comment by WinnaZ** [comment]
Hello again reedloden,
Yes i get it now, that seems like a very good idea and a very useful upgrade for Faraday.
Sadly until they don’t release an official API there’s no much we can do. Thank you for taking the time and contacting us with new ideas, we really appreciate it.
Thanks!

**Comment by WinnaZ** [comment]
Hello again reedloden,
Yes i get it now, that seems like a very good idea and a very useful upgrade for Faraday.
We’ll learn more about it and discuss it with the team.
Thank you for taking the time and contacting us with new ideas, we really appreciate it.
Thanks!

**Comment by captainkyd** [comment]
Please this...
