### ISSUE TITLE
Feature request: import reports through the web interface

### ISSUE THREAD

**Issue by tsluyter** [infobyte/faraday#189]
Hi guys!

While I'm a keyboard junkie, I prefer to work with the Faraday web interface and my usual terminal. Just something about the way the ZSH handles my history that doesn't jive with me. 

While I'm aware that I can dump reports into a directory to auto-import them, I'd also like an option in the web interface to upload reports for importing. That seems especially useful when working as a team with Faraday being accessed remotely through the web service. 

Kind regards,

Thomas

**Comment by Ezequieltbh** [comment]
Hi @tsluyter
This are in our list of future features to code due to so many users request this!
We don't have any estimation of this, but we are working in changes needed for this.

**Comment by tsluyter** [comment]
Awesome. Thanks for the update!

**Comment by llazzaro** [comment]
Hi @tsluyter ,

we released report web upload on v3.0, you can check the feature here:
https://www.youtube.com/watch?v=9IkFaQCtXkU

You can also upload reports using the faraday api.
