### ISSUE TITLE
Feature request: search hosts by port, service and such

### ISSUE THREAD

**Issue by tsluyter** [infobyte/faraday#190]
Hi guys, 

Sorry to come back again with yet another feature request! I just realized that I couldn't filter the hosts view by the ports and/or services that were open on the box. My current workspace has roughly fifty boxen in there and I want to find the one or two that run a specific port. That's a bit tricky in the current situation, unless I've missed something. 

Thanks in advance and keep up the great work :)

Thomas

**Comment by WinnaZ** [comment]
Hi tsluyter,
We'll check this out and add it to the list,
Thank you for the feedback!

**Comment by WinnaZ** [comment]
Hey tsluyter,
What you are looking for can be solved with our Faraday plugin (fplugin).
You can read more about in out wiki: https://github.com/infobyte/faraday/wiki/Faraday-Plugin
Hope this helps!
Cheers!

**Comment by tsluyter** [comment]
That's awesome, thank you! I'd love this functionality to also make it into the GUI, but for now this'll do.

**Comment by WinnaZ** [comment]
Awesome! 
Glad you like it and find it useful.
Have fun!
