### ISSUE TITLE
Nessus plugin adds plugin output to description

### ISSUE THREAD

**Issue by discoking** [infobyte/faraday#200]
The nessus plugin adds the plugin output to the desc field in couchDB.  This causes the problem in the group_by_name Executive report. The same vulnerabilities show up as unique vulnerabilities. 

Commenting out the lines in the plugin that add the Nessus plugin output fixes this.  I would like this information still available, so it would be nice to add it to another field.

**Comment by Ezequieltbh** [comment]
If you have any change for that in the code, you can do a Pull request and we can merge that!
All contributions are welcome!

**Comment by WinnaZ** [comment]
Hi there,
We have already fix this issue and it will come out on the new version of Faraday.
Cheers!

**Comment by llazzaro** [comment]
Hi @discoking ,
this issue has been fixed in https://github.com/infobyte/faraday/commit/6fd0d2f520f37a69b2a3cfa8534d19355b770e26#diff-9fc2f824cbc35a5cfe0be867bf40aa1f
The output was moved to data field to avoid duplicates.
