### ISSUE TITLE
Feature Request: View Unconfirmed Vulnerabilities

### ISSUE THREAD

**Issue by discoking** [infobyte/faraday#202]
I would like a way to view only the unconfirmed vulnerabilities

**Comment by Ezequieltbh** [comment]
Hi @discoking!
We have this feature in our roadmap, but we dont have any date for that.
We contact you when this be released.
Thanks!

**Comment by llazzaro** [comment]
Hi @discoking,
This feature will be released on the next version v3.2.

**Comment by llazzaro** [comment]
We just released v3.2 with this feature!
