### ISSUE TITLE
Bug Report: When selecting and updating a large amount of vulnerabilities not all get updated

### ISSUE THREAD

**Issue by discoking** [infobyte/faraday#203]
I have a workspace with over 12,000 medium vulnerabilities.  I want to select them all and confirm them.  I use the "severity:med" in status report, select all, then edit, then "Confirm/Change to false positive:" to confirm

Then wait a very long time, when it finally comes back usually less than half the medium vulns are set to confirmed.

**Comment by Ezequieltbh** [comment]
Thanks for report that!
We know that issue and should be fixed ina few releases.
Sorry about that.
