### ISSUE TITLE
ImportError: No module named _collections

### ISSUE THREAD

**Issue by TopKeingt** [infobyte/faraday#205]
./faraday-server.py 
Traceback (most recent call last):
  File "./faraday-server.py", line 5, in <module>
    import argparse
  File "/usr/local/lib/python2.7/argparse.py", line 85, in <module>
    import collections as _collections
  File "/usr/local/lib/python2.7/collections.py", line 8, in <module>
    from _collections import deque, defaultdict
ImportError: No module named _collections

**Comment by llazzaro** [comment]
Which operating system are you using? 

_collections is part of the  standard library. Could you try to open a python shell and import collections?
Try the following:

`import _collections
`

If you get the ImportError on the python shell it seems you need to verify your python installation.

**Comment by WinnaZ** [comment]
Hello TopKeingt,
Are you still having this issue?
Did you get a chance to look at what llazzaro suggested?
Cheers!
