### ISSUE TITLE
Conflict resolving - multiple issues

### ISSUE THREAD

**Issue by Tompazi** [infobyte/faraday#213]
While using faraday with the MetasploitOn plugin enabled I ran into several issues.

First of all, if there is a conflict resulting by the MetasploitOn plugin the conflict gets re-added every few seconds (every time the MetasploitOn plugin syncs), quickly adding up to an absurd amount of conflicts. The same conflict should not appear more than once.

Secondly, some conflicts should not be conflicts at all in my opinion, for example:
Unknown values changing to known values: OS: Unknown - OS: Linux
Upper and lower case mac addresses:
a1:b2:c3:d4:e5:f6 - A1:B2:C3:D4:E5:F6

Finally, this is a feature request, there should be an option to keep ALL left/right conflict elements, for when you know the source of the new information is more accurate. Also there should be a way to auto-resolve conflicts e.g. "Always keep right"

Version: {"Faraday Server":"Running","Version":"2.5.0"}
OS: Linux kali 4.9.0-kali4-686 #1 SMP Debian 4.9.30-1kali1 (2017-06-06) i686 GNU/Linux
Currently can't upgrade faraday regularly due to #212

**Comment by WinnaZ** [comment]
About the first conflict if you can't make it work properly a workaround for that would be to use Faraday in cli mode:
https://github.com/infobyte/faraday/wiki/Usage#cli
try that and see how it goes.
and about the other issue, for the time being we do not have an automatic way of dealing with conflicts, but
it's in our road map to improve that functionality.
Is there anything else i can help you with?

**Comment by WinnaZ** [comment]
Hi there @Tompazi,
could you take a lot at this? 
did it work? is there anything else we can do for you?
have a nice day
