### ISSUE TITLE
Faraday Server didn't start

### ISSUE THREAD

**Issue by oorozcoo** [infobyte/faraday#214]
Hello there.
I was installing the Faraday Demo VM, but when the faraday server starts it ask for install some dependencies. If I select (yes) the installation finished well and then I see "Dependencies Installed. Please launch Faraday Server Again". If I launch the server again I have the same error. If I select (no) the server didn't start.

![captura de pantalla 2017-08-22 a la s 13 04 33](https://user-images.githubusercontent.com/3171663/29580135-97f9afaa-873a-11e7-986b-6d71519a1831.png)

**Comment by WinnaZ** [comment]
Hi,
Try running Faraday with the argument --nodeps.
python2 faraday-server.py --nodeps 
Let us know who this goes!

**Comment by oorozcoo** [comment]
Thank you for the answare.
I ran the application with --nodeps but now I got another error.

![captura de pantalla 2017-08-22 a la s 15 09 17](https://user-images.githubusercontent.com/3171663/29585250-1566f7fc-874c-11e7-9fb3-089f123a68fd.png)

**Comment by f-amato** [comment]
Hi @oorozcoo 
Sorry that you have problems.
Could you please run
```
cd /root/infobyte/faraday/
pip --install -r server_requirements.txt
python2 faraday-server.pyc --stop
/etc/init.d/couchdb stop && /etc/init.d/couchdb start
```

Then you can just run the "Faraday GUI" or "Faraday Gui Web" icon, 
We are uploading a new VM with this fix if you like to download and active later.

**Comment by oorozcoo** [comment]
Hello @f-amato.
Thanks for your reply.

The pip command is wrong.
Here are the new command:
pip install -r requirements_server.txt

Then when I try to run the "Faraday GUI" I got an error for the CouchDB.
Error - CouchDB is not running at http://localhost:5984. Check faraday-server's configuration and make sure CouchDB is running.

I checked that the couchdb is running and checked the server.ini file 

![captura de pantalla 2017-08-22 a la s 16 28 09](https://user-images.githubusercontent.com/3171663/29588457-3512ee84-8757-11e7-9409-42c80e65acf8.png)

Regards

**Comment by f-amato** [comment]
Could you please send me the netstat -nap output
Did you run the stop and start?

**Comment by oorozcoo** [comment]
Hi.

This is the output:

root@kalirolling ~ # ❯❯❯ service couchdb stop && service couchdb start
root@kalirolling ~ # ❯❯❯ netstat -putona
Active Internet connections (servers and established)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name     Timer
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      20654/sshd           off (0.00/0/0)
tcp        0    176 192.168.32.140:22       192.168.32.1:62037      ESTABLISHED 20756/sshd: root@pt  on (0.01/0/0)
tcp6       0      0 :::22                   :::*                    LISTEN      20654/sshd           off (0.00/0/0)
udp        0      0 0.0.0.0:68              0.0.0.0:*                           7405/dhclient        off (0.00/0/0)
udp        0      0 0.0.0.0:68              0.0.0.0:*                           1827/dhclient        off (0.00/0/0)
udp        0      0 192.168.32.140:123      0.0.0.0:*                           789/ntpd             off (0.00/0/0)
udp        0      0 127.0.0.1:123           0.0.0.0:*                           789/ntpd             off (0.00/0/0)
udp        0      0 0.0.0.0:123             0.0.0.0:*                           789/ntpd             off (0.00/0/0)
udp6       0      0 fe80::20c:29ff:fe69:123 :::*                                789/ntpd             off (0.00/0/0)
udp6       0      0 ::1:123                 :::*                                789/ntpd             off (0.00/0/0)
udp6       0      0 :::123                  :::*                                789/ntpd             off (0.00/0/0)
root@kalirolling ~ # ❯❯❯

Regards

**Comment by f-amato** [comment]
Hi @oorozcoo 
We just upload a new VM, could you please re-download and active it again? 
It seems that it is not working the couchdb in your instance, if you still want to try to fix it, you could send us the /var/log/couchdb/couch.log
Best

**Comment by oorozcoo** [comment]
Hi @f-amato 
Dont worry, I could download the new VM, do you send me the new password? Or the last password works? 

Here is the log.

[couch.log.zip](https://github.com/infobyte/faraday/files/1243568/couch.log.zip)

Thank you.
Regards

**Comment by f-amato** [comment]
Excellent,
You have to use the same password for the license.
Best

**Comment by oorozcoo** [comment]
@Francisco.
I have this link
https://www.faradaysec.com/users/down/FaradayApp_Kali_2.0_64.ova
Is that ok?

Regards

**Comment by f-amato** [comment]
Yes, the same

**Comment by oorozcoo** [comment]
Thanks,
I will download the VM and try to run Faraday.
If  I have another issue, I will report you.

Thanks a lot.
Regards
