### ISSUE TITLE
api error

### ISSUE THREAD

**Issue by vulnz** [infobyte/faraday#216]
~/faraday-dev# ./faraday-terminal.zsh 
[!] Using default configuration 127.0.0.1:9977
>>> WELCOME TO FARADAY
[+] Current Workspace: untitled
[-] API: Warning API unreachable
[+] Faraday path not set, but server found. Aliasing fplugin

API does not start on Ubuntu 16.0 started from docker.
NOT docker image, from docker.

Because of this issue GUI does not work

**Comment by WinnaZ** [comment]
Hi there,
I will need more information to troubleshoot this:
1) In which OS are you running Faraday? 
2) What's the exact command you were using and what's the full Error message?
3)What steps did you follow that got you here?
Have a nice day

**Comment by vulnz** [comment]
1) Ubuntu 16.0 from here ---> https://github.com/fcwu/docker-ubuntu-vnc-desktop I start it in docker

2) ./faraday.py - does not work , says no api and closes faraday
3) All steps. git clone, apt-get update. pip install all requeirements for server, extas and client and after I start coachdb and start server.

**Comment by vulnz** [comment]
any news ;)

**Comment by WinnaZ** [comment]
we think we were able to replicate this issue,
If you are trying to run the faraday-terminal.zsh you need to first be running the client with ./faraday.py --gui=no-gui to have the client running and also all of it's apis.
One question tho, that error message you sent on the first comment did you saw it on the terminal or inside the GTK?
If what you wanted was simply to have Faraday running inside docker here you have a wiki for it:
https://github.com/infobyte/faraday/wiki/Installation-Docker

**Comment by WinnaZ** [comment]
hey vulnz,
Were you able to look at this?
Is the problem solved or are you still having this issue?

**Comment by vulnz** [comment]
will check it and let you know.
thank you
