### ISSUE TITLE
display render issue /_ui/#/status/ws/(some works place)

### ISSUE THREAD

**Issue by stumblesthedrunk** [infobyte/faraday#219]
Version: Faraday 2.6.2 (community )
Server: Ubuntu 16.04
Affected Client browsers: Firefox 45.8.0, 57.0b1(dev ed), Chrome 61.0.31.63.91, 
Non-affected Client browser: IE 11.0.9600.18793

Issue Status report for vulnerability in web browsers other than IE do not render data when formated into rows properly. 

See example ..  https://ibin.co/3bAR1NMWlm2M.png

**Comment by WinnaZ** [comment]
Hi there Stumbles,
I'm really sorry for the late reply, things were crazy here with us hosting the EkoParty.
That behaviour is really strange.
I think you're missing the dependency mime-types.
In which OS are you running Faraday?

Btw, the official support page for clients is Assembla, and you'll get much quicker responses if you submit your issue there. Once more i apologise for the delay.

Have a great Weekend!

**Comment by WinnaZ** [comment]
hi there,
Could you solve this?
Is there anything else i can help you with?

**Comment by stumblesthedrunk** [comment]
Not right now, we're getting the AWS environment stood up and working with a AWS  Linux AMI and Docker for couchdb. If I have any issues I will seek out Sebastian if I need help. Have a wonderful day.DOn Oct 19, 2017 16:23, WinnaZ <notifications@github.com> wrote:hi there,
Could you solve this?
Is there anything else i can help you with?

**Comment by WinnaZ** [comment]
Alright you too!
I'll close this ticket for no then.
