### ISSUE TITLE
REST  API is not REST API

### ISSUE THREAD

**Issue by fredbroker** [infobyte/faraday#221]
I`m reading documentations for faraday  RESTful GTK API Service and it is is not REST architecture. It`s children's crafts. For example:

`POST /model/edit/vulns` - verb in url!
`DELETE /model/del/vulns ` - verb in url!
`PUT /model/host` - right version
I advise you to read http://www.restapitutorial.com/.

Besides you api is broken, same methods is not work. You dos`t verified input data and this call errors in farday. If you do not have resources for fix it, please write about this in documentations. RESTful too loud a name for this.

p.s. you "rest api" have 2 GET, 1 POST, 1 Delete, and 6! PUT methods. Do not you think this is strange?

**Comment by WinnaZ** [comment]
Hi there fredbroker,
Faraday community's editions is an open source program for Collaborative Pentesting,
If there's something you don't like or find "children's crafts" you are more that welcomed to do a pull request :) .
Faraday grows everyday with the help of the Faraday Team and all the users that give us feedback or help with plugins and pull requests.
Cheers! Have a great week!
