### ISSUE TITLE
Faraday-server as a service?

### ISSUE THREAD

**Issue by RicForesight** [infobyte/faraday#222]
Hello all,

I feel this is a bit of a numpty question, but here it goes, I am running Faraday on a remote testing server. I start the server with the command `/usr/share/python-faraday/faraday-server.py --start` in it starts as a  daemon as expected and when I close the session the daemon dies (again as expected).  However, I would like the server to continue running when I log-off the remote server. So I created a script-service in /etc/init.d with the following (got this from the net, while searching for a solution):

`#! /bin/sh`
`# /etc/init.d/faraday-server`
`#`
``
`case "$1" in`

`  start)`
`    /usr/share/python-faraday/faraday-server.py --start`
`    ;;`
`  stop)`
`    /usr/share/python-faraday/faraday-server.py --stop`
`    ;;`
`  *)`
`    echo "Usage: /etc/init.d/faraday-server {start|stop}"`
`    exit 1`
`    ;;`
`esac`
``
`exit 0`

However,  when I run the `service faraday-server start` I get:
`Failed to start faraday-server.service: Unit faraday-server.service not found.`

Before anyone mentions the obvious:

'systemctl start faraday-server.py` I get:
`Failed to start faraday-server.py.service: Unit faraday-server.py.service not found.`

Any help would be appreciated.

**Comment by llazzaro** [comment]
Hello,
The following steps are for Kali Linux 2017.2, if you are using another distro please let us know.
To configure faraday at boot you need to go the systemd way (Debian 8 started using systemd).
The following steps are to give you an idea on how to configure the deamon on boot, you will need to change the contents of the configuration files. I recommend to follow the documentation link about systemd before doing any change.
Fist step is to create the following files:

```
touch /etc/systemd/system/name.service
chmod 664 /etc/systemd/system/name.service
```

Then you have save a config in name.server like this one:

```
[Unit]
Description=service_description
After=network.target

[Service]
ExecStart=path_to_executable
Type=forking
PIDFile=path_to_pidfile

[Install]
WantedBy=default.target
```
Last steps are:

```
systemctl daemon-reload
systemctl start name.service
```

Please remeber that kali has [restrictions to start network applications on boot](https://docs.kali.org/policy/kali-linux-network-service-policies)

Check the [full documentation of systemd here](https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/7/html/system_administrators_guide/sect-managing_services_with_systemd-unit_files)

**Comment by WinnaZ** [comment]
Hi there RicForesight,
Could you try what Leo suggested?
Cheers!

**Comment by RicForesight** [comment]
thank you!
