### ISSUE TITLE
SSL Faraday

### ISSUE THREAD

**Issue by RicForesight** [infobyte/faraday#223]
Hello 

I have been trying to set up the Faraday server over HTTPS and I am having some issue. I have followed the instructions on https://github.com/infobyte/faraday/wiki/SSL and have been able to access the web interface via https; happy there. However; when I try to connect the client to the address I get the error:

"Could not connect to Faraday Server".
I am starting the client with the command 

python-faraday --cert /path/tocert

Any help would be appreciated.

**Comment by WinnaZ** [comment]
Here you have a detailed guide on how to connect the server and the client running them on different machines: https://github.com/infobyte/faraday/wiki/Using-Faraday's-Client-and-Server-from-different-machines.
i suspect you are having some configuration problems
Try that and let me know how it goes.
Cheers!

**Comment by WinnaZ** [comment]
Could you solve this?
Is there anything else i can help you with?
Have a nice day!
