### ISSUE TITLE
Issue following OSX Instructions

### ISSUE THREAD

**Issue by csk** [infobyte/faraday#224]
I am trying to run faraday on OSX (macOS Sierra 10.12.6).

Followed the video tutorial step-by-step which is referenced in the OSX Installation wiki but could not get it to work :( .

CouchDB version : Apache CouchDB 1.6.1

The couchdb throws following logs:

`[debug] [<0.299.0>] 'GET' /_api/info {1,1} from "127.0.0.1"
Headers: [{'Accept',"*/*"},
          {'Accept-Encoding',"gzip, deflate"},
          {'Connection',"keep-alive"},
          {'Host',"127.0.0.1:5984"},
          {'User-Agent',"python-requests/2.18.4"}]
[debug] [<0.299.0>] OAuth Params: []
[debug] [<0.299.0>] Minor error in HTTP request: {error,
                                                  illegal_database_name,
                                                  "_api"}
[debug] [<0.299.0>] Stacktrace: [{couch_httpd_db,do_db_req,2,
                                     [{file,"couch_httpd_db.erl"},{line,239}]},
                                 {couch_httpd,handle_request_int,5,
                                     [{file,"couch_httpd.erl"},{line,318}]},
                                 {mochiweb_http,headers,5,
                                     [{file,"mochiweb_http.erl"},{line,94}]},
                                 {proc_lib,init_p_do_apply,3,
                                     [{file,"proc_lib.erl"},{line,247}]}]
[info] [<0.299.0>] 127.0.0.1 - - GET /_api/info 400
[debug] [<0.299.0>] httpd 400 error response:
 {"error":"illegal_database_name","reason":"Name: '_api'. Only lowercase characters (a-z), digits (0-9), and any of the characters _, $, (, ), +, -, and / are allowed. Must begin with a letter."}`

Faraday (`./faraday.py -d`) output:

`2017-10-16 01:02:23,197 - faraday - DEBUG - Starting application...
2017-10-16 01:02:23,198 - faraday - DEBUG - Setting up remote API's...
2017-10-16 01:02:23,200 - faraday - DEBUG - starting XMLRPCServer with api_conn_info = ('localhost', 9876)
2017-10-16 01:02:23,202 - faraday - INFO - XMLRPC API server configured on ('localhost', 9876)
2017-10-16 01:02:23,203 - faraday - DEBUG - Starting model controller daemon...
2017-10-16 01:02:23,203 - faraday - DEBUG - starting xmlrpc api server...
2017-10-16 01:02:23,225 - faraday - INFO - REST API server configured on ('localhost', 9977)
2017-10-16 01:02:23,229 - faraday - DEBUG - Faraday ready...
2017-10-16 01:02:23,311 - faraday.Server-GTK IO - WARNING - Couldn't get a valid response from the server when requesting to URL http://127.0.0.1:5984/_api/ws and function <function get at 0x108a490c8>.`

Seems faraday is using a db name starting with '_' (underscore) which is not a valid couchdb db name. 
 **{"error":"illegal_database_name","reason":"Name: '_api'. Only lowercase characters (a-z), digits (0-9), and any of the characters _, $, (, ), +, -, and / are allowed. Must begin with a letter."}**

**Comment by WinnaZ** [comment]
Hi there, 
It seems you are having some configuration problems.
Faraday's Server api is supposed to be located on the port 5985 on the 5984 you have couchdb running.
Go to your user.xml file and check the couch_uri adress it should be 127.0.0.1:5985
Let us know how it goes.

**Comment by csk** [comment]
Thanks for your reply. The settings are ok, if the port is not the usual one is because i already configured either in couchd or in faraday settings (don't remember :/ ).

I do know the connection is being established correctly because couchdb logs.

**Comment by WinnaZ** [comment]
can you show me your user.xml file?
Is the server running without any problems?

**Comment by csk** [comment]
Yes I can! 

Only to be sure we are talking about the same video I followed, i am talking abou this one: https://www.youtube.com/watch?v=F44RnB3Ru24

My config file is here `~/.faraday/config/user.xml`
Here it is https://pastebin.com/5FqgdUrX

And I also prepared an asciinema to show the step-by-step I am following and the logs I get:
https://asciinema.org/a/3UbfUQZubXRwXeOxml7R4gXU9

**Comment by WinnaZ** [comment]
![image](https://user-images.githubusercontent.com/24845440/31737439-e28d34be-b41d-11e7-8426-8ffbaccec847.png)
This is how the couch_uri line has to be like,
I just tested it myself and yes the server works anyway but the client won't.
Try changing the port to 5985 see what happens.
Keep us updated!

**Comment by WinnaZ** [comment]
Does that mean is worked? :D

**Comment by csk** [comment]
Hi WinnaZ! You were right! Changing the couchdb uri to port 5985 solved the problem. When running with GTK GUI python crashes often but with `./faraday-terminal.py` it works great!

I am still a bit consufed 🙃 ... couchdb is listening on 5984 but we have to point faraday anyways to 5985 ...

**Comment by csk** [comment]
Ok. I think I know understand. faraday-server listens on 5985 and couchdb listens in 5984.

The field name in the configuration file is confusing. Thx for your support!

**Comment by WinnaZ** [comment]
yes, the user.xml file takes care of the client, the client is not supposed to be connected to to couchdb by itself. It is connected to Faraday server (on the 5985) and then the server will connect itself to couch (5984).
Let us know if there's anything else we can do for you.
As it is solved i'll close the ticket now, if you have any other doubts or issues you can re-open it or create a new one.
cheers have a great week.
