### ISSUE TITLE
Bug Report: removeBySeverity.py does not work

### ISSUE THREAD

**Issue by sgabe** [infobyte/faraday#227]
Though the `removeBySeverity.py` helper script seems to execute just fine, it actually does not seem to work. After deleting several vulnerabilities with the script, I noticed that the affected vulnerabilities are still displayed on the web interface and deleting again from the UI results in an HTTP 500 response.

I was able to make it work by connecting to the Faraday server on `http://127.0.0.1:5985` instead of the CouchDB on `http://127.0.0.1:5984` and modifying the request URL to `/_api/ws/<db>/doc/<id>?rev=<rev>`. This is basically the same like deleting through the web UI and this works as expected.

**Comment by WinnaZ** [comment]
Hi there,
Follow this steps:
1)Stop Faraday’s Server but keep couchdb running
2)Run the script removeBySeverity.py that will delete the Vulns from couchdb.
3)Now you need to delete Sqlite database, run:
     rm faraday/server/workspaces/WORSPACE_NAME.db
4)Run faraday’s server again and you will see that all the selected by severity vulns have been deleted.
Let us know how it goes!

**Comment by WinnaZ** [comment]
Hi there,
Could you try my suggestion?
Could you solve it or are you still having this issue?
