### ISSUE TITLE
¿es posible ejecutar faraday desde subsistema linux en windows 10?

### ISSUE THREAD

**Issue by robertofocke** [infobyte/faraday#230]
La verdad que tendria que haberlo probado yo, pero tengo windows 10 en 32 bits y no trabaja con subsistema linux. La pregunta es esa que aparece en el titulo, ¿alguien probó ejecutar faraday en windows 10 desde la shell del subsistema linux.? Si todavia nadie lo probó seguramanete lo haga yo la semana que viene cuando actualice el sistema operativo en mi otra pc. Pero queria saber si alguien mas lo hizo para ver si funciona.

**Comment by WinnaZ** [comment]
hola robertofocke,
No sabemos de ningún caso por el momento, Faraday no tiene soporte official para Windows.
Si lo probas avísanos cómo va!
Saludos

**Comment by robertofocke** [comment]
ya lo probé https://medium.com/@robertfock/ejecutar-faraday-dentro-del-subsistema-linux-de-windows-10-3ac2f9f4b84f . Nada bien porque no windows todavía no ofrece soporte para AF_PACKET https://wpdev.uservoice.com/forums/266908-command-prompt-console-bash-on-ubuntu-on-windo/suggestions/17817685-support-af-packet-address-family-tcpdump-wireshar 
El problema no es faraday, el problema es windows que no deja trabajar con algunas  herramientas como nmap o algunos sniffer....todavia

**Comment by WinnaZ** [comment]
Si eso es lo que calculamos, imagino también que debe ser imposible hacer funcionar CouchDB.
Gracias por mantenernos al tanto.
Si hay algo más que pueda hacer por ustedes no duden en avisarnos!
Cierro ese ticket en particular, cualquier cosa sentite libre de re-abrirlo o crear uno nuevo.
