### ISSUE TITLE
[Bug] SQLmap plugin error TypeError: cannot concatenate 'str' and 'int' objects

### ISSUE THREAD

**Issue by dmknght** [infobyte/faraday#233]
`faraday/plugins/repo/sqlmap/plugin.py line 627, in processCommandString
    self.url = self.protocol + "://" + self.hostname + ":" + self.port + self.path`

Fix:
`self.url = self.protocol + "://" + str(self.hostname) + ":" + str(self.port) + self.path`

**Comment by WinnaZ** [comment]
hi there dmknght,
I'll take a look at this and get back to you.

**Comment by WinnaZ** [comment]
This seems perfectly reasonable, if you wanna do a pull request with this we'll be more than happy to merge it.

**Comment by dmknght** [comment]
Thanks for reply. I created a new pull request here https://github.com/infobyte/faraday/pull/239

**Comment by WinnaZ** [comment]
great!!!
We'll take a look at it and probably merge it in out next release!
