### ISSUE TITLE
Execute Report ends with status "Error" when certain vulns are included

### ISSUE THREAD

**Issue by yellowdepot** [infobyte/faraday#235]
An execute report ends with status "Error" (instead of "Created") when certain vulns are confirmed and therefore included. I couldn't find any helpful errormessage or a logfile containing more details. Please give me some hint's in how to debug this as "Error" and is not really verbose.

Faraday 2.7.0 in kali (fully patched yesterday)

**Comment by WinnaZ** [comment]
Hi there @yellowdepot,
Thanks for reporting this,
It's a bug, we'll fix it and be realising a hot fix one of these days.
If you are a client i recommend you to contact us through our Assembla page, where we have a better response time and priority for clients!

**Comment by Ezequieltbh** [comment]
Hi! Version 2.7.1 included a fix for this bug. Contact with commertial support via Assembla or email if you have any doubt about this problem! Thanks!

**Comment by WinnaZ** [comment]
Hi there @yellowdepot,
Could you take a look at the new Version of Faraday with this bug fixed?
Was the problem solved? is there anything else we can help you with?
Hope to hear from you soon!
Cheers

**Comment by WinnaZ** [comment]
I'm closing this ticket now, the bug has been fixed,
if you need something else regarding this issue you can re-open it or create a new one.
have a nice week :)
