### ISSUE TITLE
Nycto-Host

### ISSUE THREAD

**Issue by nycto-hackerone** [infobyte/faraday#236]
Do you think this would be worthy to be placed in to Faraday ?
[https://github.com/nycto-hackerone/Nycto-Host](url)

**Comment by WinnaZ** [comment]
hi there @nycto-hackerone 
That link is broken.

**Comment by nycto-hackerone** [comment]
Thanks for the feed back @WinnaZ 
 I will look into making a plugin for it and another tool i have written, I am still new to all this .. maybe i can get something done

**Comment by WinnaZ** [comment]
that's great!
We look forward to it!

**Comment by nycto-hackerone** [comment]
hey @WinnaZ , you would'nt know of any one willing to help make the plugin i need would you?

**Comment by WinnaZ** [comment]
sadly no, 
but i wish you the best of lucks!
