### ISSUE TITLE
Please add a setup.py to allow proper system-wide installation

### ISSUE THREAD

**Issue by rhertzog** [infobyte/faraday#24]
It would be nice if faraday had a proper setup.py that would install the application on the system. So that you get a /usr/bin/faraday and so that python modules get installed somewhere (either in a public python directory or in a private directory) and other data get installed in /usr/share/faraday/.

Thank you for considering it. This makes it easier to create a good package of faraday for Kali Linux.

**Comment by rhertzog** [comment]
setup.py should also take care of compiling what needs to be compiled, like shell/core/_helpers.so.

**Comment by necrose99** [comment]
[tox](https://github.com/tox-dev/tox) also a plus for deps. or virtual env  ,  also can have client and server targets...  also makes less tied to Debian/Ubuntu

**Comment by llazzaro** [comment]
Hi,
We started to do some changes on the faraday code to support python packaging.

**Comment by llazzaro** [comment]
This change has been scheduled for v3.7. We will try to make this change!

**Comment by llazzaro** [comment]
@rhertzog we finally added the setup.py!
