### ISSUE TITLE
Error connecting to CouchDB

### ISSUE THREAD

**Issue by H0nus** [infobyte/faraday#243]
Please search the [Wiki](https://github.com/infobyte/faraday/wiki) for a solution before posting a ticket. Use the <strong>“New Support Request”</strong> button to the right of the screen to submit a ticket for technical support.

## Issue Type
Can't log in in couch db even with correct credentials;
setup went well, i have couchdb running as standalone service and it works;
but if i try with curl (with credentials) or faraday, they get 401 error;
On browser i don't get it;
i even tried as root and not;
[requirements_freeze.txt](https://github.com/infobyte/faraday/files/1588986/requirements_freeze.txt)

## Faraday version
Faraday v2.7.1

## Steps to reproduce

I don't know, setup went well, but i can't login anyway.

## Expected results
To log in into CouchDB stand alone server

### Debugging tracebacks (current results)

Try to reproduce the bug with the server and/or gtk client in debug mode and check the logs for the ERROR string.
2017-12-27 12:48:10,128 - faraday-server.server.couchdb - DEBUG - Traceback (most recent call last):
  File "/usr/share/faraday-dev/server/couchdb.py", line 180, in push_reports
    workspace = couchdb_server.get_or_create_db('reports')
  File "/usr/share/faraday-dev/server/couchdb.py", line 47, in get_or_create_db
    return self.__server.get_or_create_db(ws_name)
  File "/usr/local/lib/python2.7/dist-packages/couchdbkit/client.py", line 146, in create_db
    return self.get_db(dbname, create=True, **params)
  File "/usr/local/lib/python2.7/dist-packages/couchdbkit/client.py", line 131, in get_db
    return Database(self._db_uri(dbname), server=self, **params)
  File "/usr/local/lib/python2.7/dist-packages/couchdbkit/client.py", line 265, in __init__
    self.server.res.head('/%s/' % self.dbname)
  File "/usr/local/lib/python2.7/dist-packages/restkit/resource.py", line 122, in head
    params_dict=params_dict, **params)
  File "/usr/local/lib/python2.7/dist-packages/couchdbkit/resource.py", line 111, in request
    payload=payload, headers=headers, **params)
  File "/usr/local/lib/python2.7/dist-packages/restkit/resource.py", line 204, in request
    response=resp)
Unauthorized: {'msg': '', 'status_int': 401, 'response': <couchdbkit.resource.CouchDBResponse object at 0x7f185aafbb10>}

### Configuration files
Just changed the file in faraday-dev/server/default.ini 
[couchdb]
host=127.0.0.1
port=5984
ssl_port=6984
user=admin
password=admin
protocol=http

### OS
Distributor ID:	Debian
Description:	Debian GNU/Linux testing (buster)
Release:	testing
Codename:	buster

**Comment by Ezequieltbh** [comment]
Hi!

Are you using the community version of Faraday, right? You don't have Faraday Profesional or Corporate.

If that is correct and you are using Couchdb with credentials (Not admin party), Faraday is no builded for support this use case, community version only support admin party in Couchdb.

You can read more about that Couchdb situation here:
http://guide.couchdb.org/draft/security.html#party

Let me know if you have any doubt!
Regards

**Comment by H0nus** [comment]
Oh, ok! thanks! Yes, I have community one.
i'll take a look!
Btw great tool! Awesome!

**Comment by H0nus** [comment]
UPDATE:
actually, removing admins row in couch db gave me back the admin party mode, so it's fixed, thanks too much! i'm going to close the issue!

**Comment by Ezequieltbh** [comment]
Excelent!
Thanks for use Faraday!
Have a great week!
