### ISSUE TITLE
When running WPScan automatically on Faraday Terminal, WPScan plugin doesn't work

### ISSUE THREAD

**Issue by AmandaBSobrinho** [infobyte/faraday#245]
Please search the [Wiki](https://github.com/infobyte/faraday/wiki) for a solution before posting a ticket. Use the <strong>“New Support Request”</strong> button to the right of the screen to submit a ticket for technical support.

## Issue Type
 - Bug Report

## Faraday version

Faraday v2.7.1

## Component Name

/usr/share/python-faraday/faraday-terminal.zsh
/usr/share/python-faraday/plugins/repo/wpscan

## Steps to reproduce

I want to run WPScan and integrate its results to Faraday automatically, but since I can't copy its reports to the report folder (WPScan's plugin is of Console type), I tried to run it automatically on Faraday Terminal. 

The best way I found to do so was to put the WPScan command (wpscan --url https://example.com -f json -o outfile) in the .zshrc file (~/.faraday/zsh/.zshrc). 

However, when I run the Faraday Terminal command (/usr/share/python-faraday/faraday-terminal.zsh), WPScan starts executing (as I predicted) but the plugin responsible to pass the results of the scan to Faraday doesn't execute. On the other hand, if I start Faraday Terminal and run the WPScan command manually, the plugin works perfectly.

I should also make clear that, on both occasions, Faraday API was already up and running (I know that the plugin doesn't work if the Faraday API isn't running).  

## Expected results

When running the WPScan command automatically on Faraday Terminal, it was expected that the plugin worked and sent the scan results to the Faraday API.

## Proposal

Faraday could also have a Report Plugin for WPScan, cause I was able to create a XML file from the JSON that WPScan v3 already produces. It would be very practical if I could just copy that XML file to the reports folder and put its results on Faraday.

### Configuration files

Added line:
wpscan --url https://example.com -f json -o outfile

on file:

~/.faraday/zsh/.zshrc

### OS

DISTRIB_ID=Kali
DISTRIB_RELEASE=kali-rolling
DISTRIB_CODENAME=kali-rolling
DISTRIB_DESCRIPTION="Kali GNU/Linux Rolling"

**Comment by WinnaZ** [comment]
Thank you for the feedback on this issue!
We'll take a look at it and see what's going on.
About the Proposal to have a plugin where you can make xml imports, sounds really good, we don't have the resources at the moment as we have our hands full with the migration.
But we always encourage our users to make pull requests with new plugins and any other interesting features.

**Comment by llazzaro** [comment]
Hi!
We released a fix on v3.7.0 for wpscan plugin.
Feel free to reopen this issue.
remember to update wpscan also.
