### ISSUE TITLE
Faraday at Kali not running properly [Faraday GTK console clear bug]

### ISSUE THREAD

**Issue by ThOhT** [infobyte/faraday#250]
I'm trying to use Faraday Community v.2.7.1 at Kali (fully updated), using couchdb v.1.7.1. 

When I started it for the first time, it asked me to create a workspace and I added 2 hosts (one with hostname and other with just IP). It seems ok!

But in GTK-Gui, the console is clear. I run some commands and do nothing. And if a I click CTRL+C, it shows "kali%" and I can run any command. Is it normal?

By the way, I can run nmap 127.0.0.1 but Faraday doesn't import the result automatically. And If I import manually, it doesn't recon the results. What's wrong?

$ cat /etc/lsb-release 
DISTRIB_ID=Kali
DISTRIB_RELEASE=kali-rolling
DISTRIB_CODENAME=kali-rolling
DISTRIB_DESCRIPTION="Kali GNU/Linux Rolling"

**Comment by Ezequieltbh** [comment]
Hi ThOhT!

You are using a more updated version of Tornado, the 5.0 version.
Faraday don't have, right now, compatibility with that version.
You need do an downgrade, run:
pip2 uninstall tornado
and later...
pip2 install tornado==4.5.2

Now all should be ok!

We are working in a fix for the next version!

**Comment by WinnaZ** [comment]
hey @ThOhT any updates on this?
Cheers!

**Comment by Ezequieltbh** [comment]
Hey @ThOhT.
Try the new version of Faraday, now all should be ok!
It have compatibility with tornado version 4 and version 5.
Regards!

**Comment by ThOhT** [comment]
I just updated / upgraded my Kali and tried to use Faraday and the problem persist.

I tried to uninstall tornado 5, but I got an error. Then I just installed the version 4 and now Faraday is working.

@Ezequieltbh are you sure about the compatibility? Did you update Faraday at Kali's repository?

**Comment by llazzaro** [comment]
@ThOhT the version with the fix is 2.7.2. You can check your version over the faraday logo (WebUI).
Kali's repository does not contain the 2.7.2 version since it was released yesterday on github.

**Comment by ThOhT** [comment]
@llazzaro do you have a forecast when it will be available on Kali?

**Comment by WinnaZ** [comment]
it is already, clone the project again.

**Comment by WinnaZ** [comment]
hotfix is already out for kali.
Have a great rest of the week.
