### ISSUE TITLE
SSLCheck XML import failed

### ISSUE THREAD

**Issue by jstangle** [infobyte/faraday#253]
Hi guys,
I am using your script for SSL check, but I am not able to import the exported XML file by that script.

## Issue Type
 - Bug Re port
 - Missing feature

## Faraday version
Faraday v2.7.2

## Component Name
I guess
https://github.com/infobyte/faraday/blob/faraday/managers/reports_managers.py
https://github.com/infobyte/faraday/blob/master/plugins/repo/sslcheck/plugin.py

## Steps to reproduce
I have a XML file "sslcheck_output_test.xml":
`<sslcheck><scan host="192.168.1.32" hostname="" port="443"><renegotiation>yes</renegotiation><sha256WithRSAEncryption>signature secure</sha256WithRSAEncryption><TLSv1.2>yes</TLSv1.2><TLSv1.1>.....full source below.....</CAMELLIA128-SHA><forward_secrecy>yes</forward_secrecy><heartbeat>no</heartbeat><crime>no</crime></scan></sslcheck>`

I am calling:
./faraday.py --cli --workspace workspace --nodeps --report sslcheck_output_test.xml

Getting error:
2018-05-12 19:08:29,304 - faraday.ReportProcessor - ERROR - Plugin not found: automatic and manual try!

## Expected results
I checked plugin directory and sslcheck is present, but it's not working. Is there any chance to fix it? I also looked into a source and I didn't find a file name parser for it. Please, could you provide me any advice how go through without ZSH? Thank you very much!

### Debugging tracebacks (current results)
2018-05-12 19:08:29,304 - faraday.ReportProcessor - ERROR - Plugin not found: automatic and manual try!

## Environment information
Docker container.

### Configuration files
Using default configuration files.

### Reports/Extra data
File: sslcheck_output_test.xml

`<sslcheck><scan host="192.168.1.33" hostname="" port="443"><renegotiation>yes</renegotiation><sha256WithRSAEncryption>signature secure</sha256WithRSAEncryption><TLSv1.2>yes</TLSv1.2><TLSv1.1>yes</TLSv1.1><TLSv1>yes</TLSv1><ECDHE-RSA-AES256-GCM-SHA384>secure</ECDHE-RSA-AES256-GCM-SHA384><ECDHE-RSA-AES256-SHA384>secure</ECDHE-RSA-AES256-SHA384><ECDHE-RSA-AES256-SHA>secure</ECDHE-RSA-AES256-SHA><DHE-RSA-AES256-GCM-SHA384>secure</DHE-RSA-AES256-GCM-SHA384><DHE-RSA-AES256-SHA256>secure</DHE-RSA-AES256-SHA256><DHE-RSA-AES256-SHA>secure</DHE-RSA-AES256-SHA><DHE-RSA-CAMELLIA256-SHA>secure</DHE-RSA-CAMELLIA256-SHA><AES256-GCM-SHA384>secure</AES256-GCM-SHA384><AES256-SHA256>secure</AES256-SHA256><AES256-SHA>secure</AES256-SHA><CAMELLIA256-SHA>secure</CAMELLIA256-SHA><ECDHE-RSA-DES-CBC3-SHA>insecure</ECDHE-RSA-DES-CBC3-SHA><EDH-RSA-DES-CBC3-SHA>insecure</EDH-RSA-DES-CBC3-SHA><DES-CBC3-SHA>insecure</DES-CBC3-SHA><ECDHE-RSA-AES128-GCM-SHA256>secure</ECDHE-RSA-AES128-GCM-SHA256><ECDHE-RSA-AES128-SHA256>secure</ECDHE-RSA-AES128-SHA256><ECDHE-RSA-AES128-SHA>secure</ECDHE-RSA-AES128-SHA><DHE-RSA-AES128-GCM-SHA256>secure</DHE-RSA-AES128-GCM-SHA256><DHE-RSA-AES128-SHA256>secure</DHE-RSA-AES128-SHA256><DHE-RSA-AES128-SHA>secure</DHE-RSA-AES128-SHA><DHE-RSA-CAMELLIA128-SHA>secure</DHE-RSA-CAMELLIA128-SHA><AES128-GCM-SHA256>secure</AES128-GCM-SHA256><AES128-SHA256>secure</AES128-SHA256><AES128-SHA>secure</AES128-SHA><CAMELLIA128-SHA>secure</CAMELLIA128-SHA><forward_secrecy>yes</forward_secrecy><heartbeat>no</heartbeat><crime>no</crime></scan></sslcheck>`

### OS
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=14.04
DISTRIB_CODENAME=trusty
DISTRIB_DESCRIPTION="Ubuntu 14.04.2 LTS"

**Comment by montive** [comment]
Hi there! 

That plugin hans't been modified in over 2 years, it would make sense if it werent't working. Do you have any SSL report that you can provide us? That way we could test the plugin and get a solution to this issue.

Cheers

**Comment by dkogue** [comment]
Is this bug resolved? I am having the same challenge. we will appreciate if you can provide update on this .

Thanks in advance.

**Comment by WinnaZ** [comment]
The issue is that the plugin does not have automatic identification!
see the error: 2018-05-12 19:08:29,304 - faraday.ReportProcessor - ERROR - Plugin not found: automatic and manual try!
So,  either open GTK and import manually or change the name to XOXOXOX_Sslcheck.xml 
Cheers!

**Comment by dkogue** [comment]
Thanks for your feedback.
changing the output file name as indicated does not work. see error below.
Welcome to Faraday!

 no element found: line 1, column 0
[ ERROR ]- 2018-08-13 23:18:40,777 - faraday.ReportProcessor - Plugin not found: automatic and manual try!
[ INFO ]- 2018-08-13 23:18:40,777 - faraday.ReportManager - Plugin not detected. Moving /root/.faraday/report/sslcheck/Sslcheck.xml to unprocessed
[ ERROR ]- 2018-08-13 23:18:40,778 - faraday.ReportParser - Not an xml file.
 no element found: line 1, column 0
[ ERROR ]- 2018-08-13 23:18:40,779 - faraday.ReportProcessor - Plugin not found: automatic and manual try!
[ INFO ]- 2018-08-13 23:18:40,779 - faraday.ReportManager - Plugin not detected. Moving /root/.faraday/report/sslcheck/scanoutput_Sslcheck.xml to unprocessed

**Comment by WinnaZ** [comment]
mmmm it's case sensitive, i would have to check the code to see that word it is exactly.
Maybe SSLcheck or SLLCheck.
I'll give you an answer shortly.

**Comment by WinnaZ** [comment]
![screenshot_20180814_141135](https://user-images.githubusercontent.com/24845440/44106829-0e2b88ba-9fcc-11e8-83a7-da35bcfc3c0a.png)
