### ISSUE TITLE
Faraday client in docker container: ports 9977 and 9876 are inaccessible

### ISSUE THREAD

**Issue by bananaCat123** [infobyte/faraday#254]
## Issue Type
 - Issue

## Faraday version

v.2.7.1

## Component Name

faraday-client

## Steps to reproduce

Hello!
I've pulled the Faraday docker image from your repository and run the container exposing three ports:
docker run -it -p 127.0.0.1:5985:5985 -p 127.0.0.1:9876:9876 -p 127.0.0.1:9977:9977 --name faraday-new infobyte/faraday /root/run.sh

## Expected results

I need the APIs to do the things, so I checked if I can access the ports with my browser. Port 5985 is accessible (http://127.0.0.1:5985/_ui/), but 9876 and  9977 are not. Could you please tell me, what am I doing wrong?

### Debugging tracebacks (current results)

I receive no error messages, just three warnings:
2018-05-18 11:26:04,377 - faraday.PluginManager - WARNING - No module named bs4
2018-05-18 11:26:04,382 - faraday.PluginManager - WARNING - No module named lxml
2018-05-18 11:26:04,388 - faraday.PluginManager - WARNING - No module named lxml

### Configuration files

The config is default

**Comment by montive** [comment]
Hi there.

Ports 9876 and 9977 are served with ./faraday.py --gui=no-gui. You can run ./faraday.py from docker or from you local machine (recommended). Once Faraday.cli starts, it will open these ports.

If you want to run Faraday's client in docker, run the following command: 

`docker run -it -p 127.0.0.1:5985:5985 -p 127.0.0.1:9876:9876 -p 127.0.0.1:9977:9977 --name faraday-new infobyte/faraday /root/faraday/faraday.py --gui=no-gui`

If your problem persist, you can send us the output of this command: **sudo netstat -onaput**, on the affected ports.

Cheers.

**Comment by bananaCat123** [comment]
Thank you for quick response!
I've tried the recommended
docker run -it -p 127.0.0.1:5985:5985 -p 127.0.0.1:9876:9876 -p 127.0.0.1:9977:9977 --name faraday-new infobyte/faraday /root/faraday/faraday.py --gui=no-gui
and received the following error messages:
2018-05-21 06:49:14,094 - faraday.GuiApp - ERROR - Your last workspace workspace is not accessible, check configuration.
2018-05-21 06:49:14,095 - faraday.GuiApp - ERROR - You may try and go to ~/.faraday/config/user.xml to set a valid couch_uri and last_workspace
2018-05-21 06:49:14,095 - faraday.GuiApp - ERROR - Couldn't get a valid response from the server when requesting to URL http://127.0.0.1:5985/_api/ws and function <function get at 0x7f7fb13d1488>

I also have exactly the same issue on my host machine when launching faraday client.
Am I taking it right? According to the run.sh script content, faraday client had already been launched with " --gui=no-gui"  option by the command I used before:
#!/bin/bash
###
## Faraday Penetration Test IDE
## Copyright (C) 2013  Infobyte LLC (http://www.infobytesec.com/)
## See the file 'doc/LICENSE' for the license information
###
cd /root/faraday
/root/run_service.sh &

status="False";
while [[ ! "$status" =~ "Running" ]]
 do
   status=$(curl http://localhost:5985/_api/info 2> /dev/null)
   sleep 1;
done

./faraday.py --gui=no-gui --update

Now I have faraday in a docker container ran with the previously used 
docker run -it -p 127.0.0.1:5985:5985 -p 127.0.0.1:9876:9876 -p 127.0.0.1:9977:9977 --name faraday-new infobyte/faraday /root/run.sh 
and sudo netstat -onaput gives me the following output on the ports in question:
tcp        0      0 127.0.0.1:9977          0.0.0.0:*               LISTEN      13414/docker-proxy off (0.00/0/0)
tcp        0      0 127.0.0.1:5985          0.0.0.0:*               LISTEN      13436/docker-proxy off (0.00/0/0)
tcp        0      0 127.0.0.1:9876          0.0.0.0:*               LISTEN      13424/docker-proxy off (0.00/0/0)

**Comment by bananaCat123** [comment]
There is an issue I haven't noticed before. When starting with 
docker run -it -p 127.0.0.1:5985:5985 -p 127.0.0.1:9876:9876 -p 127.0.0.1:9977:9977 --name faraday-new infobyte/faraday /root/run.sh
I get the following warning on faraday-serever:
2018-05-21 07:49:16,319 - faraday-server.server.couchdb - WARNING - Reports database couldn't be uploaded. You need to be an admin to do it

**Comment by WinnaZ** [comment]
You don't run everything all together all te time!
First you run: `sudo docker run -t -i infobyte/faraday /root/run.sh`
wich will create the docker for faraday.
you can do a `docker ps ` to check if that contair of docker of up and running, If it is then you already have Faraday's server running and to run the client you only need to do a `./faraday.py -gui=no-gui --update`,

Now if you wanna conect to the web UI you just need to get the ip where that docker is running so, 
`docker inspect $(docker ps -lq) | grep \"IPAddress` will get you the ip, and to see the server you only need to go to  http://DOCKERS_IP:5985/_ui on your broser.
The docker run is only used once when creating the container.

**Comment by bananaCat123** [comment]
Thank you for your advice! 
Unfortunately, the problem persists. When I do the way you described, I can access the port 5985 with http://DOCKERS_IP:5985/_ui. I tried to access the ports 9977 and 9876 using the same approach (http://DOCKERS_IP:9977 and so on) but they remain inaccessible

**Comment by WinnaZ** [comment]
Hi there again,
Cause you're not supposed to get there! haha
The web UI works using the server. If what you are trying to do is access the client.
Try running `python2 faraday.py` once the server is running.
 Cheers!

**Comment by WinnaZ** [comment]
Hi there bananaCat123 ,
I'm looking into this issue again, trying to reproduce your steps.

I misunderstood what you were trying to do. If i understand correctly now, you're trying to access those 2 ports from outside of docker.
Tho you must know that in order to access those apis you must have the client running inside that docker image.
You can do that like this:
# ssh -X root@DOCKER_IP
# cd faraday/
# ./faraday.py

More documentation about your apis here: https://github.com/infobyte/faraday/wiki/APIs

**Comment by WinnaZ** [comment]
@bananaCat123 Did you have any luck?
