### ISSUE TITLE
[Question] Is this project over?

### ISSUE THREAD

**Issue by vwhissell** [infobyte/faraday#255]
No new features, bug fixes or nothing for so long now?

Should this project considered inactive?

**Comment by fedek** [comment]
Nope! It's Alive and kicking, we have been working hard for the next major release, stay tuned! <3

**Comment by Ezequieltbh** [comment]
Hi @vwhissell !
Checkout the new BETA version of Faraday 3.0 in our dev branch!
A lot of changes!

**Comment by sh4r3m4n** [comment]
Hi! If you are interested in an overview of what changed in the beta checkout https://blog.infobytesec.com/2018/06/faraday-beta-v30-released.html

**Comment by WinnaZ** [comment]
I'll close this ticket now then :D
Enjoy Faraday V3 BETA!!!
