### ISSUE TITLE
Your last workspace untitled is not accessible, check configuration

### ISSUE THREAD

**Issue by xiaoyan1985** [infobyte/faraday#256]
I met some errors, as I created pod in openshift with your source.
The error message as followings:

faraday.GuiApp - ERROR - Your last workspace untitled is not accessible, check configuration.
faraday.GuiApp - ERROR - You may try and go to ~/.faraday/config/user.xml to set a valid couch_uri and last_workspace
faraday.GuiApp - ERROR - HTTPConnectionPool(host='127.0.0.1', port=5985): Max retries exceeded with url: /_api/ws (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fcebd204a50>: Failed to establish a new connection: [Errno 111] Connection refused',))

Is there any way to resolve these? Thanks.

**Comment by xiaoyan1985** [comment]
Thanks for your reply.
I can not have a file named user.xml.
I add following contents in default.xml

<last_workspace>faraday</last_workspace>
<couch_uri>http://localhost:5985</couch_uri>

is this right? or how to set workspace ?
Thanks.

**Comment by montive** [comment]
Hi there. 

User.xml is created at the moment when you run Faraday (even if it doesn't work). 
Beware that this file it's in faraday's configuration folder **~/.faraday**. Not the same as **/faraday** where you run Faraday Server and Faraday GTK.

I'll be waiting for your answer.
Cheers!

**Comment by montive** [comment]
In case you can't find user.xml file, let's try running the following command:

`python faraday.py --gui=no-gui --login`

Type in your credentials and you should be able to work in your workspace.

**Comment by xiaoyan1985** [comment]
Thanks.
I met a new error, as I using your method.
The error message as followings:

usage: faraday.py [-h] [-n HOST] [-px PORT_XMLRPC] [-pr PORT_REST] [--profile]
                  [--profile-output PROFILE_OUTPUT]
                  [--profile-depth PROFILE_DEPTH] [--disable-excepthook]
                  [--dev-mode] [--ignore-deps] [--update] [--cert CERT_PATH]
                  [--gui GUI] [--cli] [-w WORKSPACE] [-r FILENAME] [-d]
                  [--nodeps] [-v]
faraday.py: error: unrecognized arguments: --login

Is there any way to avoid it?

**Comment by WinnaZ** [comment]
Just this: `python faraday.py --gui=no-gui `
should work.
Let us know how it goes.

**Comment by xiaoyan1985** [comment]
Hi, thanks for your reply.
Then error did not disappear, as I using your way.

**Comment by llazzaro** [comment]
@xiaoyan1985 try to add username and password on couch_uri.
Example: http://username:password@yourhost:port

**Comment by xiaoyan1985** [comment]
Thanks for your mind.
We resolved the problem with other way.
Thanks again.
