### ISSUE TITLE
metasploit online service plugin repeatedly causes the same conflicts over and over again.

### ISSUE THREAD

**Issue by eadthem** [infobyte/faraday#258]
I setup and enabled the "metasploit online service plugin" today.

The install of metasploit and Faraday have been well used and never connected before.

When I did this many new conflicts appeared, and then they continued to be added every minute when the addon was run in the background,  quickly to growing to 1500 conflicts before i disabled the addon.   

I quickly noticed that there are only about 20 different conflicts, and they repeat over and over again.

I think this plugin is lacking or unable to track the state between the 2 programs and it keeps re importing the same data every run.

FYI I am running faraday 2.7.2 via Kali linux (Was the PWK 2017 version but has gotten some updates)

**Comment by WinnaZ** [comment]
Hi there,
Let me give it a try and get back to you.
Thank you so much for your feedback!
Have a great weekend.

**Comment by llazzaro** [comment]
On the next version v3.5 we made some changes to improve metasploit online plugin. stay tuned!
