### ISSUE TITLE
Lynis report imports assigned incorrect names

### ISSUE THREAD

**Issue by daniejstriata** [infobyte/faraday#259]
## Issue Type
 - Bug Report

## Faraday version

Faraday v2.7.2

## Component Name

If you know where the problem lays indicate it: 
Lynis report import

## Steps to reproduce
1. Import Lynis report
2. View the names of the vulnerabilities and see that many of them are assigned to NETW-3032 
![image](https://user-images.githubusercontent.com/13314239/42207179-91227d94-7ea9-11e8-90c7-c7090a944fdc.png)

## Expected results

The Lynis reports are using the correct / unique name for each finding.

Provide information on your operating system. Example: 

$ cat /etc/lsb-release 
DISTRIB_ID=Kali
DISTRIB_RELEASE=kali-rolling
DISTRIB_CODENAME=kali-rolling
DISTRIB_DESCRIPTION="Kali GNU/Linux Rolling"

**Comment by daniejstriata** [comment]
Regrettably I can't always replicate this issue.

**Comment by llazzaro** [comment]
Hello @daniejstriata,
can you tell us which Lynis version are you using?

Thanks

**Comment by daniejstriata** [comment]
It was 2.6.5. I looked at the Lynis reports generated and the names were correct in there. It seems that with import Faraday got stuck on using the wrong name for all Lynis imports I did. When I deleted the current hosts and imported again it was correct but as this happened a while again I thought to mention it.

**Comment by montive** [comment]
Hi @daniejstriata  

Thanks for mentioned this issue, we will be taking a look at it. Let us know if you got that issue again or any other.

Cheers

**Comment by daniejstriata** [comment]
I found this issue in Faraday 3 as well. I'll share s screenshot that will highlight how many items are all linked to the same ID but looking into the Lynis report they are not.

![image](https://user-images.githubusercontent.com/13314239/44522994-a23f3c00-a6d8-11e8-9341-d9ca698e6d26.png)
The Items listed above do not correspond with KRNL-6000 in the report.

warning[]=AUTH-9216|grpck binary found errors in one or more group files|-|-|
warning[]=FIRE-4512|iptables module(s) loaded, but no rules active|-|-|
warning[]=MACF-6234|Current SELinux mode is different from config file (current: permissive, config file: disabled)|-|-|

**Comment by WinnaZ** [comment]
Right now we do not have that kind of functionality inside of Faraday.
We have been discussing the possibility to somehow merge or group vulns that are similar or the same.
We are looking and how and if it's possible to implement that into faraday in the future but as of right now that functionality does not exist.

**Comment by daniejstriata** [comment]
No problem. I suspect that it is the Lynis reports that caused this issue and that it won't happen that frequently in any case. It seems to happen only when I import older versions of Lynis reports. I'll update when I see this again.

**Comment by WinnaZ** [comment]
Okay great!

**Comment by llazzaro** [comment]
Closing 
If you have this bug again please open this issue.
We think that this could be caused by older Lynis report.
