### ISSUE TITLE
First time user/not user 

### ISSUE THREAD

**Issue by n0x00** [infobyte/faraday#26]
Hey guys, 

I'm trying to install on a pretty vanilla copy of Kali

I'm having no success  - is there a preferred OS that the installer 100% works on ? I'd like to see what the tool is capable off (havign enquired about the professional version to no avail, I thougth I'd look at the community edition) 

any help would be grateful 

John

./faraday.py 
Traceback (most recent call last):
  File "/root/.local/lib/python2.7/site-packages/restkit/__init__.py", line 13, in <module>
    from restkit.client import Client, MAX_FOLLOW_REDIRECTS
  File "/root/.local/lib/python2.7/site-packages/restkit/client.py", line 24, in <module>
    pip install http-parser""")
ImportError: http-parser isn't installed or out of data.

        pip install http-parser
Missing module couchdbkit. Do you wish to install it? [Y/n] y
Requirement already satisfied (use --upgrade to upgrade): couchdbkit==0.6.5 in /root/.local/lib/python2.7/site-packages
Requirement already satisfied (use --upgrade to upgrade): restkit>=4.2.2 in /root/.local/lib/python2.7/site-packages (from couchdbkit==0.6.5)
Downloading/unpacking http-parser>=0.8.3 (from restkit>=4.2.2->couchdbkit==0.6.5)
  Downloading http-parser-0.8.3.tar.gz (83Kb): 83Kb downloaded
  Running setup.py egg_info for package http-parser
    
Requirement already satisfied (use --upgrade to upgrade): socketpool>=0.5.3 in /usr/local/lib/python2.7/dist-packages/socketpool-0.5.3-py2.7.egg (from restkit>=4.2.2->couchdbkit==0.6.5)
Installing collected packages: http-parser
  Running setup.py install for http-parser
    building 'http_parser.parser' extension
    gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -Iparser -I/usr/include/python2.7 -c http_parser/http_parser.c -o build/temp.linux-x86_64-2.7/http_parser/http_parser.o
    gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -Iparser -I/usr/include/python2.7 -c http_parser/parser.c -o build/temp.linux-x86_64-2.7/http_parser/parser.o
    http_parser/parser.c:16:20: fatal error: Python.h: No such file or directory
    compilation terminated.
    error: command 'gcc' failed with exit status 1
    Complete output from command /usr/bin/python2.7 -c "import setuptools;__file__='/root/Desktop/faraday-master/build/http-parser/setup.py';exec(compile(open(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --single-version-externally-managed --record /tmp/pip-y8_9qj-record/install-record.txt --user:
    running install

running build

running build_py

creating build

creating build/lib.linux-x86_64-2.7

creating build/lib.linux-x86_64-2.7/http_parser

copying http_parser/pyparser.py -> build/lib.linux-x86_64-2.7/http_parser

copying http_parser/__init__.py -> build/lib.linux-x86_64-2.7/http_parser

copying http_parser/util.py -> build/lib.linux-x86_64-2.7/http_parser

copying http_parser/http.py -> build/lib.linux-x86_64-2.7/http_parser

copying http_parser/reader.py -> build/lib.linux-x86_64-2.7/http_parser

copying http_parser/_socketio.py -> build/lib.linux-x86_64-2.7/http_parser

running build_ext

building 'http_parser.parser' extension

creating build/temp.linux-x86_64-2.7

creating build/temp.linux-x86_64-2.7/http_parser

gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -Iparser -I/usr/include/python2.7 -c http_parser/http_parser.c -o build/temp.linux-x86_64-2.7/http_parser/http_parser.o

gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -Iparser -I/usr/include/python2.7 -c http_parser/parser.c -o build/temp.linux-x86_64-2.7/http_parser/parser.o

http_parser/parser.c:16:20: fatal error: Python.h: No such file or directory

compilation terminated.

error: command 'gcc' failed with exit status 1

----------------------------------------
Command /usr/bin/python2.7 -c "import setuptools;__file__='/root/Desktop/faraday-master/build/http-parser/setup.py';exec(compile(open(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --single-version-externally-managed --record /tmp/pip-y8_9qj-record/install-record.txt --user failed with error code 1 in /root/Desktop/faraday-master/build/http-parser
Storing complete log in /root/.pip/pip.log

**Comment by f-amato** [comment]
Hi @n0x00
Before start faraday you have to run ./install.sh 
Take a look at:
https://github.com/infobyte/faraday/wiki/Installation

Let me know if this works for you.
Best

**Comment by n0x00** [comment]
Yep! Did that ☺️

**Comment by f-amato** [comment]
Could you provide a log of the ./install.sh ?
From I saw it's a ./faraday.py log

**Comment by n0x00** [comment]
Sure, I'll get that to you tomorrow :) thanks for quick response

**Comment by f-amato** [comment]
Thanks you for the trying it!
Best
