### ISSUE TITLE
[branch=dev] Postgres SQL connection

### ISSUE THREAD

**Issue by vwhissell** [infobyte/faraday#260]
Getting this when starting the faraday-server.py script:

`Could not connect to postgresql.`

How do we specify the postgres username/password?

Thanks :)

**Comment by vwhissell** [comment]
Also:

```
cat /root/.faraday/config/server.ini
[faraday_server]
port = 5985
bind_address = localhost
websocket_port = 9000
secret_key = [SECRET]

[ssl]
port = 6985
certificate =
keyfile =

[couchdb]
host = localhost
port = 5984
ssl_port = 6984
user =
password =
protocol = http

[storage]
path = /root/.faraday/storage
```

**Comment by llazzaro** [comment]
Hi @vwhissell ,
You need to execute python manage.py initdb to configure the database.
Check here the [install steps for faraday V3.0 BETA](https://github.com/infobyte/faraday/wiki/Install-steps-for-Faraday-v3.0-BETA)

**Comment by vwhissell** [comment]
Thank you. It worked :)

**Comment by WinnaZ** [comment]
Great!
