### ISSUE TITLE
Creating a workspace without the faraday interface, but CouchDB and Faraday-Server Running?

### ISSUE THREAD

**Issue by vwhissell** [infobyte/faraday#261]
Hello, here's the use case:

The Couch server is running: (I changed the port to test stuff)
```
 netstat -antp | grep 5985
tcp        0      0 192.168.0.199:5985     0.0.0.0:*
```
Also faraday-server.py
```
 netstat -antp | grep 5984
tcp        0      0 192.168.0.199:5984     0.0.0.0:*               LISTEN      2657/python2.7
```

SSH X-Forward is not working, so I use:
`./faraday.py --gui=no-gui`
I get:
```
ERROR - Your last workspace untitled is not accessible, check configuration.
2018-07-13 10:30:02,384 - faraday.GuiApp - ERROR - You may try and go to ~/.faraday/config/user.xml to set a valid couch_uri and last_workspace
2018-07-13 10:30:02,384 - faraday.GuiApp - ERROR - Couldn't get a valid response from the server when requesting to URL http://192.168.0.199:5985/_api/ws and function <function get at 0x7fdbab26b2a8>.
2018-07-13 10:30:02,385 - faraday - INFO - Closing Faraday...
```
On Firefox, in URL: http://192.168.0.199:5985/_api/ws
`{"error":"illegal_database_name","reason":"Name: '_api'. Only lowercase characters (a-z), digits (0-9), and any of the characters _, $, (, ), +, -, and / are allowed. Must begin with a letter."}`

Can I use ./faraday-terminal.zsh to create a workspace and start importing results?
How can I create a workspace without the Faraday ui?
The Web UI is stuck to: This workspace does not exist. Select one of the list
But, the list is empty.
I tried to create a folder under ~/.faraday/report , but that does not create a workspace ;)

Thank you!

**Comment by montive** [comment]
Hi there!

Change the name of the workspace you are working at to a valid one. You can change it in the tag **<last_workspace>** of the file _~/.faraday/config/user.xml_ 

Then, restart the Faraday server and run the following command:

`./faraday.py --gui=no-gui --login`

Type in your credentials and you should be able to start working.

Let us know how it goes.
Cheers.

**Comment by vwhissell** [comment]
It's a fresh use. There are no workspace yet created.

**Comment by vwhissell** [comment]
cat ~/.faraday/config/server.ini
```
[faraday_server]
port = 5984
bind_address = 192.168.0.199
websocket_port = 9000
secret_key = 2AIWkC01kQ4LbIblsYQJBVixv

[ssl]
port = 6985
certificate =
keyfile =

[couchdb]
host = 192.168.0.199
port = 5985
ssl_port = 6985
user =
password =
protocol = http

[storage]
path = /root/.faraday/storage

[database]
connection_string = postgresql+psycopg2://faraday_postgresql:zLJov2LleReWbpIbCJEEkZtlm@localhost/faraday

```
Oh, that database section! I tried the "dev" branch on that host. Hum, that might be the issue...

**Comment by vwhissell** [comment]
Same thing
http://192.168.60.199:5985/_api/ws on Firefox

`{"error":"illegal_database_name","reason":"Name: '_api'. Only lowercase characters (a-z), digits (0-9), and any of the characters _, $, (, ), +, -, and / are allowed. Must begin with a letter."}`

**Comment by montive** [comment]
Which version of Faraday are you using?

**Comment by vwhissell** [comment]
Now that I rebuilt the server.ini

 ```
cat ~/.faraday/config/server.ini
[faraday_server]
port=5984
bind_address=192.168.0.199

[ssl]
port=6984
certificate=
keyfile=
;keyfile_pwd=''

[couchdb]
host=192.168.0.199
port=5985
ssl_port=6985
user=
password=
protocol=http
```

**Comment by montive** [comment]
You're probably using Faraday v3. In this new version, we don't use CouchDB anymore. We use PostgreSQL.

In the file server.ini at the [faraday_server] section, change the port to: 5985. 

The [couchdb] section is only used when we want to import our data from CoudhDB to PostgreSQL.

**Comment by vwhissell** [comment]
```
./faraday.py -v
Faraday v2.7.2
```

**Comment by WinnaZ** [comment]
If you are in the v2.7.2, it's important that before opening the client you create a workspace using the web UI, we have better solutions for this type of issue on V3beta. But for that version please create a workspace before and let us know.
Also if you have a professional or corporate license you should open a ticket on our zoho desk! You will have a better support experience there. 
Let us know how it goes!

**Comment by WinnaZ** [comment]
Hi there how did that go?
Need any further assistance?
