### ISSUE TITLE
Web front-end stops working - No such resource

### ISSUE THREAD

**Issue by daniejstriata** [infobyte/faraday#267]
## Issue Type
 - Bug Report

## Faraday version
Faraday v3.0

## Component Name
Faraday Server

## Steps to reproduce

1. I was using the Webpage editing a Host. No errors or issues. Suddenly the page goes white with the following:
![image](https://user-images.githubusercontent.com/13314239/43451601-9b9714a2-94b5-11e8-9c11-1b8df27cc499.png)
2. I tried many various things mostly restarting the Faraday client, which did not help.
3. I restarted the Faraday Server and that allowed me to use the web frontend again.

### Debugging tracebacks (current results)

I looked at the known logs to me for my OS and Faraday and cannot see why this is now happening.
Debug mode did not give me any more detail.

Please attach the result of:

[requirements_freeze.txt](https://github.com/infobyte/faraday/files/2244809/requirements_freeze.txt)

### Configuration files

No changes to default install.

### OS

Provide information on your operating system. Example:

$ cat /etc/lsb-release
DISTRIB_ID=LinuxMint
DISTRIB_RELEASE=18.3
DISTRIB_CODENAME=sylvia
DISTRIB_DESCRIPTION="Linux Mint 18.3 Sylvia"

**Comment by WinnaZ** [comment]
Thank you for your feedback.
I will check this out tho it seems really estrange.
Is it possible that your instance running the server stopped for some reason?
Would you mind sending us the logs?
There are located in .faraday/log .
Cheers.

**Comment by daniejstriata** [comment]
The Server was running the whole time and I was unable to see it log anything new when I got the error. Restarting the server resolved the issue.

I attached my logs
[logs.zip](https://github.com/infobyte/faraday/files/2245669/logs.zip)
I think the issue was with one of the Python modules like Twisted that did not log into the server log file. If there is anything else I should do next time something like this happen please let me know. debug was only used on the Client and restarting the Server resolved my issue so I would not have been able to change its state.

BTW
I noticed that I was missing the bs4 module according to the logs but it was not mentioned as a requirement. I installed it using pip and the warning went away.

**Comment by llazzaro** [comment]
Can try to execute faraday-server.py with --debug flag could ? What about your ram usage? it could be the os killing the process?
Thanks!
