### ISSUE TITLE
Cannot run GUI

### ISSUE THREAD

**Issue by junzi749** [infobyte/faraday#27]
After installing the faraday and all related dependencies on Mac Yosemite, I got message "Please config Couchdb for fancy HTML5 Dashboard" after command ./faraday.py

Can you kindly help me know how to fix it?

Thank you.

**Comment by f-amato** [comment]
Hi @junzi749 thanks for your report, in case of OSX you have to run faraday with the following command:
./faraday.py --gui=nogui
then run 
./faraday-terminal.zsh

Take a look to:
https://github.com/infobyte/faraday/wiki/Installation#osx

**Comment by junzi749** [comment]
Thanks for the response. One more question, is the GUI avaiable in Mac OS?

**Comment by f-amato** [comment]
It will be added in a near future. You can use Web GUI in Mac OS
