### ISSUE TITLE
Feature Idea - Import MBSA log

### ISSUE THREAD

**Issue by daniejstriata** [infobyte/faraday#271]
I use MBSA (Microsoft Baseline Security Analyzer) to check my windows hosts in place of Lynis on Linux hosts. Will it be possible to import the MBSA logs into Faraday in the future?

I've attached example output below:

### Reports/Extra data
[MBSA.log](https://github.com/infobyte/faraday/files/2315051/MBSA.log)

**Comment by WinnaZ** [comment]
Hey!
We'll have it in mind for future plugin development.
Cheers :)
