### ISSUE TITLE
Docker distribution functionality regression after postgresql

### ISSUE THREAD

**Issue by fryjustinc** [infobyte/faraday#273]
## Issue Type
 - Bug Report

## Faraday version

Faraday v3.0.1

## Component Name

run_service.sh

## Steps to reproduce
Open terminal.

$ sudo docker run -t -i infobyte/faraday /root/run.sh

> 2018-09-02 11:18:27,728 - faraday-server.__main__ - ERROR {MainThread} [faraday-server.py:102 - check_postgresql() ]
> 
> Could not connect to PostgreSQL.
> Please check:
>   * if database is running
>   * configuration settings are correct.
> 
> For first time installations execute:
> 
>   python manage.py 

$ python manage.py initdb

> python: can't open file 'manage.py': [Errno 2] No such file or directory

## Expected results

run_service.sh should contain commands to start postgresql, it currently only contains couchdb. the docker distribution needs to be updt

### Debugging tracebacks (current results)

pip requirements:
alembic==1.0.0
asn1crypto==0.24.0
attrs==17.4.0
autobahn==18.8.2
Automat==0.6.0
Babel==2.6.0
backports-abc==0.5
backports.csv==1.0.6
backports.ssl-match-hostname==3.4.0.2
bcrypt==3.1.4
beautifulsoup4==4.6.3
blinker==1.4
certifi==2018.8.24
cffi==1.11.2
chardet==3.0.4
cli-helpers==1.0.2
click==6.7
colorama==0.3.9
configobj==5.0.6
constantly==15.1.0
couchdbkit==0.6.5
cryptography==2.1.4
decorator==3.4.0
deprecation==2.0.5
enum34==1.1.6
filedepot==0.5.2
filteralchemy==0.1.0
Flask==1.0.2
Flask-BabelEx==0.9.3
Flask-Classful==0.14.1
Flask-Login==0.4.1
Flask-Mail==0.9.1
Flask-Principal==0.4.0
Flask-Security==3.0.0
Flask-Session==0.3.1
Flask-SQLAlchemy==2.3.2
Flask-WTF==0.14.2
funcsigs==1.0.2
html5lib==0.999
http-parser==0.8.3
humanize==0.5.1
hyperlink==17.3.1
idna==2.7
incremental==17.5.0
ipaddress==1.0.19
IPy==0.83
ipython==1.2.1
itsdangerous==0.24
Jinja2==2.10
Mako==1.0.7
manage.py==0.2.10
MarkupSafe==0.23
marshmallow==2.15.4
marshmallow-sqlalchemy==0.14.1
mockito==1.0.12
ndg-httpsclient==0.4.0
nplusone==1.0.0
packaging==17.1
passlib==1.7.1
pexpect==3.1
pgcli==1.10.3
pgspecial==1.11.2
Pillow==5.2.0
prompt-toolkit==1.0.15
psycopg2==2.7.5
pyasn1==0.4.2
pyasn1-modules==0.2.1
pycparser==2.18
pydot==1.2.4
Pygments==2.2.0
pygobject==3.12.0
PyHamcrest==1.9.0
pyOpenSSL==17.5.0
pyparsing==2.2.0
python-dateutil==2.7.3
python-editor==1.0.3
python-slugify==1.2.5
pytz==2018.5
requests==2.19.1
restkit==4.2.2
service-identity==17.0.0
setproctitle==1.1.10
simplegeneric==0.8.1
singledispatch==3.4.0.3
six==1.11.0
socketpool==0.5.3
speaklater==1.3
SQLAlchemy==1.2.0
sqlalchemy-schemadisplay==1.3
sqlparse==0.2.4
ssh-import-id==3.21
tabulate==0.8.2
terminaltables==3.1.0
tornado==4.5.2
tqdm==4.25.0
Twisted==18.7.0
txaio==18.8.1
Unidecode==1.0.22
urllib3==1.23
w3af-api-client==1.1.7
wcwidth==0.1.7
webargs==4.0.0
websocket-client==0.51.0
Werkzeug==0.14.1
Whoosh==2.7.4
WTForms==2.2.1
zope.interface==4.5.0
### Screenshots
[https://i.imgur.com/icW55Iv.jpg](url)
## Environment information
standard docker

### OS
OSX high sierra

**Comment by WinnaZ** [comment]
Hey there,
We are currently taking a look at this and trying to come up with a solution.
We'll keep you updated!

**Comment by alem0lars** [comment]
Any updates?

**Comment by WinnaZ** [comment]
Yes!
 We are working on it,
it's almost done just needs some testing,
it will be realesed when the next version of Faraday somes out.
Cheers!

**Comment by alem0lars** [comment]
How long will it take?

**Comment by WinnaZ** [comment]
We don't have a release date set out yet.

**Comment by fryjustinc** [comment]
You're delaying the patch to a bug that makes an entire platform DoA? You guys should have some basic regression tests for this stuff.

**Comment by edoz90** [comment]
still nothing?

**Comment by marxenegls** [comment]
"initdb must be run as the user that will own the server process, because the server needs to have access to the files and directories that initdb creates. Since the server cannot be run as root, you must not run initdb as root either." postgresDocs 
my2cents;
which i think explains the whole credentials issue

**Comment by llazzaro** [comment]
> "initdb must be run as the user that will own the server process, because the server needs to have access to the files and directories that initdb creates. Since the server cannot be run as root, you must not run initdb as root either." postgresDocs
> my2cents;
> which i think explains the whole credentials issue

The issue creator uses faraday "initdb" (python manage.py initdb) which will create faraday tables on postgresql. I think you are talking about postgres initdb command which is another command.

**Comment by jloehel** [comment]
The initdb function of the manager does not work really well with docker. Is there a way to pass the `connection_string` directly as ENV variable or secret to the container? Why do you default to localhost, and try to create the database, user role, ... with this function? In my opinion it should fail if the database was not configured correctly.

**Comment by llazzaro** [comment]
Hi,

In order to use docker, please refer to this guide: https://support.faradaysec.com/portal/en/kb/articles/docker

You can use volumes for configuration. 

```
$ docker run \
    ....
    -v /path/to/my_doc_folder:/faraday-license \
    -v /path/to/my_storage_folder:/faraday-storage \
    -v /path/to/my_config_folder:/faraday-config
    ....
    faraday:X.Y.Z
```
