### ISSUE TITLE
Web-UI login credentials

### ISSUE THREAD

**Issue by sumgro** [infobyte/faraday#276]
I've installed the faraday on the parrot OS and while both the server and client are running post following the first instructions to the T.

I'm not able to access the web-ui at http://localhost:5985, it prompts for the username/password.

How do I find out the username/password or is there a default one? The Wiki does not share the solution.

Please help!

**Comment by WinnaZ** [comment]
the username and password was given to you when you executed manage.py initdb!

**Comment by sumgro** [comment]
I guess I've screwed up the whole installation. Seems like few commands were executed as root while few as user in the Parrot OS setup. 

Now the server or the client won't start up again.

Is there a way I can start from the scratch for both faraday-dev and the postgresql part? Please guide me.

Thanks in advance.

**Comment by WinnaZ** [comment]
well you could uninstall Postgres if you are not currently using for any other project.
https://askubuntu.com/questions/1010442/how-to-uninstall-the-postgresql

And then install it again.

You could also make a virtualenv for the use of faraday and install all the python dependencies inside.

**Comment by llazzaro** [comment]
Hi,
You can also try to delete the faraday database using the command "dropdb faraday".
Then you can follow the faraday install steps again.

When you start the server you can user the --bind and --port parameters to specify the listening address and port.

You can also check the logs at $HOME/.faraday/logs and if you find any error please attach it to this ticket.

**Comment by llazzaro** [comment]
On the next version you can use manage.py change_password to reset the password or you can use the "sql_shell" on the current version to change the password.

Steps to change password with sql_shell:


> python manage.py sql_shell

then execute the following query:

> update faraday_user set password='PASSWORD';


After you login to faraday the password will be encrypted.

**Comment by sumgro** [comment]
I've tried removing the postgresql and installing it again, but the tables and roles have stayed.

When I try to run the ./faraday-server.py, I get the following message:

sudo ./faraday-server.py 
2018-09-15 10:35:58,081 - faraday-server.__main__ - ERROR {MainThread} [faraday-server.py:102 - check_postgresql() ]  

Could not connect to PostgreSQL.
Please check: 
  * if database is running 
  * configuration settings are correct. 

For first time installations execute: 

  python manage.py initdb


┌─[✗]─[root@parrot]─[/home/Tools/Reporting/faraday-dev]
└──╼ #sudo python manage.py initdb
Database section  already found. Do you want to reconfigure database? (yes/no) no

**Comment by sumgro** [comment]
> On the next version you can use manage.py change_password to reset the password or you can use the "sql_shell" on the current version to change the password.
> 
> Steps to change password with sql_shell:
> 
> > python manage.py sql_shell
> 
> then execute the following query:
> 
> > update faraday_user set password='PASSWORD';
> 
> After you login to faraday the password will be encrypted.

Tried this and got an error too
#python manage.py sql_shell
Usage: manage.py [OPTIONS] COMMAND [ARGS]...
Try "manage.py -h" for help.

Error: No such command "sql_shell".

**Comment by WinnaZ** [comment]
We are glad to hear that.
Enjoy Faraday!

**Comment by nepohelovski** [comment]
faraday-manage change-password

**Comment by hwac121** [comment]
> faraday-manage change-password

Now THIS was a great answer!

**Comment by hwac121** [comment]
> > On the next version you can use manage.py change_password to reset the password or you can use the "sql_shell" on the current version to change the password.
> > Steps to change password with sql_shell:
> > > python manage.py sql_shell
> > 
> > 
> > then execute the following query:
> > > update faraday_user set password='PASSWORD';
> > 
> > 
> > After you login to faraday the password will be encrypted.
> 
> Tried this and got an error too
> #python manage.py sql_shell
> Usage: manage.py [OPTIONS] COMMAND [ARGS]...
> Try "manage.py -h" for help.
> 
> Error: No such command "sql_shell".
> 
> Edit: This ticket can be closed, I've been able to fix the errors and sort out. The server, client and web-UI are all working now.
> 
> Thank you for your help and support.

Whoa...
You did not tell everyone what the fix was? I am still trying to find WTF the faraday user is?
About to go back old school and just install my own damn tools rather than using one of these fancy distros where they set everything up for you but don't bother to tell you all the important information like locations, logins, and passwords!!!!!
