### ISSUE TITLE
Consider replacing restkit with something else

### ISSUE THREAD

**Issue by rhertzog** [infobyte/faraday#279]
Hello,

I'm one of the Kali packagers and I noticed that faraday is using the "restkit" python module. That module has not seen any new release since 2013 and is vulnerable to a security issue (https://github.com/benoitc/restkit/issues/140) that has been ignored for years. For this reason, python-restkit is no longer part of Debian Testing and in Kali we have only kept it temporarily for the needs of faraday.

I saw that you are doing only minimal usage of this module so it would be nice if you could get rid of entirely.

Thank you for considering.

cc @sbrun

**Comment by montive** [comment]
Hi.
Thanks for your advice. We will keep it in mind for the upcoming release.

Cheers.

**Comment by llazzaro** [comment]
Hi,
We just merged this change in our development branch. It will be publish on v3.2

**Comment by llazzaro** [comment]
We just published v3.2 and restkit dep was removed.
