### ISSUE TITLE
Can't upload reports in GTKGui - Faraday 3.1.1

### ISSUE THREAD

**Issue by Gee94** [infobyte/faraday#285]
[pip-freeze.txt](https://github.com/infobyte/faraday/files/2450937/pip-freeze.txt)
## Issue Type
 - Bug Report

## Faraday version
3.1.1

## Component Name

If you know where the problem lays indicate it:
GTKGui/Plugin

## Steps to reproduce
Removed server running 3.1.0 reinstalled version 3.1.1 community in virtualenv. Try to upload files from a remote client and client on system with server (.nessus and zap.xml) into the GTKGui and getting an error (See debug)

faraday.ReportProcessor - The file is /root/test-linuxscan-xxx_xx_x_xxx_eclwg1.nessus, Nessus
faraday.ReportProcessor - The file is /opt/test.xml, Zap

## Expected results

Successful upload of report

### Debugging tracebacks (current results)
Exception: 
    Traceback: Traceback (most recent call last):
  File "/opt/faraday/gui/gtk/application.py", line 906, in on_open_report_button
    on_file_selected(plugin_id, dialog.get_filename())
  File "/opt/faraday/gui/gtk/application.py", line 882, in on_file_selected
    self.report_manager.sendReportToPluginById(plugin_id, report)
  File "/opt/faraday/managers/reports_managers.py", line 170, in sendReportToPluginById
    self.processor.sendReport(plugin_id, filename)
  File "/opt/faraday/managers/reports_managers.py", line 54, in sendReport
    command_id = self.plugin_controller.processReport(plugin_id, filename, ws_name=self.ws_name)
  File "/opt/faraday/plugins/controller.py", line 283, in processReport
    'params': filepath,
  File "/opt/faraday/model/commands_history.py", line 56, in __init__
    self.ip = get_private_ip()
  File "/opt/faraday/model/commands_history.py", line 25, in get_private_ip
    ip = socket.gethostbyname(socket.gethostname())
gaierror: [Errno -2] Name or service not known

    
    Identifier: 5a6b4258bf61729792b8e59610ad6f24176f94722753d7e7fc457f446807e538
    Versions: OS: debian 9.5 ,
              Faraday Version: 3.1.1
              Python Versions: Python 2.7.13 
 Modules: [  ]
    
### Configuration files

None changed across versions

### OS
DISTRIB_ID=Debian
DISTRIB_RELEASE=9.5
DISTRIB_CODENAME=Stretch
DISTRIB_DESCRIPTION="Debian 9.5 Stretch"

**Comment by llazzaro** [comment]
Hi,
We think that you nessus report contains a hostname that cannot be resolved from the computer where the GTK ui is running.
We will check this issue with devel team and avoid cancelling the importation when a host cannot be resolved.

**Comment by Gee94** [comment]
Hi llazzaro,
The Nessus scan only has the hostname 'localhost.localdomain' and after a clean install of the O.S and Faraday 3.1.1 the same reports could then be imported (Nessus and ZAP)

**Comment by llazzaro** [comment]
Hi,
We just commited a fix to the develment branch and this will be released on v3.3
Thanks
