### ISSUE TITLE
[Feature Request] Automatically replace finding with custom finding

### ISSUE THREAD

**Issue by aress31** [infobyte/faraday#289]
A feature that I would like to see would be enabling Faraday users to automatically set up rules for replacing findings with custom findgins. For example, let say that a user is unhappy with the way Nessus report a specific finding and would prefer to have different wordings for it. It could be nice to set up a rule saying, alright each time this finding generated by Nessus is exported into Faraday it will get replaced by this custom finding that was wrote instead.

**Comment by WinnaZ** [comment]
hey there!
This is one of our latests features!
Here you can read more about it: http://blog.infobytesec.com/2018/09/faraday-v31-is-here-and-updated.html.
it's called the searcher.
Cheers!

**Comment by AresS31** [comment]
Hi @WinnaZ,

What I am exactly looking for is a feature that would allow me to automatically replace a finding with another one from the knowledge database. Not sure how to do that with the searcher. And I believe that for ease of use there should be a dedicated tab, or setting in the web interface to set the searcher rules and whener a plugin (import nessus scan for example) is triggered the searcher will automatically do the updates.

Regards
Alex

**Comment by WinnaZ** [comment]
don't pay to much attention to the same it's sort of misleading.
It will change info given certain regex, here you have a wiki that explains more:https://github.com/infobyte/faraday/wiki/Searcher

if you wanna change the way a vuln is imported into faraday cause you don't like how a certain tool names it you can always cutomize de plugins scripts.

**Comment by ezk06eer** [comment]
Searched was deprecated, use workflows instead.
