### ISSUE TITLE
[Feature Request] Confirm multiple findings in one go

### ISSUE THREAD

**Issue by AresS31** [infobyte/faraday#291]
Hi,

Is it possible to confirm more than one finding/sub-finding in one go? What I mean by this, is that if I would like to confirm multiple findings, e.g. all the medium in one click how can I do that? At the moment it seems that even for individual findings, we must click on the finding which will take us to the details of all hosts/services affected byt he finding and confirm each of them individually.

Could you please implement a feature to confirm:
1/ When selecting an individual finding, confirming it will confirm all its child items.
2/ We can select a bunch of findings and confirm them in one click.

Thanks,
Alex

**Comment by montive** [comment]
Hi there.

It is possible to confirm multiple vulns at once. Just select the vulns that you want to confirm, then click on "Actions" (the button that is next to the edit button). A dialog will open and you must select "Confirm/change to false positive".

If you want to confirm those vulns that are medium, search them (severity:medium), then select them all by click on the "check" button and follow the instructions above.

I hope this can help you. 
Cheers.
