### ISSUE TITLE
[Feature Request] Custom portal branding

### ISSUE THREAD

**Issue by aress31** [infobyte/faraday#293]
Hi,

A core feature to implement IMHO is the possibility to "brand" the Faraday web portal using custom images/logos, and remove the Faraday text instances to replace them with a company name instead. Indeed, most security consultancies would not want to get the Faraday framework because of this limitation. If they grant access to the web portal to their customers in order to monitor a pentest in real time, they would want their own company name and logos to appear on the portal.

Regards
Alex

**Comment by montive** [comment]
Hi there.

Once again, thanks for the idea.
We will keep it in mind for next releases.

Cheers

**Comment by ezk06eer** [comment]
Faraday doesnt support this feature, and we are not thinking about supporting it.
