### ISSUE TITLE
faraday-server.py failed to start

### ISSUE THREAD

**Issue by lmcthbe** [infobyte/faraday#294]
## Issue Type
 - Bug Report

## Faraday version
Faraday v3.1.1

## Steps to reproduce
1 - Installing Faraday on Ubuntu 16.04 using katoolin
2 - When starting faraday-server.py, it failed with the error below 

[requirements_freeze.txt](https://github.com/infobyte/faraday/files/2473766/requirements_freeze.txt)
[server.ini.txt](https://github.com/infobyte/faraday/files/2473774/server.ini.txt)
[user.xml.txt](https://github.com/infobyte/faraday/files/2473775/user.xml.txt)
### Debugging tracebacks (current results)
2018-10-12 15:45:04,681 - faraday-server.__main__ - WARNING {MainThread} [faraday-server.py:94 - check_postgresql() ]  No workspaces found. Remember to execute CouchDB importer
2018-10-12 15:45:04,684 - faraday-server.server.web - INFO {MainThread} [web.py:82 - __init__() ]  Starting web server at http://localhost:5985/
2018-10-12 15:45:04,812 - faraday-server.server.web - ERROR {MainThread} [web.py:179 - run() ]  Something went wrong when trying to setup the Web UI
2018-10-12 15:45:04,813 - faraday-server.server.web - ERROR {MainThread} [web.py:180 - run() ]  __init__() takes exactly 2 arguments (3 given)
Traceback (most recent call last):
  File "/usr/share/python-faraday/server/web.py", line 160, in run
    self.raw_report_processor = RawReportProcessor()
  File "/usr/share/python-faraday/server/api/modules/upload_reports.py", line 80, in __init__
    self.processor = ReportProcessor(plugin_controller, None)
TypeError: __init__() takes exactly 2 arguments (3 given)

### OS

$ cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.5 LTS"

**Comment by montive** [comment]
Hi there.

Can you send me the logs? They are located in the folder ~/.faraday.

Also, send me the output of the following command:

`$ python manage.py status-check`

**Comment by lmcthbe** [comment]
See below

```
/usr/share/python-faraday/manage.py status-check

Checking if postgreSQL is running...
[+] PostgreSQL is running
[+] PostgreSQL lock not detected.

Checking if Faraday is running...
[-] Faraday Server is not running
[-] Faraday GTK is not running

Checking Faraday config...
[-] Credentials can not be checked. Either Faraday Server not running or database not working
[-] /.faraday/storage -> Permission denied
[-] Port 5985 in localhost is not open
```

[faraday-server.log](https://github.com/infobyte/faraday/files/2474136/faraday-server.log)
[faraday.log](https://github.com/infobyte/faraday/files/2474137/faraday.log)
[psql_log.log](https://github.com/infobyte/faraday/files/2474138/psql_log.log)

**Comment by montive** [comment]
Did you follow this guide in order to install Faraday: https://github.com/infobyte/faraday/wiki/Installation-Community

Which command are you exactly running?

**Comment by lmcthbe** [comment]
I just have installed the python-faraday package from kali repo and then I have started  the server using
```
systemtcl start python-faraday
```
and noticed that the service was not started

**Comment by lmcthbe** [comment]
I fixed by reconfiguring the python-faraday package. It seems that the server.ini was somehow corrupted. Ticket can be closed

**Comment by lmcthbe** [comment]
I have also issue to create workspace via scripting. I got an error about "not authorized to make this request. Please check your domain". 

And I could not import reports anymore again related to authorization. 

Please help. This latest version is really not working well on Kali

I have tried also from GitHub and having other issues

Keep you posted

**Comment by lmcthbe** [comment]
When creating workspace from UI I got:
```
{"data":"<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 3.2 Final//EN\">\n<title>500 Internal Server Error</title>\n<h1>Internal Server Error</h1>\n<p>The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.</p>\n","status":500,"config":{"method":"POST","transformRequest":[null],"transformResponse":[null],"url":"https://159.117.202.150/_api/v2/ws/","data":{"_id":"toto","customer":"","name":"toto","type":"Workspace","children":[],"duration":{"start_date":"","end_date":""},"scope":[],"description":""},"headers":{"Accept":"application/json, text/plain, */*","Content-Type":"application/json;charset=utf-8"}},"statusText":""}
```

**Comment by daniejstriata** [comment]
I get the same from a clean Kali 2018.3a install to try and get Faraday working. The server starts but the agent fails due to 500 internal server error.

**Comment by lmcthbe** [comment]
@daniejstriata I noticed that I got a error regarding credential not matching.
I wonder if the connection to postgres is OK because I cannot see any of my workspace from UI while I can see them sql 

```
Checking if postgreSQL is running...
[+] PostgreSQL is running
[+] PostgreSQL lock not detected. 

Checking if Faraday is running...
[+] Faraday Server is running. PID:6763         
[-] Faraday GTK is not running

Checking Faraday config...
[-] Error. Credentials does not match
[+] /.faraday/storage -> Permission accepted
[+] Port 5985 in localhost is open
```

**Comment by daniejstriata** [comment]
Alas I broke mine so badly that I have to reinstall Kali. There are too many other tools dependant on PostgreSQL that I don't want to break them too by removing SQL and starting from scratch. I'm almost done reinstalling Kali. Will then snapshot and see if I can figure it out.

**Comment by lmcthbe** [comment]
Got the following error when using scripting to create workspace from https://github.com/infobyte/faraday/wiki/Workspaces
```
Traceback (most recent call last):                                                                                                                                   
  File "./createws.py", line 30, in <module>                                                                                                                         
    result = server.create_workspace( workspace, 'DESCRIPTION', date_today, date_today, 'CUSTOMER NAME')                                                             
  File "/usr/share/python-faraday/persistence/server/server.py", line 1475, in create_workspace                                                                      
    type="Workspace")                                                                                                                                                
  File "/usr/share/python-faraday/persistence/server/server.py", line 349, in _save_db_to_server
    return _post(post_url, expected_response=201, **params)                                              
  File "/usr/share/python-faraday/persistence/server/server.py", line 270, in _post                                                                                                                                                                     
    json=params))                                                                                                   
  File "/usr/share/python-faraday/persistence/server/server.py", line 188, in wrapper
    response = func(*args, **kwargs)                                         
  File "/usr/share/python-faraday/persistence/server/server.py", line 212, in _unsafe_io_with_server                                                                                                                                                    
    raise Unauthorized(answer)                                                                                                                                                                                                                          
persistence.server.server_io_exceptions.Unauthorized: You're not authorized to make this request. The answer from the server was <Response [401]>. Plase check that your domain is the correct one.
```

**Comment by montive** [comment]
Hi @lmcthbe 

Did you check that your credentials are correct in the file _~/.faraday/config/user.xml_?

**Comment by lmcthbe** [comment]
Is it the api_ setting?
```
<shell_maximized>0</shell_maximized>                                                                                                                                                                                                                  
  <last_workspace>untitled</last_workspace>                                                                                                                                                                                                             
  <api_url />                                                                                                                                                                                                                                           
  <api_username />                                                                                                                                                                                                                                      
  <api_password />                                                                                                                                                                                                                                      
  <couch_uri>http://127.0.0.1:5985</couch_uri>                                                                                                                                                                                                          
  <couch_is_replicated>False</couch_is_replicated>                                                                                                                                                                                                      
  <couch_replics />                                                                                                                                                                                                                                     
  <version>3.1.1</version>                              
```

**Comment by montive** [comment]
Yes. I'm sending you an example. Lets suppose that we want to run Faraday in _localhost:5985_, also that our username is _faraday_ and our password is _changeme_. The file should look like this:

```
  <api_url>http://localhost:5985</api_url>
  <api_username>faraday</api_username>
  <api_password>changeme</api_password>
```

**Comment by montive** [comment]
Are you using Faraday's community version? 
Also, do the credentials that you have in the file user.xml match with the ones on the script?

**Comment by lmcthbe** [comment]
yes using Kali package however the credential issue that I had is fixed because I got an 500 server error now with the correct credential for both creation of workspace to importing report into existing workspace
```
CantCommunicateWithServerError: Couldn't get a valid response from the server when requesting to URL http://localhost:5985/_api/v2/ws and function <function get at 0x7fe8b0d83398>. Response was <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>500 Internal Server Error</title>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error and was unable to complete your request.  Either the server is overloaded or there is an error in the application.</p>
```

**Comment by montive** [comment]
Sorry for the question but do you have the server running? I just reproduced this issue by stopping the server and running the script.

**Comment by lmcthbe** [comment]
Yes it is running and  it is a bit different error when server is not running (there is no 500 error) see below

server not running
```
persistence.server.server_io_exceptions.CantCommunicateWithServerError: Couldn't get a valid response from the server when requesting to URL http://127.0.0.1:5985/_api/v2/ws/ and function <function post at 0x7f5f6e1198c0>. Response was
```

server running
```
persistence.server.server_io_exceptions.CantCommunicateWithServerError: Couldn't get a valid response from the server when requesting to URL http://127.0.0.1:5985/_api/v2/ws/ and function <function post at 0x7f6cdcc818c0>. Response was <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>500 Internal Server Error</title>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error and was unable to complete your request.  Either the server is overloaded or there is an error in the application.</p>
```

**Comment by llazzaro** [comment]
Hi,

Can you try to downgrade Marshmallow? it seems you have installed marshmallow 3.0.0b14, which is a beta version.

Try the command:
`
pip uninstall marshmallow
pip install marshmallow==2.15.3
`

This downgrade should fix the error:

`
TypeError: __init__() got an unexpected keyword argument 'strict'
`

**Comment by lmcthbe** [comment]
Sorry it worked now for creating workspace. I did not noticed the server restart ..

Now importing report failed with a different error:
```
* Faraday UI is ready
Point your browser to: 
[http://127.0.0.1:5985/_ui]

2018-10-17 00:11:42,342 - faraday - INFO [api.py:118 -      _setUpAPIServer() ]  XMLRPC API server configured on ('127.0.0.1', 9876)
127.0.0.1
2018-10-17 00:11:42,353 - faraday - INFO [api.py:68 -            startAPIs() ]  REST API server configured on ('127.0.0.1', 9977)
2018-10-17 00:11:42,416 - faraday.ReportProcessor - INFO [reports_managers.py:53 -           sendReport() ]  The file is /root/.msstw/test/ndir/nmap-cis-us-iad1-udnp1.cdx-test2.unifieddeliverynetwork.net-tcp.xml, Nmap
There was an error while starting Faraday:
*** [Errno -2] Name or service not known ***
2018-10-17 00:11:42,437 - faraday - INFO [api.py:485 -                  log() ]  Closing Faraday...
```

**Comment by llazzaro** [comment]
@lmcthbe great that the previous error was fixed.
Could it be that the .xml file contains domains that can't be resolved? This could be a known issue we are working on.

**Comment by daniejstriata** [comment]
I installed faraday 3.0.1 and did not have any of these issues.

**Comment by lmcthbe** [comment]
Even with no service/detection I got the same error and I tried to import a nikto xml file and got the same issue. I tried also using IP address when doing scanning but it is always the same result

**Comment by lmcthbe** [comment]
I found the issue. The /etc/hosts does not have the hostname defined in the loopback, once defined the error is gone and importing is working
