### ISSUE TITLE
/usr/bin/env/ zsh...... error

### ISSUE THREAD

**Issue by yuleitest** [infobyte/faraday#296]
![image](https://user-images.githubusercontent.com/28857318/47074502-1a376780-d22d-11e8-9ce6-c5a302d8fb02.png)

![image](https://user-images.githubusercontent.com/28857318/47074542-31765500-d22d-11e8-9a25-23b2719866f6.png)

**Comment by llazzaro** [comment]
Hi,
I think you are missing zsh, can you install it with:

```
sudo apt install zsh
```

**Comment by yuleitest** [comment]
ok, thank you  very much.....   now it works well....
