### ISSUE TITLE
Hostname get overwitten

### ISSUE THREAD

**Issue by Techbrunch** [infobyte/faraday#297]
## Issue Type
 - Bug Report

No sure where the problem is but when using plugins such as `dig` or `nmap` hostnames get overwritten instead of adding new ones.

## Faraday version

Faraday v3.1.1

## Steps to reproduce

```
[faraday](demo2) xxx% dig A www.google.com 2>&1 | tee -a tmp.RjRYGIgHrh73yuNnS734yLxelT3ZQ

; <<>> DiG 9.10.6 <<>> A www.google.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 288
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1460
;; QUESTION SECTION:
;www.google.com.			IN	A

;; ANSWER SECTION:
www.google.com.		228	IN	A	216.58.201.228

;; Query time: 38 msec
;; SERVER: 192.168.1.1#53(192.168.1.1)
;; WHEN: Fri Oct 19 15:12:56 CEST 2018
;; MSG SIZE  rcvd: 59

[faraday](demo2) xxx%  nmap -oX /Users/xxx/.faraday/data/demo2_Nmap_output-2.45817454616.xml -sn 216.58.201.228 2>&1 | tee -a tmp.UEufPRaZPMIwpiRZR0uqJmOC7Nx9X
Starting Nmap 7.70 ( https://nmap.org ) at 2018-10-19 15:13 CEST
Nmap scan report for fra02s18-in-f4.1e100.net (216.58.201.228)
Host is up (0.023s latency).
Nmap done: 1 IP address (1 host up) scanned in 0.05 seconds
```

## Expected results

The hostname `fra02s18-in-f4.1e100.net ` should be added to the IP instead of replacing `www.google.com`.

**Comment by WinnaZ** [comment]
I just tested this out and you are right,
I'll look into it and let you know when i have an update.
Cheers!

**Comment by rubentroncon** [comment]
This issue is still present. I'm seeing this when using the Sublist3r plugin.

**Comment by WinnaZ** [comment]
The version of faraday just released has this issue fixed!
You can read more about what's new here: https://t.co/zwvQR1lTcv
Cheers!
