### ISSUE TITLE
Faraday Installation [docker ubuntu/windows]

### ISSUE THREAD

**Issue by Thilaknath** [infobyte/faraday#298]
Please search the [Wiki](https://github.com/infobyte/faraday/wiki) for a solution before posting a ticket. Use the <strong>“New Support Request”</strong> button to the right of the screen to submit a ticket for technical support.

## Issue Type
 - Bug Report

## Faraday version
 - Installation of Community edition

## Component Name

If you know where the problem lays indicate it:

## Steps to reproduce

1) Pull the following docker image docker pull ubuntu
2) Run the container with port 5985 exposed
3) Follow instructions from https://github.com/infobyte/faraday/wiki/Installation-Community#server-system-dependencies  for faraday installation
4) The server mentions it starts up, But hitting http://localhost:5985 doesn't respond, also doing a ping to http://localhost:5985 within the container produces no response. 

I am running docker on Windows 10 64 bit version.

## Expected results

What did you expect to happen when following the steps above?

### Debugging tracebacks (current results)

Try to reproduce the bug with the server and/or gtk client in debug mode and check the logs for the ERROR string.
Add here any errors you find while running in debug mode or, if possible, Faraday’s log files (located at *$HOME/.faraday/logs/*).

If you need help on how to execute in debug mode [click here for more information](https://github.com/infobyte/faraday/wiki/troubleshooting).

Please attach the result of:

pip freeze > requirements_freeze.txt

### Screenshots

If you don't find anything on the logs, please provide screenshots of the error.

### Configuration files

Mention any settings you have changed/added/removed.

### Reports/Extra data

If you are having issues with plugins, please attach relevant files if possible.
(strip your reports of all sensitive information beforehand).

### OS

Provide information on your operating system. Example:

$ cat /etc/lsb-release
DISTRIB_ID=Windows
DISTRIB_RELEASE=10
DISTRIB_CODENAME=
DISTRIB_DESCRIPTION="Windows 10"

Docker Image details
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.1 LTS"

**Comment by WinnaZ** [comment]
Hey there,
Our Faraday docker image hasn't been released yet.
But we'll keep you updated.

**Comment by Thilaknath** [comment]
Hey @WinnaZ  what is this image then ? https://hub.docker.com/r/infobyte/faraday/

Also there setup instructions here https://github.com/infobyte/faraday/wiki/Installation-Docker. Can you please clarrify

**Comment by WinnaZ** [comment]
Let me clarify,
That docker contains a version of the old Faraday 2.7,
We are now at the version 3.2 and that docker image has yet not been released,
thought we will be releasing it soon!
cheers.
