### ISSUE TITLE
cannot import name want_bytes

### ISSUE THREAD

**Issue by milevyo** [infobyte/faraday#299]
## Issue Type
 - Bug Report

## Faraday version
from file 'VERSION'
3.2

## Component Name
python manage.py initdb

## Steps to reproduce
1. clean install of ubuntu-server version "Ubuntu 16.04.5 LTS"
2. install system dependencies
3. install python dependencies
4. execute python manage.py 

## Expected results
No Errors?

## Environment information
[requirements_freeze.txt](https://github.com/infobyte/faraday/files/2506837/requirements_freeze.txt)

### Configuration files
none

### Reports/Extra data

```
user@Faraday:~/faraday$ python manage.py initdb
/home/superuser/.local/lib/python2.7/site-packages/psycopg2/__init__.py:144: UserWarning: The psycopg2                                                                                              wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip                                                                                              install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-                                                                                             install-from-pypi>.
  """)
Traceback (most recent call last):
  File "manage.py", line 19, in <module>
    from server.commands.app_urls import show_all_urls
  File "/home/superuser/faraday/server/commands/app_urls.py", line 7, in <module>
    from server.web import app
  File "/home/superuser/faraday/server/web.py", line 31, in <module>
    from server.app import create_app
  File "/home/superuser/faraday/server/app.py", line 36, in <module>
    from flask_session import Session
  File "/home/superuser/.local/lib/python2.7/site-packages/flask_session/__init__.py", line 16, in <mod                                                                                             ule>
    from .sessions import NullSessionInterface, RedisSessionInterface, \
  File "/home/superuser/.local/lib/python2.7/site-packages/flask_session/sessions.py", line 23, in <mod                                                                                             ule>
    from itsdangerous import Signer, BadSignature, want_bytes
ImportError: cannot import name want_bytes

```

### OS

$ cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.5 LTS"

**Comment by llazzaro** [comment]
It's Dangerous 1.0.0 was recently released.
The temporary solution is doengrade itsdangerous until flask-sesison project supports latest version of it's dangerous. 

``` bash
pip install 'itsdangerous<1.0.0'
```

To follow up flask session issue check here https://github.com/fengsp/flask-session/issues/89

**Comment by milevyo** [comment]
things that i did that make things to work 

actions i did in order:
1. pip install 'itsdangerous<1.0.0'  --- as advised somewhere in stackoverflow.com ---
2. pip install 'itsdangerous==0.23'
3. pip2 uninstall 'itsdangerous'

then it works!

**Comment by montive** [comment]
Great to read that! Thanks for sending the instructions.

**Comment by davidism** [comment]
itsdangerous 1.1.0 was just released and contains a fix for this. Flask-Session should still be fixed so it doesn't rely on this, but it won't fail for now. You can unpin the requirement, or at least pin to `itsdangerous~=1.1.0` instead.

**Comment by llazzaro** [comment]
@davidism thanks for the news. We will update the requirements file

**Comment by milevyo** [comment]
thank you @davidism , i will confirm this later after i test it.
