### ISSUE TITLE
[BUG][DEPRECATE][FIXED][Faraday_v2] Strange missing of characters in GUI

### ISSUE THREAD

**Issue by nickkilla** [infobyte/faraday#30]
![screen shot 2015-05-09 at 7 30 43 pm](https://cloud.githubusercontent.com/assets/2976431/7554222/0a043bb8-f752-11e4-8cb8-62fb71ff4bde.jpg)

When adding first workspace, had an issue with the popup. See attached screenshot. 

After the first one was added, then all subsequent ones were shown correctly.

**Comment by f-amato** [comment]
Hi @nickkilla 
Thanks for reporting it. What linux distribution are you using?
Best

**Comment by nickkilla** [comment]
Linux kali 3.18.0-kali3-586 #1 Debian 3.18.6-1~kali2 (2015-03-02) i686 GNU/Linux

**Comment by Ezequieltbh** [comment]
Hi nickkilla!
Our QT interface is now deprecated.
GTK is the new Graphical interface for Faraday.
We are closing this ticket for this.
Cheers!
