### ISSUE TITLE
[Feature Request] Hostname view

### ISSUE THREAD

**Issue by Techbrunch** [infobyte/faraday#300]
## Issue Type
 - Feature Idea

Faraday looks awesome but there is something preventing us from using it. It looks like Faraday was built with internal pentest in mind.

It would be great to also have an "Hostname" view since that is what we are dealing with most of the times when doing external pentest.

It would also be nice to be able to link vulnerabilities to specific hostnames. Same thing with credentials.

What do you think ? If this is something you want I might be able to help.

PS: Notes were replaced by comments in 3.0 it seems but I don't see where you can add comments in the web ui currently. Is it possible ?

**Comment by WinnaZ** [comment]
We have been discusing new ways of dealing with host information lately.
For example for when you have dinamic ips and need to identify the host by something else.
We have not confirmed anything yet but it definetly is on our roadmap to do something about it.
Cheers!

**Comment by Techbrunch** [comment]
@WinnaZ That's good to here. Did you already set some kind of priority for this feature in the roadmap ?

**Comment by WinnaZ** [comment]
Not yet.

**Comment by noraj** [comment]
I think hostname is different from a domain name or an URL.
