### ISSUE TITLE
Unable to Connect to WebShell from Host

### ISSUE THREAD

**Issue by Thilaknath** [infobyte/faraday#302]
## Issue Type
 - Documentation Report

## Faraday version
C-3.2

## Component Name

If you know where the problem lays indicate it:
webshell

## Steps to reproduce

1) Enabled webshell following instructions from faraday wiki
2) faraday server client running inside a VM
3) Able to access webshell from the dashboard (i.e the web GUI)
4) Able to access faraday server from my host machine 
5) Unable to access the webshell from the host machine

## Expected results

Should be able to access the webshell running inside the VM from my host machine

### OS
Windows 10 (Host OS)

Provide information on your operating system. Example:

$ cat /etc/lsb-release
DISTRIB_ID=Kali
DISTRIB_RELEASE=kali-rolling
DISTRIB_CODENAME=kali-rolling
DISTRIB_DESCRIPTION="Kali GNU/Linux Rolling"

**Comment by WinnaZ** [comment]
Hi there,
Can you further explain what you mean by "Unable to access the webshell from the host machine" ?
it would be helpful if you could Attach an sreenshot of the error message you're getting.
but also, copy the url from faraday and paste it into a separate window of the brower.
Check if it's not a firewall problem.

**Comment by Thilaknath** [comment]
Hello @WinnaZ 

Components
1) Host - Windows (10)
2) Guest - Kali-Rolling (Running on virtual box) with faraday commercial demo installation

I followed the instruction as specified in [here ](https://github.com/infobyte/faraday/wiki/Web-Shell) to enable the webshell. 

I was able to enable the webshell with some tweaks, 
a) First uninstall the already existing butterfly installation and re install
b) Starting the server with allow all host allow any ip (i.e 0.0.0.0)

Something i noted, 
1) In the guest machine, despite enabling the webshell, Is it also needed to have the faraday GUI (which opens up the faraday client) running ?
If i leave the faraday client running, i see that the commands i execute in the webshell are available in the dashboard, if the client is not running, the dashboard doesn't record my commands from webshell.

Below attached is the screenshot of the error i get when i try to connect to the webshell running in the guest (kali) from my host(windows)
![butterfly](https://user-images.githubusercontent.com/3452073/47488733-3cd90a00-d845-11e8-8bc9-2510d4b29b18.png)

**Comment by WinnaZ** [comment]
Hey there,
Yes! As specified in the wiki:
![image](https://user-images.githubusercontent.com/24845440/47516124-0a3a0c00-d85b-11e8-87b7-a39cff6ca77a.png)

**Comment by WinnaZ** [comment]
We are happy to know that you got it to work.
Enjoy Faraday!
