### ISSUE TITLE
Running nmap did not automatically import any scan results

### ISSUE THREAD

**Issue by skiamakhe** [infobyte/faraday#305]
I ran an nmap scan from within the faraday GTK client, and after it completed, there were no results, even though nmap found several things to report. 
Command history from Web UI:
![image](https://user-images.githubusercontent.com/14299684/47529217-cea83d80-d86c-11e8-8128-ceab66844080.png)

Activity feed from web UI:
![image](https://user-images.githubusercontent.com/14299684/47529303-044d2680-d86d-11e8-80d9-274778f57198.png)

My understanding was that faraday was supposed to auto import results for any command it has a plugin for. Is that not right?

**Comment by WinnaZ** [comment]
yes,
would you send us the namp report?

**Comment by skiamakhe** [comment]
Are you talking about the output files I generated with my -oA option, or something that faraday created?

**Comment by skiamakhe** [comment]
This appears to be function of my also specifying and output in my nmap command. When I don't put the -oA option on there, faraday captures and imports the results. My guess is that while nmap will let you specify the -o option more than once, it only uses the last one. If that's the case, it wouldn't have generated any output in the expected place for faraday to catch.
