### ISSUE TITLE
Switching work spaces in Client Shell

### ISSUE THREAD

**Issue by Thilaknath** [infobyte/faraday#307]
## Issue Type
 - Feature Request

Hello Team, 

Is it possible to enable switching work spaces from the client shell. The idea is to have multiple users have connected to the server using the webshell and enable them to switch to work space they are allowed to work with. 

Currently the work space selection is only possible using the client UI which pops up and any change in there is reflected in the other terminals

**Comment by WinnaZ** [comment]
I agree this is a very needed feature,
Will discuss it with the team.
Cheers! and and you for the feedback!
