### ISSUE TITLE
LDAP [Does not belong to any registered Faraday group]

### ISSUE THREAD

**Issue by Thilaknath** [infobyte/faraday#308]
## Issue Type
 - Question

## Faraday version
C-3.2

## Component Name

If you know where the problem lays indicate it:
LDAP

## Steps to reproduce

1) Enabled ldap based on the wiki
2) When i try to login with my credentials i get the following error

2018-10-30 11:33:39,671 - faraday-server.server.api.modules.auth - DEBUG {PoolThread-twisted.internet.reactor-1} [auth.py:203 - auth_ldap() ]  Using domain None from server.ini config
2018-10-30 11:33:39,762 - faraday-server.server.api.modules.auth - DEBUG {PoolThread-twisted.internet.reactor-1} [auth.py:216 - auth_ldap() ]  Getting roles from LDAP
2018-10-30 11:33:39,798 - faraday-server.server.api.modules.auth - DEBUG {PoolThread-twisted.internet.reactor-1} [auth.py:288 - parse_users_search() ]  0 Faraday Users with user memberOf query per group
2018-10-30 11:33:39,798 - faraday-server.server.api.modules.auth - INFO {PoolThread-twisted.internet.reactor-1} [auth.py:221 - auth_ldap() ]  LDAP user Global\xxxxxx does not belong to any registered Faraday group

Note: Currently in the Corporate trial we have two users 

## Expected results

Should be able to access the faraday with my credentials with in my organization since ldap integration is turned on

### OS
Windows 10 (Host OS)

Provide information on your operating system. Example:

$ cat /etc/lsb-release
DISTRIB_ID=Kali
DISTRIB_RELEASE=kali-rolling
DISTRIB_CODENAME=kali-rolling
DISTRIB_DESCRIPTION="Kali GNU/Linux Rolling"

**Comment by Thilaknath** [comment]
@llazzaro Thanks for your response. We don't have access to create groups with in Active directory or neither does IT allow it to be done. Is it possible to allow access based on a specific Distribution List? 

In our scenario, We are planning to add eligible pentesters to a DL and allow access to Faraday. Hence if there is a customization in server.ini which accepts DL id as a param for verification of user cred would facilitate us to have the LDAP integration complete.

Please advise

Example: Upon creation of a DL
1) I get assigned or either to be a memberOf DL and my user is associated with the id of the DL as below.
CN=5bd96f347bcf84286100000a,OU=DL,OU=MSX

also i tried to have the displayName to be Dl fadmin.

Is there a possibility you can allow either the displayName or the distribution list ID at your end in order for authorization to go through?

**Comment by llazzaro** [comment]
@Thilaknath Thanks for your feedback.
We are planning to add the following configuration variables to ldap section of server.ini:
* use_local_roles
* default_local_role

When use_local_roles is set to True it will use the role saved on the faraday database, then admin_group, pentester_group and client_group will be ignored.
We are close to merge this changes on the development branch of the corp version and if this happends the feature will be available on v3.3 (14 Nov).

Thanks

**Comment by llazzaro** [comment]
Closing this issue, this should have been fixed in v3.4.
Please let me know if the issue continues.
