### ISSUE TITLE
Changing database password causes faraday failure to connect to server.

### ISSUE THREAD

**Issue by jimkil** [infobyte/faraday#309]
-Bug Report

Faraday v3.2 
(using postgresql)
using Kali 2018.4

I changed the sql password to allow me to access the web interface which initially worked. But when I shut down faraday and restarted it I received errors related to not having permission/unable to connect.

I found it appears that "manage.py change-password" is not updating "~/.faraday/config/user.xml" <api_password>. It also appeared that changing the password via the web interface may have similar issues.

I edited the api_password in the xml to match what I had changed it to via manage.py and was able to restore full functionality.

I hope this helps.

**Comment by WinnaZ** [comment]
Thanks for the feedback we'll take a look at this.

**Comment by llazzaro** [comment]
Hi,
You can use:
python faraday.py --login

This will update the old password
