### ISSUE TITLE
SQLMap Plugin doesn't work the desired way

### ISSUE THREAD

**Issue by Thilaknath** [infobyte/faraday#310]
## Issue Type
 - Bug

## Faraday version
C-3.2

## Component Name

If you know where the problem lays indicate it:
Faraday Client

## Steps to reproduce

1) Executing SQL Map against a vulnerable site, The finding recorded after execution are not loaded correctly in Faraday dashboard
2) I executed SQL Map against a vulnerable site and the results were recorded under log file in /root/.sqlmap/results.
3) moving the log file ~/.faraday/report/<workspace> with the plugin name in the files (Example: Sqlmap_log_Sqlmap) doesn't load the findings in faraday  dashboard.

Note: Currently in the Corporate trial we have two users 

## Expected results

The findings should be listed in the dashboard.

### OS
Windows 10 (Host OS)

Provide information on your operating system. Example:

$ cat /etc/lsb-release
DISTRIB_ID=Kali
DISTRIB_RELEASE=kali-rolling
DISTRIB_CODENAME=kali-rolling
DISTRIB_DESCRIPTION="Kali GNU/Linux Rolling"

**Comment by Ezequieltbh** [comment]
The Sqlmap plugin works differently then other plugins.
In order to use that, you need to configure some options using Faraday GTK.
Open Faraday GTK, go to “Plugins” menu, select Sqlmap and set the options required.
If that doesnt works, run the faraday gtk client in debug mode (using —debug) and paste the output here!

**Comment by Ezequieltbh** [comment]
Here you have a video with all information needed about our Sqlmap plugin...
https://www.youtube.com/watch?v=45NgXfXbaCI

**Comment by Thilaknath** [comment]
@Ezequieltbh SqlMap generates the result in a txt format and looks like faraday requires the output to be in xml format in order to be parsed, Can you advice on that?

**Comment by Ezequieltbh** [comment]
Our Sqlmap plugin doesn't work importing XML or any other format files.
In order to use Sqlmap with Faraday, you need to configure the Sqlmap path and everything should work without any problem.
This video show you the steps to achieve that.
https://www.youtube.com/watch?v=45NgXfXbaCI

**Comment by llazzaro** [comment]
There is one error in the logs:

> "/root/infobyte/faraday/plugins/controller.py", line 241, in processCommandInput modified_cmd_string = plugin.processCommandString("", pwd, cmd) File "/root/.faraday/plugins/sqlmap/plugin.py", line 627, in processCommandString self.url = self.protocol + "://" + self.hostname + ":" + int(self.port) + self.path TypeError: cannot concatenate 'str' and 'int' objects 2018-11-07 10:19:56,624 

We already fixed that issue and it will be released on v3.3.

**Comment by Thilaknath** [comment]
Thanks @llazzaro , Do you happen to know when the v3.3 will be released?

**Comment by llazzaro** [comment]
We expect to release on 14th Nov.

**Comment by Thilaknath** [comment]
@llazzaro Even with the new release, The SQLmap plugin doesn't seem to import the findings in to faraday. I see the log file containing results, But not in the dashboard. 

1) Does not work when Sqlmap is initiated from the Faraday GTK client
2) Does not work when the report is manually copied in the report/<workspace_name>/folder
3) Neither choosing the plugin and importing the result using GTK client.

**Comment by Thilaknath** [comment]
@WinnaZ  Can you take a look at this?

**Comment by Thilaknath** [comment]
Closing this issue as there is no response.

**Comment by Ezequieltbh** [comment]
Sorry for the delay.
We are going to review this issue in the next days.
I will contact you with more information soon.
Regards!

**Comment by Ezequieltbh** [comment]
@Thilaknath Hi again! 
Are you still having troubles with the Faraday plugin? because i can't reproduce your error.
Remember that you need to specify the directory of Sqlmap in Faraday GTK menu -> Plugins -> Sqlmap and use the last version of the tool.
Also, this plugin won't work importing any file (like .txt or .xml), you need to use Sqlmap inside Faraday Shell.
