### ISSUE TITLE
Failed to create vulnerability with existing name for different service_id

### ISSUE THREAD

**Issue by emcthbe** [infobyte/faraday#317]
## Issue Type
 - Bug Report

## Faraday version
Faraday v3.2

## Component Name
fplugin 

## Steps to reproduce
/usr/share/python-faraday/bin/fplugin -w toto --username faraday --password System99 create_vuln --severity low --description 'TLS Scanning' Service 665 'potentially vulnerable, uses TLS CBC ciphers'
Vuln creation result is: 1267

/usr/share/python-faraday/bin/fplugin -w toto --username faraday --password System99 create_vuln --severity low --description 'TLS Scanning' Service 663 'potentially vulnerable, uses TLS CBC ciphers'
Vuln creation result is: A vulnerability with ID 1267 already exists!

Note that when running fplugin with a different name for service_id 663, it is successful (removal of the space between comma and "uses TLS ...")

/usr/share/python-faraday/bin/fplugin -w toto --username faraday --password System99 create_vuln --severity low --description 'TLS Scanning' Service 663 'potentially vulnerable,uses TLS CBC ciphers'
1270

## Expected results
The creation of the second vulnerability with a identical name (of an existing one) for a different service_id should be successful 

### Debugging tracebacks (current results)
No output in faraday 

[requirements_freeze.txt](https://github.com/infobyte/faraday/files/2585672/requirements_freeze.txt)
logs

Please attach the result of:
pip freeze > requirements_freeze.txt

### Configuration files
No change

### OS
$ cat /etc/lsb-release
DISTRIB_ID=Kali
DISTRIB_RELEASE=kali-rolling
DISTRIB_CODENAME=kali-rolling
DISTRIB_DESCRIPTION="Kali GNU/Linux Rolling"

**Comment by lmcthbe** [comment]
Anyone available to look into it?

**Comment by Ezequieltbh** [comment]
HI @lmcthbe 
I am looking on it!
I will be more information when i have!

**Comment by lmcthbe** [comment]
Let me know when the fix will be ready or if you can provide a temporary fix, I would like to try it if possible

**Comment by WinnaZ** [comment]
I was able to reproduce the bug and i'm currently working on a solution.

**Comment by WinnaZ** [comment]
hey @emcthbe @lmcthbe,
I made some progress, this will most likely come out on our next release of Faraday (v 3.4)
Cheers!

**Comment by lmcthbe** [comment]
Thanks and when it is planned to have 3.4 ready?

**Comment by llazzaro** [comment]
Probably the 5th

**Comment by llazzaro** [comment]
We just released v3.4 with the fix on fplugin create.
Please reopen if the issue was not fixed.
Thanks!
