### ISSUE TITLE
The server is running a different Faraday version than the client you are running. Version numbers must match!

### ISSUE THREAD

**Issue by vwhissell** [infobyte/faraday#319]
git pull before
then:

` faraday.launcher - ERROR [faraday.py:437 - check_faraday_version() ]  The server is running a different Faraday version than the client you are running. Version numbers must match!`

**Comment by vwhissell** [comment]
`cat /etc/lsb-release`

```
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.3 LTS"
```

**Comment by WinnaZ** [comment]
Can you do a aux | grep faraday and make sure you didn't leave faraday running on a previous version?

**Comment by WinnaZ** [comment]
Hey @vwhissell 
thanks for reporting this issue!
We just fixed it. Do a git pull.
Cheers.
