### ISSUE TITLE
Installation on Arch

### ISSUE THREAD

**Issue by snoopythesecuritydog** [infobyte/faraday#32]
I had to do the following as well as installing the required dependencies on Arch Linux. This should be reviewed and added to the wiki, if helpful. Thanks

Install pip from github

$ wget https://raw.github.com/pypa/pip/master/contrib/get-pip.py
$ sudo python get-pip.py

I also had to install the below dependency for faraday to run
$  yaourt -S python-colorama

Note: Arch comes default with python3, If you've already installed python2, you should change the symlink to point to python2.

**Comment by f-amato** [comment]
Hi @snoopythesecuritydog thanks for contacting us and for trying Faraday!
We are going to review the Arch Linux install and update it.
Best

**Comment by mattaereal** [comment]
Hi @snoopythesecuritydog.

We encourage users installing dependencies from pacman/yaourt. There's a package for a pip installation in the extra category (extra/python2-pip). All the dependencies will be added to the AUR package as well. 

And respect the default path of python in arch, as another Arch user, I strongly recommend never modifying the symlinks. Faraday is launched using python2 from the environment (/usr/bin/env python2), so there's no need to do such thing.

Thank you very much for your feedback. Feel free to comment on any of my suggestions.

**Comment by snoopythesecuritydog** [comment]
cool. cheers for the advice :)
