### ISSUE TITLE
ZAP Report plugin

### ISSUE THREAD

**Issue by Thilaknath** [infobyte/faraday#321]
Please search the [Wiki](https://github.com/infobyte/faraday/wiki) for a solution before posting a ticket. Use the <strong>“New Support Request”</strong> button to the right of the screen to submit a ticket for technical support.

## Issue Type
 - Question

## Faraday version

-vC3.3

## Component Name

If you know where the problem lays indicate it:
Zap

Hello Team, With the new release i noticed there was a mention about a ZAP plugin to directly send reports to faraday. I don't see it available in the ZAP market place or nor there is a means in ZAP to import the plugin. Can you advise on how this is setup. There is no wiki on this topic.

**Comment by llazzaro** [comment]
Hi @Thilaknath ,

The code for the plugin is located at: https://github.com/infobyte/faraday/tree/master/plugins/repo/zap/java
You can download the binaries from the release v3.3 here https://github.com/infobyte/faraday/releases/tag/v3.3
