### ISSUE TITLE
Pagination for Command history, Last Vulnerabilities and Activity Logs

### ISSUE THREAD

**Issue by Thilaknath** [infobyte/faraday#325]
**What's the problem this feature will solve?**
Introduce pagination which will provide more information on command history 

**Describe the solution you'd like**
I would like to see the option to traverse across multiple pages for command history (i.e fetch atleast the last one weeks execution in order for users not to repeat the same tasks as done by their collaborators)

**Comment by WinnaZ** [comment]
This is actually already on the roadmap.
the command history new feature needs a few final touches.
We'll keep you posted on the progress.

**Comment by llazzaro** [comment]
This will feature will be released at v3.6!
