### ISSUE TITLE
Issues with licence

### ISSUE THREAD

**Issue by yashar6909** [infobyte/faraday#33]
I ve just got a 30 day licence for faraday which i added to the faraday download version I was giving. when I start it tells me:

2015-05-24 06:10:05,448 - faraday.launcher - ERROR - It's seems that something's wrong with your license
Please contact customer support

I have extracted the files in the directory, am not sure where I went wrong

**Comment by Annihilat0r** [comment]
How did you solve this problem?
I have 30-day license too but absolutely no idea where push it.

**Comment by f-amato** [comment]
Hi @Annihilat0r ,

You need to put the license files in the directory doc.

Hope this helps!

**Comment by Annihilat0r** [comment]
All works! Thank you!
