### ISSUE TITLE
Nessus import adds extra host-names 

### ISSUE THREAD

**Issue by daniejstriata** [infobyte/faraday#332]
Hi,

Importing from Nessus Professional 8.1.2 into Faraday 3.5 I see that the imported hosts get assigned the alphabet as extra host-names. The easiest will be to show and tell:
![image](https://user-images.githubusercontent.com/13314239/51543111-7e3d7d80-1e65-11e9-881c-a24ea4b7aedb.png)

Actual Host 
 
![image](https://user-images.githubusercontent.com/13314239/51542946-1b4be680-1e65-11e9-9611-7160e44f85e2.png)

**Comment by WinnaZ** [comment]
Would you mind sending us the nessus report that caused this?

**Comment by daniejstriata** [comment]
Sorry for the delay. I missed the request.
[External_0aumln.nessus.zip](https://github.com/infobyte/faraday/files/2889502/External_0aumln.nessus.zip)

**Comment by llazzaro** [comment]
Hi!
Thanks for the answer. We fixed this issue on v3.6.
Thanks
