### ISSUE TITLE
WARNING: Faraday administrator user already exists. Im installing on unbuntu Ubuntu 18.04.1 LTS any idea?

### ISSUE THREAD

**Issue by solrac901** [infobyte/faraday#334]
Please search the [Wiki](https://github.com/infobyte/faraday/wiki) for a solution before posting a ticket. Use the <strong>“New Support Request”</strong> button to the right of the screen to submit a ticket for technical support.

## Issue Type
 - Bug Re port
 - Feature Idea
 - Documentation Report

## Faraday version

Paste the output of the *./faraday.py --version* command

## Component Name

If you know where the problem lays indicate it:
WebGui/GTKGui/Plugin/Console/Continuous Scanning/Etc.

## Steps to reproduce

Provide detailed steps on how the issue happened so we can try to reproduce it. If the issue is random, please provide as much information as possible.

## Expected results

What did you expect to happen when following the steps above?

### Debugging tracebacks (current results)

Try to reproduce the bug with the server and/or gtk client in debug mode and check the logs for the ERROR string.
Add here any errors you find while running in debug mode or, if possible, Faraday’s log files (located at *$HOME/.faraday/logs/*).

If you need help on how to execute in debug mode [click here for more information](https://github.com/infobyte/faraday/wiki/troubleshooting).

Please attach the result of:

pip freeze > requirements_freeze.txt

### Screenshots

If you don't find anything on the logs, please provide screenshots of the error.

### Configuration files

Mention any settings you have changed/added/removed.

### Reports/Extra data

If you are having issues with plugins, please attach relevant files if possible.
(strip your reports of all sensitive information beforehand).

### OS

Provide information on your operating system. Example:

$ cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.10
DISTRIB_CODENAME=yakkety
DISTRIB_DESCRIPTION="Ubuntu 16.10"

**Comment by llazzaro** [comment]
Can you provide the steps to reproduce?

**Comment by bbirkinbine** [comment]
Have the same issue, but on CentOS7, I have a local vagrant environment that I'm playing with. 'manage.py initdb' worked in v3.4 but getting warning message below with v3.5.0.   As a side note, for CentOS7, I had to upgrade from postgres 9.2 to 9.4 (for new faraday jsonb dependency)

vagrant environment used to build is here - https://github.com/bbirkinbine/faradaysec-vagrant/tree/faraday-issue-334

- -
(faraday-python2-venv) [vagrant@faraday-server faraday-dev]$ python ./manage.py initdb
2019-01-30 14:58:33,290 - faraday-server.server.config - INFO {MainThread} [config.py:67 - copy_default_config_to_local() ]  Local faraday-server configuration created at /home/vagrant/.faraday/config/server.ini
No handlers could be found for logger "server.app"
/opt/faraday-python2-venv/lib/python2.7/site-packages/flask_sqlalchemy/__init__.py:774: UserWarning: Neither SQLALCHEMY_DATABASE_URI nor SQLALCHEMY_BINDS is set. Defaulting SQLALCHEMY_DATABASE_URI to "sqlite:///:memory:".
  'Neither SQLALCHEMY_DATABASE_URI nor SQLALCHEMY_BINDS is set. '
/opt/faraday-python2-venv/lib/python2.7/site-packages/marshmallow/schema.py:364: ChangedInMarshmallow3Warning: strict=False is not recommended. In marshmallow 3.0, schemas will always be strict. See https://marshmallow.readthedocs.io/en/latest/upgrading.html#schemas-are-always-strict
  ChangedInMarshmallow3Warning
This script will  create a new postgres user  and  save faraday-server settings (server.ini). 
Creating database faraday
Saving database credentials file in /home/vagrant/.faraday/config/server.ini
Creating tables
INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
INFO  [alembic.runtime.migration] Will assume transactional DDL.
INFO  [alembic.runtime.migration] Running stamp_revision  -> 8a10ff3926a5
**WARNING: Faraday administrator user already exists.**
- -

**Comment by llazzaro** [comment]
Hi,
python ./manage.py initdb is only executed the first time.

**Comment by llazzaro** [comment]
Hi,
the error is caused due to missing column in the insert statement.
Your pull request fixes the issue.

**Comment by llazzaro** [comment]
One workaround is to use the command:
python manage.py create-superuser

**Comment by montive** [comment]
Hi there.

Do you have any updates for this issue?

Cheers.
