### ISSUE TITLE
AttributeError when create new workspace, HTTP 500 error - Parrot Security OS

### ISSUE THREAD

**Issue by dmknght** [infobyte/faraday#339]
## Issue Type
 - Bug Report

## Faraday version

- The output of the *./faraday.py --version* command: Faraday v3.5.0
- Package version: (Parrot Security OS)
```
Package: python-faraday
Version: 3.5.0-1parrot2
```
## Component Name

GTK Gui

## Steps to reproduce
(Reinstalled db with these steps: `https://community.parrotsec.org/t/faradaysec-defautl-username-password/4091/11`)
1. Start faraday-server (postgres service has been started)
`cd /usr/share/python-faraday && python faraday-server.py`
2. Start faraday
`python faraday.py`
3. Create workspace from pop up (screenshot)
![screenshot from 2019-02-06 23-11-21](https://user-images.githubusercontent.com/29118926/52355250-97008280-2a64-11e9-9850-d0af23f55d3b.png)

## Expected results

Create workspace manually

### Debugging tracebacks (current results)

```
2019-02-06 22:56:59,657 - faraday-server.__main__ - WARNING {MainThread} [faraday-server.py:117 - check_postgresql() ]  No workspaces found. Remember to execute CouchDB importer
2019-02-06 22:56:59,668 - faraday-server.server.web - INFO {MainThread} [web.py:81 - __init__() ]  Starting web server at http://localhost:5985/
2019-02-06 22:56:59,872 - faraday-server.server.web - INFO {MainThread} [web.py:127 - __build_websockets_resource() ]  Starting websocket server at port 9000 with bind address localhost. SSL False
2019-02-06 22:56:59,874 - faraday-server.server.web - INFO {MainThread} [web.py:170 - run() ]  Faraday Server is ready
/usr/local/lib/python2.7/dist-packages/twisted/web/wsgi.py:128: UnicodeWarning: write() argument should be str, not u'[2019-02-06 22:57:46,873] ERROR in app: Exception on /v2/ws/ [POST]\nTraceback (most recent call last):\n  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1982, in wsgi_app\n    response = self.full_dispatch_request()\n  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1614, in full_dispatch_request\n    rv = self.handle_user_exception(e)\n  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1517, in handle_user_exception\n    reraise(exc_type, exc_value, tb)\n  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1612, in full_dispatch_request\n    rv = self.dispatch_request()\n  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1598, in dispatch_request\n    return self.view_functions[rule.endpoint](**req.view_args)\n  File "/usr/lib/python2.7/dist-packages/flask_classful.py", line 268, in proxy\n    response = view(**request.view_args)\n  File "/usr/lib/python2.7/dist-packages/flask_classful.py", line 239, in inner\n    return fn(*args, **kwargs)\n  File "/usr/share/python-faraday/server/api/base.py", line 602, in post\n    flask.request)\n  File "/usr/share/python-faraday/server/api/base.py", line 295, in _parse_data\n    *args, **kwargs)\n  File "/usr/local/lib/python2.7/dist-packages/webargs/core.py", line 391, in parse\n    parsed = self._parse_request(schema=schema, req=req, locations=locations)\n  File "/usr/local/lib/python2.7/dist-packages/webargs/core.py", line 314, in _parse_request\n    argname = field_obj.data_key or argname\nAttributeError: \'NullToBlankString\' object has no attribute \'data_key\'\n' (unicode)
  data, type(data).__name__), category=UnicodeWarning)
2019-02-06 22:57:46,873 - server.app - ERROR {PoolThread-twisted.internet.reactor-1} [app.py:1560 - log_exception() ]  Exception on /v2/ws/ [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/lib/python2.7/dist-packages/flask_classful.py", line 268, in proxy
    response = view(**request.view_args)
  File "/usr/lib/python2.7/dist-packages/flask_classful.py", line 239, in inner
    return fn(*args, **kwargs)
  File "/usr/share/python-faraday/server/api/base.py", line 602, in post
    flask.request)
  File "/usr/share/python-faraday/server/api/base.py", line 295, in _parse_data
    *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/webargs/core.py", line 391, in parse
    parsed = self._parse_request(schema=schema, req=req, locations=locations)
  File "/usr/local/lib/python2.7/dist-packages/webargs/core.py", line 314, in _parse_request
    argname = field_obj.data_key or argname
AttributeError: 'NullToBlankString' object has no attribute 'data_key'
```
p/s:
- I think this issue is different from #194
- Default Parrot OS's start script doesn't start faraday-server, so I started it manually

Log file: 
[faraday_log.zip](https://github.com/infobyte/faraday/files/2837158/faraday_log.zip)

The result of: 
[requirements_freeze.txt](https://github.com/infobyte/faraday/files/2837175/requirements_freeze.txt)
pip freeze > requirements_freeze.txt

### Screenshots
![screenshot from 2019-02-06 23-11-21](https://user-images.githubusercontent.com/29118926/52355352-c44d3080-2a64-11e9-867e-8a7d42b98641.png)
![screenshot from 2019-02-06 23-13-30](https://user-images.githubusercontent.com/29118926/52355413-df1fa500-2a64-11e9-9338-8d1f7197b808.png)
![screenshot from 2019-02-06 23-13-37](https://user-images.githubusercontent.com/29118926/52355414-df1fa500-2a64-11e9-983d-f4795450312d.png)
![screenshot from 2019-02-06 23-14-08](https://user-images.githubusercontent.com/29118926/52355443-eb0b6700-2a64-11e9-951c-bfb5006fa4dd.png)

### OS

```
$cat /etc/lsb-release
DISTRIB_ID=Parrot
DISTRIB_RELEASE=4.5
DISTRIB_CODENAME=stable
DISTRIB_DESCRIPTION="Parrot 4.5"
```

**Comment by llazzaro** [comment]
Hi,
We saw marshmallow==3.0.0b3 on your pip freeze.
For the moment we support marshmallow==2.15.3. You can downgrade the marshmallow version with:

`pip install marshmallow==2.15.3`

**Comment by dmknght** [comment]
Sorry for lately reply. Downgrade marshmallow worked for me. I am reporting back to Parrot Forum. Thanks!

**Comment by dmknght** [comment]
P/s: There is a issue with delete workspace, response 405, I am debugging it and create issue if I can't fix it

**Comment by alvahdati** [comment]
> Hi,
> We saw marshmallow==3.0.0b3 on your pip freeze.
> For the moment we support marshmallow==2.15.3. You can downgrade the marshmallow version with:
> 
> `pip install marshmallow==2.15.3`

Solved my problem too. thanks.

**Comment by dmknght** [comment]
@llazzaro as i see in `https://github.com/infobyte/faraday/blob/master/requirements_server.txt`, `marshmallow>=2.15.3` means newer versions of `marshmallow` library are allowed. So, if my system has `marshmallow==3.0.0b3`, `pip install requirements` process will skip by default? I am thinking changing `marshmallow>=2.15.3` to `marshmallow==2.15.3` will fix this issue during installation process. Can you test it, please?

**Comment by baadie** [comment]
pip install marshmallow==2.15.3 solved my problem too!

**Comment by dmknght** [comment]
New update: I've installed fresh Parrot 4.5.1. I didn't have this error this time. my marshmallow version
```
Name: marshmallow
Version: 3.0.0b3
```
Everything i did was run `sudo python-faraday`. For Parrot Sec OS, i am thinking this problem is about creating database with permission (running `python-faraday` only gonna use current user permission with `uid=1000`).

**Comment by dmknght** [comment]
> @dmknght did you get the same error?
> 
> Faraday only works with marshmallow 2.15.3, we will publish a non-stable branch for marshmallow 3 soon

No. Not at all. That is so strange. There is only error when i tried to delete workspace (i forgot create issue).

**Comment by llazzaro** [comment]
We have a known on issue when you try to delete workspace that have some data in it.
If a vulnerability has a policy violation the workspace delete will throw a 500 error. However there are another situations where you can get the error 500.
Checkout the log on ~/.faraday/logs and search for "ERROR".
Feel free to open an issue on the workspace delete error.
We are very close to release v3.7 soon!
