### ISSUE TITLE
Bug Report: Cannot import Lynis reports of FreeBSD hosts - UnboundLocalError

### ISSUE THREAD

**Issue by daniejstriata** [infobyte/faraday#343]
Bug Report

## Faraday version
Faraday v3.5.0

## Component Name
Lynis Plugin

## Steps to reproduce
When I import a Lynis 2.7.1 report of Linux devices it succeeds with no error. When I import any Lynis 2.7.1 report for a FreeBSD host I get an crash error in debug mode. 

## Expected results
Be able to import Lynis report for FreeBSD host.

### Debugging tracebacks (current results)
 INFO ]- 2019-02-15 11:50:26,215 - faraday.ReportProcessor - The file is /home/danie.dejager/Downloads/server-lynis-log/LYN1550222308-lynis-report.log, Lynis
[ DEBUG ]- 2019-02-15 11:50:26,326 - faraday.PluginController - Created plugin_process (140580864438416) for plugin instance (140581603380304)
[ DEBUG ]- 2019-02-15 11:50:26,327 - faraday - ----------------------------------------
[ DEBUG ]- 2019-02-15 11:50:26,327 - faraday - proc_name = Thread-23
[ DEBUG ]- 2019-02-15 11:50:26,327 - faraday - Starting run method on PluginProcess
[ DEBUG ]- 2019-02-15 11:50:26,327 - faraday - parent process: 27859
[ DEBUG ]- 2019-02-15 11:50:26,327 - faraday - process id: 23374
[ DEBUG ]- 2019-02-15 11:50:26,328 - faraday - ----------------------------------------
[ DEBUG ]- 2019-02-15 11:50:26,328 - faraday - Thread-23: New Output
[ DEBUG ]- 2019-02-15 11:50:26,331 - faraday - Plugin raised an exception:
[ DEBUG ]- 2019-02-15 11:50:26,331 - faraday - _processAction - 3000 - parameters = ['Lynis', 165]
[ INFO ]- 2019-02-15 11:50:26,333 - faraday.ModelController - Plugin Started: Lynis. 
[ DEBUG ]- 2019-02-15 11:50:26,333 - faraday - Traceback (most recent call last):
  File "/home/user/Tools/faraday/plugins/plugin.py", line 407, in run
    self.plugin.processOutput(output)
  File "/home/user/Tools/faraday/plugins/plugin.py", line 134, in processOutput
    self.parseOutputString(output)
  File "/home/user/.faraday/plugins/lynis/plugin.py", line 236, in parseOutputString
    services = lde.listeningservices()
  File "/home/user/.faraday/plugins/lynis/plugin.py", line 106, in listeningservices
    elements = self.clean_services(combo, local_services)
  File "/home/user/.faraday/plugins/lynis/plugin.py", line 148, in clean_services
    ip, port = self.colon_count(count, elements_ip_port, items_service)
  File "/home/user/.faraday/plugins/lynis/plugin.py", line 189, in colon_count
    return ip, port
UnboundLocalError: local variable 'ip' referenced before assignment

If you need help on how to execute in debug mode [click here for more information](https://github.com/infobyte/faraday/wiki/troubleshooting).

Please attach the result of:
[requirements_freeze.txt](https://github.com/infobyte/faraday/files/2868725/requirements_freeze.txt)

### Screenshots
![image](https://user-images.githubusercontent.com/13314239/52849145-05a2a780-3119-11e9-9a74-0d639b06f627.png)

### Configuration files
Standard

 Setup.
### Reports/Extra data
[LYN1550222308-lynis-report.log](https://github.com/infobyte/faraday/files/2868768/LYN1550222308-lynis-report.log)

### OS

Provide information on your operating system. Example:

$ cat /etc/lsb-release
DISTRIB_ID=LinuxMint
DISTRIB_RELEASE=18.3
DISTRIB_CODENAME=sylvia
DISTRIB_DESCRIPTION="Linux Mint 18.3 Sylvia"

**Comment by montive** [comment]
Hi there.

Sorry for this issue. We will work on it. 
By the way, thanks for the report! It will be very helpful.

Regards.

**Comment by daniejstriata** [comment]
Great! Let me know if you need a working host's report too.

**Comment by montive** [comment]
Hi. 

If you can provide it, it would be great! This way we can be sure that the plugin is working well.

Regards.

**Comment by llazzaro** [comment]
Hi,
The fix for this issue was released with v3.6.
Please reopen this issue if the problem was not fixed.
Thanks!
