### ISSUE TITLE
Change Wiki - Plugin name

### ISSUE THREAD

**Issue by sangnu** [infobyte/faraday#346]
https://github.com/infobyte/faraday/wiki/Plugin-List

+Change 'Linys' by: 'Lynis'.

BR, Sng.

**Comment by montive** [comment]
Hi. 
Thanks for the feedback!

**Comment by llazzaro** [comment]
Empty results with the typo, closing!
```
faraday.wiki(master✔) ]
 $ grep -nr 'Linys' *                                    
```
