### ISSUE TITLE
failed building wheel for filteralchemy-fork

### ISSUE THREAD

**Issue by Kasperait** [infobyte/faraday#348]
When installing (pip2 install -r requirements_server.txt -U) comes out error (failed building wheel for filteralchemy-fork) and (not cleaning build dir for filteralchemy-fork)
I’ve also written this at the beginning (DEPRECATION: Python 2.7 will be saved after that date. A future version of pip will drop  support for Python 2.7.) In the middle is (Generating metadata for filteralchemy package for filatralchemy-forks. Fix your # egg = filteralchemy fragments.
 )

Screenshot : 
![Screenshot_4](https://user-images.githubusercontent.com/42416467/55687276-d881b100-5973-11e9-8a04-4fe524c0a9fd.png)

P.S :Sorry for the translation (I don't know English)

**Comment by llazzaro** [comment]
Hi,

We made an update on our filteralchemy-fork.
Could you retry the install step?

Thanks!

**Comment by Kasperait** [comment]
Yes, thanks, it worked.

**Comment by llazzaro** [comment]
Great! Closing
