### ISSUE TITLE
How to restart the server

### ISSUE THREAD

**Issue by yuuiki** [infobyte/faraday#349]
Hi, I install faraday on Ubuntu and I want to access the server from my pc, so I edit the server.ini
and set the bind_address param to 0.0.0.0,and then Restart the Ubuntu.

But it did not work. could you pls tell me how can I solve this isuue? 

[faraday-server]
...
bind_address=0.0.0.0

![image](https://user-images.githubusercontent.com/29880212/56031727-d2fce000-5d52-11e9-9a41-052cc07a829c.png)

**Comment by WinnaZ** [comment]
After changing the configuration file, did you restart the server?
keep in mind the section that says [couchdb] is deprecated. The actual config is under the label [faraday_server].
Let us know how it goes, cheers.

**Comment by llazzaro** [comment]
You can always use:

```
faraday-server.py --restart
```
