### ISSUE TITLE
Reporting

### ISSUE THREAD

**Issue by yashar6909** [infobyte/faraday#35]
When creating a report after adding the acunetix XML, it goes into 'processing' and hangs for hours. I ve checked that I have all the dependencies and everything advised by your wiki, how can I remediate that problem?

**Comment by f-amato** [comment]
Hi @yashar6909,
Thanks for trying Faraday!
Could you please run faraday using -d flag and copy again the report.
Please send us the faraday console output and the xml so we can reproduce the issue.
Best

**Comment by f-amato** [comment]
Hi @yashar6909  do you have feedback about this issue?
Best

**Comment by yashar6909** [comment]
No sorry,

I just uninstalled it. Gave me too many issues.
Thanks for chasing it up

Yashar

**Comment by f-amato** [comment]
Ok, It was a pity that you does not give the opportunity to fix the bugs, We didn't received any feedback just "not working" 
Best
