### ISSUE TITLE
Nmap auto completion script not working

### ISSUE THREAD

**Issue by neomh** [infobyte/faraday#351]
## Issue Type
 - Bug 
## Steps to reproduce
nmap --script XXXX <tab>
###OS
Kali Linux 4.17.0 kali1 686

The tab option to autocomplete doesn't work inside of Faraday's shell.
Is there any windows to link auto completion scripts to Faraday's shell ?

The scripts reside at /usr/share/bash-completion/completions

Thank you for your help

**Comment by WinnaZ** [comment]
Autocomplete does work on faradays shell. 
Keep in mind is a zsh terminal with extra config. Not a bash terminal.
Cheers
