### ISSUE TITLE
Missing binary module at server start

### ISSUE THREAD

**Issue by garbopujol** [infobyte/faraday#355]
**New Support Request**

## Issue Type
 - Bug Re port
 Traceback (most recent call last):
  File "manage.py", line 27, in <module>
    from server.importer import ImportCouchDB
  File "/usr/share/python-faraday/server/importer.py", line 35, in <module>
    from passlib.utils.binary import ab64_encode
ImportError: No module named binary
dpkg: error processing package python-faraday (--configure):
 installed python-faraday package post-installation script subprocess returned error exit status 1
Errors were encountered while processing:
 python-faraday
E: Sub-process /usr/bin/dpkg returned an error code (1)

## Faraday version

Faraday v3.7.0

### Debugging tracebacks (current results)

faraday.log 
2019-04-24 12:04:36,021 - faraday.launcher - INFO [faraday.py:408 -          printBanner() ]  Starting Faraday IDE.
2019-04-24 12:04:36,022 - faraday.launcher - INFO [faraday.py:359 -   checkConfiguration() ]  Checking configuration.
2019-04-24 12:04:36,022 - faraday.launcher - INFO [faraday.py:360 -   checkConfiguration() ]  Setting up plugins.
2019-04-24 12:04:36,022 - faraday.launcher - INFO [faraday.py:294 -         setupPlugins() ]  Removing old plugins folder.
2019-04-24 12:04:36,283 - faraday.launcher - INFO [faraday.py:362 -   checkConfiguration() ]  Setting up ZSH integration.
2019-04-24 12:04:36,283 - faraday.launcher - INFO [faraday.py:364 -   checkConfiguration() ]  Setting up user configuration.
2019-04-24 12:04:36,284 - faraday.launcher - INFO [faraday.py:332 -       setupXMLConfig() ]  Copying default configuration from project.
2019-04-24 12:04:36,314 - faraday.launcher - INFO [faraday.py:366 -   checkConfiguration() ]  Setting up icons for GTK interface.
2019-04-24 12:04:36,327 - faraday.launcher - INFO [faraday.py:218 -              setConf() ]  Setting configuration.
2019-04-24 13:22:18,179 - faraday.launcher - INFO [faraday.py:408 -          printBanner() ]  Starting Faraday IDE.
2019-04-24 13:22:18,205 - faraday.launcher - INFO [faraday.py:359 -   checkConfiguration() ]  Checking configuration.
2019-04-24 13:22:18,206 - faraday.launcher - INFO [faraday.py:360 -   checkConfiguration() ]  Setting up plugins.
2019-04-24 13:22:18,206 - faraday.launcher - INFO [faraday.py:294 -         setupPlugins() ]  Removing old plugins folder.
2019-04-24 13:22:24,824 - faraday.launcher - INFO [faraday.py:362 -   checkConfiguration() ]  Setting up ZSH integration.
2019-04-24 13:22:24,924 - faraday.launcher - INFO [faraday.py:364 -   checkConfiguration() ]  Setting up user configuration.
2019-04-24 13:22:24,924 - faraday.launcher - INFO [faraday.py:339 -       setupXMLConfig() ]  Using custom user configuration.
2019-04-24 13:22:24,924 - faraday.launcher - INFO [faraday.py:366 -   checkConfiguration() ]  Setting up icons for GTK interface.
2019-04-24 13:22:26,253 - faraday.launcher - INFO [faraday.py:218 -              setConf() ]  Setting configuration.

pip freeze > requirements_freeze.txt
pip freeze
Warning: cannot find svn location for chirp===daily-20190104
adns-python==1.2.1
alembic==1.0.9
appdirs==1.4.3
aprslib==0.6.46
argcomplete==1.8.1
argh==0.26.2
asn1crypto==0.24.0
atomicwrites==1.3.0
attrs==19.1.0
autobahn==19.3.3
Automat==0.6.0
Babel==2.6.0
backports-abc==0.5
backports.csv==1.0.7
backports.functools-lru-cache==1.5
backports.shutil-get-terminal-size==1.0.0
backports.ssl-match-hostname==3.5.0.1
BBQSQL==1.0
bcrypt==3.1.6
bdfproxy==0.0.0
beautifulsoup4==4.7.1
BlindElephant==1.0
blinker==1.4
bottle==0.12.15
brotlipy==0.6.0
bs4==0.0.1
capstone==4.0.0
cbor==1.0.0
certifi==2019.3.9
cffi==1.11.5
cfscrape==1.9.5
Chameleon==2.24
chardet==3.0.4
CherryTree==0.38.8
## FIXME: could not find svn URL in dependency_links for this package:
chirp===daily-20190104
cli-helpers==1.2.0
Click==7.0
colorama==0.4.1
config==0.4.0
ConfigArgParse==0.11.0
configobj==5.0.6
configparser==3.7.4
constantly==15.1.0
construct==2.5.3
cryptography==2.6.1
cssselect==1.0.3
cssutils==1.0.2
cycler==0.10.0
Cython==0.29.2
decorator==4.3.0
defusedxml==0.5.0
deprecation==2.0.6
dhcpig==0.0.0
dicttoxml==1.7.4
distorm3==3.4.1
Django==1.11.20
dnslib==0.9.7
dnspython==1.16.0
docker==3.6.0
docker-pycreds==0.4.0
docutils==0.14
easygui==0.96
EditorConfig==0.12.1
Elixir==0.7.1
entrypoints==0.3
enum34==1.1.6
et-xmlfile==1.0.1
feedparser==5.2.1
filedepot==0.6.0
filteralchemy==0.1.0
flake8==3.7.7
Flask==1.0.2
Flask-BabelEx==0.9.3
Flask-Classful==0.14.2
Flask-Cors==3.0.7
Flask-Login==0.4.1
Flask-Mail==0.9.1
Flask-Principal==0.4.0
Flask-Restless==0.17.0
Flask-Security==3.0.0
Flask-Session==0.3.1
Flask-SQLAlchemy==2.3.2
Flask-WTF==0.14.2
FormEncode==1.3.0
funcsigs==1.0.2
functools32==3.2.3.post2
fuse-python==0.3.1
future==0.17.1
futures==3.2.0
GDAL==2.4.0
GeoIP==1.3.2
gevent==1.3.7
gpg==1.12.0
greenlet==0.4.15
h2==2.4.4
hpack==2.3.0
html2text==2016.9.19
html5lib==1.0.1
httplib2==0.11.3
humanize==0.5.1
hupper==1.5
hyperframe==4.0.2
hyperlink==17.3.1
idna==2.8
impacket==0.9.18
incremental==16.10.1
ipaddress==1.0.17
IPy==1.0
ipython==5.8.0
ipython-genutils==0.2.0
isc-dhcp-leases==0.9.1
itsdangerous==1.1.0
jdcal==1.0
Jinja2==2.10.1
jsbeautifier==1.6.4
jsonpickle==0.9.5
jsonrpclib==0.1.7
keyring==17.1.1
keyrings.alt==3.1.1
killerbee==1.0
kiwisolver==1.0.1
ldap3==2.5.1
libarchive-c==2.1
lxml==3.6.0
lz4==1.1.0
M2Crypto==0.31.0
Mako==1.0.7
MarkupSafe==1.1.1
marshmallow==3.0.0b3
marshmallow-sqlalchemy==0.16.2
matplotlib==2.2.3
mccabe==0.6.1
mechanize==0.2.5
mercurial==4.8.2
metaconfig==0.1.4a1
mimerender==0.6.0
mitmproxy==0.18.2
mockito==1.1.1
more-itertools==5.0.0
msgpack==0.5.6
mysqlclient==1.3.10
netaddr==0.7.19
NetfilterQueue==0.8.1
netifaces==0.10.9
networkx==2.2
NfSpy==1.0
nplusone==1.0.0
numpy==1.16.2
oauthlib==2.1.0
odfpy==1.4.0
olefile==0.46
openpyxl==2.4.9
osrframework==0.18.8
packaging==19.0
paramiko==2.4.2
passlib==1.6.5
Paste==3.0.6
PasteDeploy==2.0.1
PasteScript==2.0.2
pathlib2==2.3.3
pathtools==0.1.2
pcapy==0.10.8
peepdf==0.4.2
pefile==2018.8.8
pexpect==4.6.0
pgcli==2.1.0
pgspecial==1.11.5
pickleshare==0.7.5
Pillow==6.0.0
plaster==1.0
plaster-pastedeploy==0.5
pluggy==0.9.0
prettytable==0.7.2
prompt-toolkit==2.0.9
psycopg2==2.7.7
psycopg2-binary==2.8.2
py==1.8.0
py-ubjson==0.12.0
pyasn1==0.4.5
pyasn1-modules==0.2.5
pycairo==1.16.2
pycodestyle==2.5.0
pycparser==2.19
pycrypto==2.6.1
pycryptodomex==3.6.1
pycurl==7.43.0.2
pydns==2.3.6
pydot==1.4.1
pyenchant==2.0.0
pyexcel==0.2.1
pyexcel-io==0.2.0
pyexcel-ods==0.1.0
pyexcel-text==0.2.0
pyexcel-xls==0.2.0
pyexcel-xlsx==0.2.0
pyflakes==2.1.1
Pygments==2.3.1
PyGObject==3.30.4
pygraphviz==1.5
pygtkspellcheck==4.0.5
PyHamcrest==1.9.0
pyinotify==0.9.6
PyJWT==1.7.0
pymongo==3.7.1
pymssql==2.1.4
PyNaCl==1.3.0
pyOpenSSL==19.0.0
pyparsing==2.4.0
PyPDF2==1.26.0
pyperclip==1.5.32
pyquery==1.2.9
pyramid==1.10.2
pyrit==0.5.1
pyscard==1.9.7
pyserial==3.4
PySocks==1.6.8
pysqlite==2.7.0
pytest==4.4.1
pytest-flake8==1.0.4
python-dateutil==2.8.0
python-editor==1.0.3
python-emailahoy==0.0.6
python-Levenshtein==0.12.0
python-magic==0.4.6
python-mimeparse==0.1.4
python-openid==2.2.5
python-slugify==3.0.2
python-snappy==0.5.3
pythonaes==1.0
PyTrie==0.2
pytz==2019.1
pyusb==1.0.2
PyV8==1.0.dev0
PyX==0.12.1
pyxdg==0.25
PyYAML==3.13
qrcode==6.1
repoze.lru==0.7
requests==2.21.0
requests-oauthlib==1.0.0
rfidiot==1.0
roman==2.0.0
ruamel.ordereddict==0.4.13
ruamel.yaml==0.15.94
scandir==1.10.0
scapy==2.4.0
scapy-http==1.8.2
scgi==1.13
scipy==1.1.0
SecretStorage==2.3.1
selenium==3.141.0
service-identity==18.1.0
setproctitle==1.1.10
simplegeneric==0.8.1
simplejson==3.16.0
singledispatch==3.4.0.3
sipvicious==0.2.8
six==1.12.0
slowaes==0.1a1
soupsieve==1.8
speaklater==1.3
SQLAlchemy==1.3.3
sqlalchemy-schemadisplay==1.3
sqlparse==0.2.4
subprocess32==3.5.3
tabulate==0.8.2
tcpwatch==1.3.1
Tempita==0.5.2
termcolor==1.1.0
terminaltables==3.1.0
text-unidecode==1.2
texttable==1.6.0
tornado==5.1.1
tqdm==4.31.1
traitlets==4.3.2
translationstring==1.3
trollius==2.0.1
tweepy==3.6.0
Twisted==19.2.0
txaio==18.8.1
typing==3.6.6
u-msgpack-python==2.1
unicodecsv==0.14.1
Unidecode==1.0.23
urllib3==1.24.2
urwid==1.3.1
uTidylib==0.5
venusian==1.2.0
vext==0.7.3
vinetto==0.7b0
volatility==2.6
w3af-api-client==1.1.7
waitress==1.2.0b2
watchdog==0.8.3
wcwidth==0.1.7
webargs==5.3.0
webencodings==0.5.1
WebOb==1.8.5
websocket-client==0.56.0
WebTest==2.0.32
webunit==1.3.10
Werkzeug==0.15.2
whois==0.7
Whoosh==2.7.4
wifite==2.2.5
wsaccel==0.6.2
WTForms==2.2.1
wxPython==3.0.2.0
wxPython-common==3.0.2.0
xlrd==1.1.0
XlsxWriter==1.1.2
xlwt==1.3.0
xmlbuilder==1.0
yara-python==3.9.0
zenmap==7.70
zim==0.68
zope.component==4.3.0
zope.deprecation==4.4.0
zope.event==4.2.0
zope.hookable==4.0.4
zope.interface==4.6.0

/etc/lsb-release
DISTRIB_ID=Kali
DISTRIB_RELEASE=kali-rolling
DISTRIB_CODENAME=kali-rolling
DISTRIB_DESCRIPTION="Kali GNU/Linux Rolling"

**Comment by montive** [comment]
Hi there.

What command did you run??

Regards.

**Comment by ekiojp** [comment]
garbopujol 

You should be using `passlib==1.7.1` instead `passlib==1.6.5`

Version 1.7.x function name is `passlib.utils.binary.ab64_encode` (Used in Faraday)
Version 1.6.x function name is `passlib.utils.ab64_decode` hence the error you get about no binary module

Try with `pip install passlib -U` and then check is version 1.7.1
```
root@kali:~# pip freeze | grep passlib
passlib==1.7.1
root@kali:~# 
```
