### ISSUE TITLE
How to change the default interface (localhost) of the web server ?

### ISSUE THREAD

**Issue by NRGLine4Sec** [infobyte/faraday#356]
there is no documentation to explain how to change the default interface (localhost) of the web server to an external IP

**Comment by llazzaro** [comment]
Hi!
Check here this wiki page: https://github.com/infobyte/faraday/wiki/FAQ#how-do-i-bind-faraday-to-0000

The server also supportes the following parameters:

* --bind 
* --port

Example usage

faraday-server --bind 0.0.0.0 --port 9000

Please reopen this issue if this was not the correct solution.

Thanks!
