### ISSUE TITLE
[Wiki/doc] multiple issues

### ISSUE THREAD

**Issue by noraj** [infobyte/faraday#358]
Multiples wiki issues.

## Typos

- [x]  https://github.com/infobyte/faraday/wiki/Executive-Report#using-markdown-on-a-report: -lenguage +language

## Bad links

- [x]  https://github.com/infobyte/faraday/wiki/Executive-Report#requirements: https://github.com/infobyte/faraday/wiki/first-steps, the nedpoint `first-steps` doesn't exist anymore.

## Images

- [x]  https://github.com/infobyte/faraday/wiki#getting-started: the image contains the logo of ArchAssault, but the project has been [transferred](https://inventory.rawsec.ml/operating_systems.html#title-operating-systems-project-transferred) to BlackArch Linux, so the logo need to be updated

## Logical

On https://github.com/infobyte/faraday/wiki/Installation-Community#downloading it is said:

> Download the latest tarball or clone the Faraday Git Project repository and checkout the dev branch:
>
> ```
> $ git clone https://github.com/infobyte/faraday.git faraday-dev
> $ cd faraday-dev
> ```
- [x] But doing that you are on the master branch. So an extra `git checkout dev` is required.
- [x] On https://github.com/infobyte/faraday/wiki/Installation-Guide#installation-from-git-repo, replace `git@github.com:infobyte/faraday.git` with `https://github.com/infobyte/faraday.git` because users don't have ssh access.
- [x] Step missing `source faraday_venv/bin/activate`
  ```
  # create a virtualenv (optional)
  pip install virtualenv
  virtualenv -p python2 faraday_venv
  pip install git+git@github.com:infobyte/faraday.git
  ```
- [x] Step missing `cd faraday` and `source faraday_venv/bin/activate`
  ```
  git clone git@github.com:infobyte/faraday.git
  # create a virtualenv (optional)
  pip install virtualenv
  virtualenv -p python2 faraday_venv
  python setup.py install
  ```

## Documentation tool

- [x] Using a dedicated website for the documentation with a markdown powered static website generator such as [docusaurus](https://docusaurus.io/), [MkDocs](https://www.mkdocs.org/), [couscous](http://couscous.io) rather than the github wiki, would allow you to host the doc on a website and also accepts PR.

## Deprecated

- [x] On https://github.com/infobyte/faraday/wiki/Installation-Community#initializing-postgresql you say `python2 manage.py initdb` but:
  ```
  From Faraday v3.8 onwards, running ./manage.py doesn't work anymore. You should run faraday-manage instead.
  
  This allows users to put the faraday-manage script in any directory (like /usr/local/bin) and to run it from anywhere, with no need of switching to the Faraday directory.
  ```
  So update it to `faraday-manage initdb`.

## Add info

- [x] On https://github.com/infobyte/faraday/wiki/Installation-Community, it not clear when referring to python if it is python 2 or 3. But as there is later a title `Installing Python 2 dependencies` I wish it is python 2. So can you explicitly write it.  
 - [x] Here are the steps for `Installing system dependencies` for `ArchLinux`
  ```
  # pacman -Syu
  # pacman -S base-devel ipython python2-setuptools python2-pip openssl libffi libxml2 libxslt libpng freetype2 postgresql
  ```
- [x] Also there is a community [BlackArch](https://www.blackarch.org/) package: https://github.com/BlackArch/blackarch/blob/master/packages/faraday/PKGBUILD
- [x] This page (Installation Community) is referenced on the README but does't no figure on the wiki sidebar.
- [x] For ArchLinux add a link to PostgreSQL installation and initial configuration https://wiki.archlinux.org/index.php/PostgreSQL#Installation
- [x] On https://github.com/infobyte/faraday/wiki/vulnerabilities-database#manual-import in the context of `Go to the Web UI and click on the import icon` also say to go on the `Vulnerability templates` page

**Comment by montive** [comment]
Hi. Thanks so much for your feedback. 

We will consider your suggestions.

Kind regards.

**Comment by llazzaro** [comment]
Hi!
We have updated most of your observations. We are planning to move to mkdocs in the future.
Thanks!!

**Comment by EricHorvat** [comment]
Hi there! @DobleV55 has been checking and updating the changed listed. We are actually moving to mkdocs, but can confrm a date yet.

Thank you for your observations and feel free to open a new issue!
