### ISSUE TITLE
Credential list page show plain password

### ISSUE THREAD

**Issue by royoan** [infobyte/faraday#360]
**What's the problem this feature will solve?**
The password couldn't show as a plain text

**Describe the solution you'd like**
all credential information is secret, may be show  "****" on the page

**Comment by royoan** [comment]
![credentail](https://user-images.githubusercontent.com/5915563/58942406-47328d80-87b0-11e9-83e4-261ff3c77a3d.jpg)

**Comment by montive** [comment]
Hi there.

Thanks for your report. We will consider it.

Regards.
