### ISSUE TITLE
[Question] data cwe

### ISSUE THREAD

**Issue by noraj** [infobyte/faraday#364]
In [`/data/`](https://github.com/infobyte/faraday/tree/master/data) there are `cwe.csv  cwe_en.csv  cwe_es.csv  fix_severities.py`.

What is the difference between `cwe_es.csv` and `cwe.csv`? Because they are both in spanish but with few differences.

Also why is there a script `fix_severities.py` in `/data/`? It should be placed somewhere else.

**Comment by montive** [comment]
Hi there.

* `cwe.csv`: contains vulnerabilities in **english** and **spanish**
* `cwe_en.csv`: contains vulnerabilities only in **english**
* `cwe_es.csv`: contains vulnerabilities only in **spanish**

About the script `fix_severities.py`:

- This script takes a .csv file and changes the severities names inside this .csv so it won't have any trouble during the importation process. E.g: if you have a severity named _med_, this might fail when you import the file into Faraday so this script will change this name to _medium_. This way, it won't fail.
