### ISSUE TITLE
Question: Can status report list page show custom field?

### ISSUE THREAD

**Issue by royoan** [infobyte/faraday#365]
**What's the problem this feature will solve?**
When I add a new custom field, and I want it show on the **status report** page. but I can't find it when I click the "**Add columns**" button. 
Further more, I want filter the vuls when enter keywords in the search input box.

**Describe the solution you'd like**

I want add some custom field, but **Status Report" page can't show on the list page. 
If the **Add columns** button can list the custom field, it's perfect.
And the search input box need support the field filter.

**Alternative Solutions**

**Additional context**

**Comment by montive** [comment]
Hi there.
Custom Fields are not available as a column in Status Report.
We will take a look to see if it is possible to add it.
Regards.

**Comment by royoan** [comment]
thank you
