### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by rhertzog** [infobyte/faraday#368]
As you know Python 2 will no longer be supported in 2020 and Faraday should aim to work with Python 3.

I know that you are already working on this but I wanted this to be officially tracked in some place so that I can be notified when the Python 3 port is over.

In Debian, developers are removing Python 2 modules and this already affects faraday in Kali because the "deprecation" module is no longer available for Python 2. We will keep the old package for now but the need to port to Python 3 is thus getting very concrete now.

**Comment by cript0nauta** [comment]
Hi! The migration to python 3 will be our main priority after the release of 3.9, that should be in a few weeks. As you said, we already started the migration process by properly packaging Faraday with a setup.py file, which was necessary to make absolute imports work.

We still have a lot of work to do to fully port it, but we'll do the best to have this ready for 2020.

We'll keep this issue open until the port is over.

Greetings!

**Comment by cript0nauta** [comment]
Hi again! Just wanted to give a status update about this. Today we relased Faraday 3.9 (or 3.9.2 to be precise). This is supposed to be the last version using Python 2.

The 3.10 version (there is no release date yet) will only support Python 3. We have an experimental py3 branch with all tests passing and the Web UI working pretty well. However there are some edge cases and features that break with Python 3. We will work full-time on addressing them.

Greetings!

**Comment by cript0nauta** [comment]
Status update: I recently pushed the `python3` branch of the project which supports Python 3 pretty well. After finishing testing it and fixing a few things with the .deb and .rpm generators, we will merge it to master and release v3.10.

**Comment by jloehel** [comment]
@cript0nauta The `w3af-api-client` does not support python3 right now. There is a pending PR from 2018 andresriancho/w3af-api-client#4 but no action so far. Will you drop the support for the w3af plugin in 3.10?

**Comment by cript0nauta** [comment]
Python 3 is already supported in `w3af-api-client` since https://github.com/andresriancho/w3af-api-client/pull/7 was merged. I asked the maintainer to bump a new version so we can upgrade the requirements file and test the w3af plugin.

@jloehel thanks for implementing Python 3 support for the library!

**Comment by llazzaro** [comment]
@cript0nauta I think we can close this issue!

**Comment by cript0nauta** [comment]
@llazzaro indeed we can! @jloehel the w3af plugin is working ok with Python 3.

Closing since version 3.10 is already released and supports Python 3.

Happy holidays, new year and the last 12 days of Python 2 support!
