### ISSUE TITLE
[Plugin request] IP's service information from Shodan

### ISSUE THREAD

**Issue by leitosama** [infobyte/faraday#369]
**What's the problem this feature will solve?**
OSINT scan with shodan.io for services with IP list from faraday workspace.

**Describe the solution you'd like**
A script or plugin to automaticly request ```https://api.shodan.io/shodan/host/{addr}?key={api_key}``` API call from shodan with service information. It will be good for recon stage when you want to be silent.

**Comment by llazzaro** [comment]
Hi,
we are going to create an [agent executor ](https://github.com/infobyte/faraday_agent_dispatcher)with this feature.

**Comment by ezk06eer** [comment]
the agent executor is released: [agent executor](https://github.com/infobyte/faraday_agent_dispatcher/tree/master/faraday_agent_dispatcher/static/executors/dev)
