### ISSUE TITLE
Unable to login through web UI

### ISSUE THREAD

**Issue by b0rked** [infobyte/faraday#370]
Ubuntu 16.04.6 LTS
Faraday 3.8.0

After successfully creating the tables (remote postgres) and starting the server, im unable to login through the UI.

faraday-manage create-tables

```
Creating tables
INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
INFO  [alembic.runtime.migration] Will assume transactional DDL.
Tables created successfully!
```

`systemctl start faraday-server`

I've tried username: faraday, password: changeme
Along with 

faraday-manage change-password
```
Username: faraday
Password:
Repeat for confirmation:
User not found in Faraday's Database
```

`faraday> select * from faraday_user`
Yields 0 entries.

What am i missing? It seems like the installation instructions for the remote postgres setup arent complete.

**Comment by b0rked** [comment]
Post installation of the .deb file it says the path of `server.ini` should be `/home/faraday/.faraday/server.ini` - this is incorrect (the installation documentation on github is actually correct).

Once the tables have been created, one has to create the actual superuser through faraday-manage - this is not documented anywhere.

**Comment by llazzaro** [comment]
Hello @b0rked,

We are going to update the install message.
Once the install finishes a random password is created for the "faraday" super-user.

I will reopen and close when we merge the updated message.

**Comment by llazzaro** [comment]
We have updated the path in post install message of the .deb file.
Thanks for reporting this issue
