### ISSUE TITLE
Incorrect instructions post .deb installation

### ISSUE THREAD

**Issue by b0rked** [infobyte/faraday#371]
Version: 3.8.0 `https://github.com/infobyte/faraday/releases/download/v3.8.0/faraday-server-community_amd64.deb`

Post installation of the 3.8.0 .deb file the instructions are incorrect:
```
* Install Postgresql > 9.5 locally or in a remote server.
* If you are going to use postgresql locally:
  ** Create faraday database an tables running 'faraday-manage initdb' as root
* If you are going to use postgresql remotely:
  **  Configure [database] section on /home/faraday/.faraday/server.ini with correct postgresql string. Ex:
      [database] 
      postgresql+psycopg2://faraday_postgresql:PASSWORD@localhost/faraday 
  *** Run faraday-manage create-tables
```

Expected:
The path of server.ini for remote postgresql should be ` /home/faraday/.faraday/config/server.ini`

**Comment by llazzaro** [comment]
Hi,
We have rewritten the install documentation in this wiki page:
https://github.com/infobyte/faraday/wiki/Remote-PostgreSQL-database-configuration

Thank you for reporting this issue.
