### ISSUE TITLE
[Idea] Add description field for open ports in each host

### ISSUE THREAD

**Issue by dmknght** [infobyte/faraday#372]
**What's the problem this feature will solve?**
- I want to use Faraday IDE fully in pentesting so i don't have to do everything manually so much
- I want to add extra information for an open port that faraday doesn't add it automatically
- I want to take note / explain something for myself and read it later
- I don't have to use both editor and faraday to save my data (cherrytree for example)

**Describe the solution you'd like**
- Add a new field that users can add their own note information. In GUI mode, it should has `Add description` button after I click on open port
- It could support extra syntax instead of purge text editor only (and color highlight maybe)

**Alternative Solutions**

**Additional context**

**Comment by cript0nauta** [comment]
Hi @dmknght! Although we don't have this feature in our GTK client, it is possible to do that via the Web Interface. Click on a host to see its services, then select the target service and click on the edit button. You should see a modal like this one:

![output](https://user-images.githubusercontent.com/1222362/66422477-1ffaff80-e9e0-11e9-8bd5-171ff6670309.png)

from it you can change the description of your services.

Let us know if this solves your problem!

**Comment by dmknght** [comment]
Thanks for your support but is there a chance to have description feature in gtk client? You know, in community edition, gtk client can run commands and do everything so edit description in gtk gui will be easier

**Comment by fedek** [comment]
The GTK interface has been deprecated. Closing this issue for clean-up, thanks for the feedback!
