### ISSUE TITLE
creating a new workspace

### ISSUE THREAD

**Issue by pastaoficial** [infobyte/faraday#376]
what wave dogs?

I was using faraday and had a bad UX, in the dashboard I didn't have workspaces yet, so faraday put the following link:
![image](https://user-images.githubusercontent.com/18431519/68684989-297c0800-0548-11ea-8efd-55c7b48f12b6.png)

when I press "create a new one" I want to open automatically the form, but open this:
![image](https://user-images.githubusercontent.com/18431519/68685283-a7d8aa00-0548-11ea-98fa-c608868dd3b4.png)

and now I need to press "New".... NO NO NO, I want my form there

**Comment by llazzaro** [comment]
Hi @pastaoficial ,

We will try to improve this workflow in future versions. I like the idea to reduce the number of clicks.

Regards,
Leonardo

**Comment by llazzaro** [comment]
Hi @pastaoficial,

In our latest release we improved the UX for workspaces.
Checkout v3.11

Good luck dog!
