### ISSUE TITLE
Can not find the plugins on 3.9.3

### ISSUE THREAD

**Issue by e101sg** [infobyte/faraday#379]
[#](url) Issue Type
 - Bug Re port : Can not find Plugin 3.9.3 after i have updated Kali linux to latest  version 
**Linux kali 5.3.0-kali3-amd64 #1 SMP Debian 5.3.15-1kali1 (2019-12-09) x86_64 GNU/Linux**
I can not see the plugins on the top from Faraday terminal. 
_Screen shot_ Link_

https://1drv.ms/u/s!AgQa8i37A0sihJBQNhk7Vwf23GJUEQ?e=e5Cifg

Please advise. am i missing something. Thanks.

**Comment by e101sg** [comment]
Is it a bug?

**Comment by llazzaro** [comment]
Hi!
You have to click on the folder icon to select the plugin or execute any command at the terminal to use the plugins.

![Screenshot from 2019-12-27 10-40-48](https://user-images.githubusercontent.com/568181/71549605-00e88a00-299f-11ea-8c83-dd915be0e6b8.jpeg)

We recommend to use the webui to upload the files from tools.

**Comment by llazzaro** [comment]
I'm closing this issue. If you still have problems, please feel free to reopen this issue.
Thanks!

**Comment by e101sg** [comment]
Please update me if i miss anything. Every time, i click, a window opens, ask to import a report (path). Strange right? For example, for arp scan command, earlier this is not behavior. Correct me if i am wrong. Thanks.

**Comment by llazzaro** [comment]
Hi,
For commands you can use the terminal. For tools that export data in xml or other formats you can select the file.
