### ISSUE TITLE
AppScan support request

### ISSUE THREAD

**Issue by retbandit** [infobyte/faraday#38]
Please support importing AppScan results- thanks!

**Comment by f-amato** [comment]
Hi @lockandski,
Thanks for trying Faraday. We are going to add your request for the interactions list to work on.
Best

**Comment by whitehatandy** [comment]
I second that! One of my clients is considering purchasing Faraday, but their primary scanner is Appscan. Until it supports that, they can't really use it.

**Comment by f-amato** [comment]
Good news! @retbandit @whitehatandy The AppScan plugin was added last version! Give a try an let us know if you like it!
Regards!
