### ISSUE TITLE
Module not found marshmallow.compat

### ISSUE THREAD

**Issue by cixafo** [infobyte/faraday#382]
I'm upgrading my debian with apt and when metasploit package is upgrading, it through an error in faraday as

Setting up faraday (3.10.2-0kali1) ...
Traceback (most recent call last):
File "/usr/bin/faraday-manage", line 11, in
load_entry_point('faradaysec==3.10.2', 'console_scripts', 'faraday-manage')()
File "/usr/lib/python3/dist-packages/pkg_resources/init.py", line 489, in load_entry_point
return get_distribution(dist).load_entry_point(group, name)
File "/usr/lib/python3/dist-packages/pkg_resources/init.py", line 2852, in load_entry_point
return ep.load()
File "/usr/lib/python3/dist-packages/pkg_resources/init.py", line 2443, in load
return self.resolve()
File "/usr/lib/python3/dist-packages/pkg_resources/init.py", line 2449, in resolve
module = import(self.module_name, fromlist=['name'], level=0)
File "/usr/lib/python3/dist-packages/faraday/manage.py", line 43, in
from faraday.server.commands.faraday_schema_display import DatabaseSchema
File "/usr/lib/python3/dist-packages/faraday/server/commands/faraday_schema_display.py", line 17, in
from faraday.server import models
File "/usr/lib/python3/dist-packages/faraday/server/models.py", line 46, in
from faraday.server.fields import FaradayUploadedFile, JSONType
File "/usr/lib/python3/dist-packages/faraday/server/fields.py", line 20, in
from webargs.core import ValidationError
File "/usr/lib/python3/dist-packages/webargs/init.py", line 7, in
from webargs.core import dict2schema, ValidationError
File "/usr/lib/python3/dist-packages/webargs/core.py", line 23, in
from marshmallow.compat import iteritems
ModuleNotFoundError: No module named 'marshmallow.compat'
dpkg: error processing package faraday (--configure):
installed faraday package post-installation script subprocess returned error exit status 1
dpkg: dependency problems prevent configuration of python-faraday:
python-faraday depends on faraday; however:
Package faraday is not configured yet.

dpkg: error processing package python-faraday (--configure):
dependency problems - leaving unconfigured
Errors were encountered while processing:
faraday
python-faraday
needrestart is being skipped since dpkg has failed
Scanning application launchers
Updating active launchers
Done
E: Sub-process /usr/bin/dpkg returned an error code (1)

I've tried installing marshmallow with pip but it shows requirement satisfies and still throw the error.

**Comment by cixafo** [comment]
Now I tried this and the error changes

sudo python3 -m pip install faradaysec

Here is the new error.

Setting up faraday (3.10.2-0kali1) ...
Traceback (most recent call last):
  File "/usr/bin/faraday-manage", line 11, in <module>
    load_entry_point('faradaysec==3.10.2', 'console_scripts', 'faraday-manage')()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2852, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2443, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
ModuleNotFoundError: No module named 'faraday.manage'
dpkg: error processing package faraday (--configure):
 installed faraday package post-installation script subprocess returned error exit status 1
dpkg: dependency problems prevent configuration of python-faraday:
 python-faraday depends on faraday; however:
  Package faraday is not configured yet.

dpkg: error processing package python-faraday (--configure):
 dependency problems - leaving unconfigured
Errors were encountered while processing:
 faraday
 python-faraday
needrestart is being skipped since dpkg has failed
Scanning application launchers
Updating active launchers
Done
E: Sub-process /usr/bin/dpkg returned an error code (1)

**Comment by cript0nauta** [comment]
Hi @cixafo! If you're trying to run Faraday in Kali and it's not working properly, you can try using the `.deb` files we upload in each release: https://github.com/infobyte/faraday/releases/tag/v3.10.2. These should work in any Debian-based distro, including Kali.

Be sure to remove the `faraday` and `python-faraday` Kali packages before installing these new .deb's.

**Comment by cixafo** [comment]
I have to install both client and server?

**Comment by cixafo** [comment]
I just do the following and my linux got weird, it's desktop environment changes and most of the functionalities get removed.

sudo dpkg -r python-faraday
sudo dpkg -r faraday
sudo apt purge --auto-remove python-faraday
sudo apt purge python-faraday faraday
sudo apt remove python-faraday faraday

Please help me to roll it back... I'm stuck. Please...

**Comment by cript0nauta** [comment]
@cixafo installing just the server deb is ok. The client is already included in it so you can use it by running `/opt/faraday/bin/faraday-client` with the Faraday Server already up (you can run `systemctl start faraday-server` for this).

**Comment by cixafo** [comment]
no no...
I'm stuck.. I've run the above commands and everything is messed up...
please help me... I've my placement drive in a week and my pc is like crashed or something...
most of the functionalities dissappear

**Comment by cript0nauta** [comment]
This seems to be a problem with the Kali distribution. We are not the maintainers of `python-faraday` nor `faraday` Kali packages, as this is done entirely by the Kali package maintainers instead.

We recommend you to contact the Kali maintainers, as I'm aware system upgrades usually cause system errors in Kali (often not related to Faraday).

I'm sorry we can't help you with this issue.
