### ISSUE TITLE
Vulns Report History Request

### ISSUE THREAD

**Issue by skarfaze** [infobyte/faraday#387]
Hello,

If I upload several reports of the same target (for example from Nessus) done in different months, I can't see the evolution of the vulnerabilities in time. It would be very interesting to have that option.

Kind regards.

**Comment by llazzaro** [comment]
Hi!

We added support to use the scan date instead of the imported date for some plugins. In particular we added support for nessus.

This feature will be included in v3.11, that will be released next week.

Thanks!
