### ISSUE TITLE
Qualysguard xml report not importing 

### ISSUE THREAD

**Issue by adnanmig** [infobyte/faraday#389]
I have a Qualys Web Application Scan report which I am trying to import through Web UI, once I click onupload, nothing gets added.

## Issue Type
 - Bug Report

## Faraday version
Faraday v3.10.2

## Component Name

If you know where the problem lays indicate it:
File Upload function

## Steps to reproduce
1- Create a workspace
2- Navigate to Manage>Vulns
3- Click Upload a report and select qualysgaurd web application scan generated report (xml)
4- Click upload file

## Expected results

Vulnerability information in dashboard

### Debugging tracebacks (current results)

Try to reproduce the bug with the server and/or gtk client in debug mode and check the logs for the ERROR string.
[ INFO ]- 2020-03-31 15:42:40,856 - faraday.client.managers.reports_managers - The file is /home/user/Downloads/qualys20200331_faraday_Qualysguard.xml, qualysguard
[ INFO ]- 2020-03-31 15:42:40,903 - faraday.client.plugins.controller - Processing report with plugin qualysguard
[ INFO ]- 2020-03-31 15:42:40,909 - faraday.client.plugins.controller - Created plugin_process (139671340570256) for plugin instance (139671815929808)
[ DEBUG ]- 2020-03-31 15:42:40,909 - faraday.client.model.api - _processAction - 3000 - parameters = ['Qualysguard', 8]
[ INFO ]- 2020-03-31 15:42:40,910 - faraday.client.model.controller - Plugin Started: Qualysguard. 
[ DEBUG ]- 2020-03-31 15:42:40,910 - faraday.client.model.api - ----------------------------------------
[ DEBUG ]- 2020-03-31 15:42:40,910 - faraday.client.model.api - proc_name = PluginProcessThread
[ DEBUG ]- 2020-03-31 15:42:40,910 - faraday.client.model.api - Starting run method on PluginProcess
[ DEBUG ]- 2020-03-31 15:42:40,911 - faraday.client.model.api - parent process: 12219
[ DEBUG ]- 2020-03-31 15:42:40,911 - faraday.client.model.api - process id: 12245
[ DEBUG ]- 2020-03-31 15:42:40,911 - faraday.client.model.api - ----------------------------------------
[ DEBUG ]- 2020-03-31 15:42:40,911 - faraday.client.model.api - PluginProcessThread: New Output
[ INFO ]- 2020-03-31 15:42:40,914 - faraday.client.plugins.controller - Plugin end. Commiting to faraday server.
[ DEBUG ]- 2020-03-31 15:42:40,922 - faraday.client.model.api - _processAction - 3001 - parameters = ['Qualysguard', 8]
[ INFO ]- 2020-03-31 15:42:40,922 - faraday.client.model.controller - Plugin Ended: Qualysguard

Please attach the result of:

pip freeze > requirements_freeze.txt

====
user@ubuntu:~/.faraday/logs$ ls
faraday-server.log  requirements_freeze.txt
user@ubuntu:~/.faraday/logs$ cat requirements_freeze.txt
asn1crypto==0.24.0
certifi==2018.1.18
chardet==3.0.4
command-not-found==0.3
cryptography==2.1.4
distro-info===0.18ubuntu0.18.04.1
idna==2.6
keyring==10.6.0
keyrings.alt==3.0
language-selector==0.1
netifaces==0.10.4
pycrypto==2.6.1
pygobject==3.26.1
python-apt==1.6.5+ubuntu0.2
pyxdg==0.25
PyYAML==3.12
requests==2.18.4
SecretStorage==2.3.1
six==1.11.0
ssh-import-id==5.7
ufw==0.36
unattended-upgrades==0.1
urllib3==1.22
user@ubuntu:~/.faraday/logs$
====

If you don't find anything on the logs, please provide screenshots of the error.

### OS

Provide information on your operating system. Example:

user@ubuntu:~/.faraday/logs$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.4 LTS
Release:        18.04
Codename:       bionic

**Comment by llazzaro** [comment]
Hi,
I'm closing this issue, feel free to reopen if you have any problems with the latest version.

Thanks!
