### ISSUE TITLE
API question

### ISSUE THREAD

**Issue by s0i37** [infobyte/faraday#391]
Hello.
Why I can't iterate for each host/service/vuln?
```
for host in models.get_hosts(workspace):
  for service in host.getServices():
    for vuln in service.getVulns():
      ...
```
`host.getServices()` returns all services instead of services of current host.
And the same for `service.getVulns()`.
Is it normally?

**Comment by llazzaro** [comment]
Hi,

We can confirm that host.getServices() is returning all services, we created an internal dev ticket to fix this bug.
We will let you know when this bug is fixed.

Regards,
Leonardo

**Comment by llazzaro** [comment]
Hi!

We have moved the client to https://github.com/infobyte/faraday-client.

The fix was done here https://github.com/infobyte/faraday-client/commit/54d9a3d115878dbf1cb6c7fc76ab39be69d74f2d#diff-7d898baf64dfa67a036e7e6e558ed90c

Thanks!
