### ISSUE TITLE
Error While importing Zap Add-on plugin

### ISSUE THREAD

**Issue by Yashvendra** [infobyte/faraday#392]
Hi All,

I wanted to integrate Faradayv3.3 with Zaproxyv2.9.0. 
I downloaded the **zap-plugin.zap** file from [here](https://github.com/infobyte/faraday/releases/tag/v3.3).
It throws an error when I import this Add-on which you can see in the logs, screenshot attached.

![Screenshot_2020-04-10_06-53-21](https://user-images.githubusercontent.com/23001311/78987901-5afbfe00-7afd-11ea-91ea-211eb2125c84.png)

Can someone share his/her thoughts on this issue, is the plugin broken?

**Comment by thc202** [comment]
It's relying on a library that's no longer bundled in core, needs to be changed to include it.

**Comment by Yashvendra** [comment]
I see in the latest [release](https://github.com/infobyte/faraday/releases), @llazzaro has mentioned that ZAP plugin has been updated. Will check it and give the updates.

**Comment by llazzaro** [comment]
@Yashvendra We updated the XML plugin, the new ZAP add-on was not released in this version.

**Comment by llazzaro** [comment]
Hi @Yashvendra @thc202 ,

we have released a new version with the fix: https://github.com/infobyte/faraday/releases/download/v3.11.1/faraday-release-1_1.zap

Regards,
