### ISSUE TITLE
The client can't connect to faraday sever

### ISSUE THREAD

**Issue by tXambe** [infobyte/faraday#398]
Hello,

I has installed faraday-server downloaded the packet .deb and was installed with dpkg, the interface is up and I can login without problem ( http://localhost:5985) but with http://192.168.200.1:5985 don't work, unable to connect.
I have install nginx but I think I'm missing some configuration, ¿Anyone can help me?

Thanks and a greeting

**Comment by dnadares** [comment]
Hi tXambe,

Could you please check the bind_address param in your server.ini configuration. By default faraday-server listens on ```localhost``` only. To make it listen on all interfaces you should change it with ```bind_address = 0.0.0.0```

Regards,

Diego

**Comment by tXambe** [comment]
Hello,

Thanks for your response, and it's already working, I only have configure faraday-server to access from internet, yesterday I've been setting up in my home rooter at NAT but don't work, I'll keep researching how to do it.

**Comment by EricHorvat** [comment]
Hi tXambe,

We recommend to set faraday-server behind a reverse proxy. We can suggest [NGINX](https://github.com/infobyte/faraday/wiki/NGINX-Setup) as one of them. 

Regards,

Eric

**Comment by tXambe** [comment]
Hello,

I follow the manual of nginx but don't work 

I follow the manual of github to access , but nginx don’t work, when type systemctl start I have this error:

    May 07 12:34:04 Fara nginx[1464]: nginx: [emerg] “user” directive is not allowed here in /etc/nginx/sites-enabled/faraex:1
    May 07 12:46:06 Fara nginx[1550]: nginx: [emerg] “worker_processes” directive is not allowed here in /etc/nginx/sites-enabled/faraex:2
    -May 07 12:47:09 Fara nginx[1561]: nginx: [emerg] “pid” directive is not allowed here in /etc/nginx/sites-enabled/faraex:3

-May 07 12:47:52 Fara nginx[1577]: nginx: [emerg] “load_module” directive is not allowed here in /etc/nginx/modules-enabled/50-mod-http-auth-pam.conf:1

Inside of 50-mod-http-auth-pam.conf I have this:

load_module modules/ngx_http_auth_pam_module.so;

Can I help me a litte more, thanks very much

**Comment by tXambe** [comment]
Hello,

I follow the manual of nginx but I don't understand what file I have what modify so that when I write the url https://myfaraday.com go to the panel login of faraday server

Thanks very much and a greeting

**Comment by EricHorvat** [comment]
Hi tXambe,

First make sure you already set up Nginx and that you are able to see the default page when you go to localhost:80 on your browser.

Once you have that, modify /etc/nginx/nginx.conf and create /etc/nginx/sites-available/faraday. Note that you have to modify this latter file to include your own server name (for example, `localhost` or `myfaraday`). These are the files referenced in our wiki. The last step is to soft-link /etc/nginx/sites-available/faraday to /etc/nginx/sites-enabled/faraday, by e.g. `ln -s /etc/nginx/sites-available/faraday/etc/sites-enabled/` ).

After that, restart nginx (systemctl restart nginx) and veryfy that if you go to 'localhost' on your browser, you see the login page. Once that works, it's a matter of how you access the machine from the LAN or the internet. I strongly recommend to first test on your LAN and make sure you understand how name resolving works before exposing it to the internet.

Regards,

Eric

**Comment by tXambe** [comment]
> that you have to modify this latter file to include your o

Hello,

My current situation:

If write http://localhost --> nginx Bad request The plain HTTP request was sent to HTTPS port
If write http://localhost:5985 --> login panel
If write https://localhost --> unable to connect
If write https://172.16.100.23 --> unable to connect

Should I copy the content of nginx.conf in /etc/nginx/sites-available/faraday ?

**Comment by EricHorvat** [comment]
Hi tXambe,

Great, you achive to run it with SSL. In the other hand name resolution is DNS and OS task, I recommend [this link](https://en.wikipedia.org/wiki/Name_resolution_(computer_systems)) to start investigating name resolution.

Let us know of any other issue. 

Issue closed

**Comment by tXambe** [comment]
> Hi tXambe,
> 
> Great, you achived to run it with SSL. In the other hand name resolution is DNS and OS task, I recommend [this link](https://en.wikipedia.org/wiki/Name_resolution_(computer_systems)) to start investigating name resolution.
> 
> Let us know of any other issue.
> 
> Issue closed

Hello,
But if I don't understand one thing, in my router I have port mirroring of my public IP at my private IP ( faraday-server) with port 5985 , so when write https://83.175.200.98 don't work if I write https://83.175.200.98:5985 don't work, ¿so i should use a service like freedns, dydns?

Thanks very much

**Comment by llazzaro** [comment]
@tXambe I think you need to do port forwarding with your router, since it seems faraday run in an internal IP 172.16.100.23 .

**Comment by tXambe** [comment]
> @tXambe I think you need to do port forwarding with your router, since it seems faraday run in an internal IP 172.16.100.23 .

Yes , I has done port mirroring from my IP public at my IP internal but don't work
