### ISSUE TITLE
FIX: Kali Linux 2020: faraday-server error: No module named 'marshmallow.compat'

### ISSUE THREAD

**Issue by llazzaro** [infobyte/faraday#399]
We are working on fixing this error on Kali Linux ASAP.

In this issue, we will provide information on how to fix `faraday-server` not starting with the error  **No module named 'marshmallow.compat'**. 
If faraday is not working in Kali Linux, please check the following steps.
This guide will help you to use faraday temporarily until we update marshmallow to the latest version.

We are going to use this issue to provide information about the update. Feel free to ask any questions about Faraday in kali here.

1. First, uninstall `faraday` package and update/upgrade your packages

```
sudo apt remove faraday
sudo apt-get update
sudo apt-get upgrade
```

2. Download .deb package from our GitHub repo

Download our [latest version v3.11  from here](https://github.com/infobyte/faraday/releases/download/v3.11/faraday-server_amd64.deb)

SHA256 Sum: `b7b1db8be062d49fa4daee1b4b7b86587b0027ea3594f1bf2a9b7c5c91c3f96c`

```
sudo apt install ./faraday-server_amd64.deb
```

3. Start the server

After our package is installed a new service will be added to your systemd.

```
sudo service faraday-server start
```

Note: for first-time use, you need to execute `faraday-manage initdb`

You can check the status with:

```
sudo service faraday-server status
```

Make sure you execute `faraday-manage status-check` to ensure that everything is working:

<img width="502" alt="Screen Shot 2020-05-07 at 10 28 41 PM" src="https://user-images.githubusercontent.com/568181/81360427-29e9fb80-90b2-11ea-9ab8-50d5447cd278.png">

**Comment by cyrus104** [comment]
I followed the instructions above but running into another issues where apt won't install Faraday manually due to other packages that are installed by default.

The following packages have unmet dependencies:
 kali-linux-default : Depends: faraday but it is not installable
E: Error, pkgProblemResolver::Resolve generated breaks, this may be caused by held packages.

**Comment by epsilon-mahlil** [comment]
Awesome, thank you.
