### ISSUE TITLE
unmet dependencies in kali linux

### ISSUE THREAD

**Issue by hansaja** [infobyte/faraday#403]
**### I was trying to install tilix but got errors**

udo apt-get install tilix
Reading package lists... Done
Building dependency tree       
Reading state information... Done

Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 gsettings-desktop-schemas : Breaks: mutter (< 3.31.4) but 3.30.2-7 is to be installed
E: Error, pkgProblemResolver::Resolve generated breaks, this may be caused by held packages.

**Comment by jayswalnayan1999** [comment]
i have same problem but i can't find any solution if you find plz tell me brother

**Comment by llazzaro** [comment]
Hi!

Can you provide the command that triggered the error?

Thanks!

**Comment by hansaja** [comment]
> Hi!
> 
> Can you provide the command that triggered the error?
> 
> Thanks!

Hey llazzaro I installed kali linux 20.3 the latest (currently) and tried installing tilix and it worked

**Comment by hansaja** [comment]
> i have same problem but i can't find any solution if you find plz tell me brother

Only  solution is to install the latest kali linux edition

This error came 2019 version and i upgraded to 2020 latest version
