### ISSUE TITLE
Password Reset for End Users

### ISSUE THREAD

**Issue by z3-al** [infobyte/faraday#404]
**What's the problem this feature will solve?**
Allowing users to reset their own password using the Faraday web interface front-end. Not only will this reduce admin overhead, this allows a more secure workflow of setting up first-time users. Currently, the user has to be given their password, which inevitably involves some form of password sharing. With password reset functionality, a user could set their own password and reduce the risks resulting from password sharing. 

**Describe the solution you'd like**
It would be great if the login UI interface of Faraday provided this functionality. Ideally, user accounts would be tied to email addresses with this design. To reset their password, a user could then enter this email address into the password reset functionality, which would generate a secure password reset link allowing them to access a password reset page. 

**Alternative Solutions**
Alternative methods to that described above may be insecure, and as such the above may be the only acceptable solution.

**Comment by fedek** [comment]
Thank you @z3-al for your feedback. The `Forgot password` feature is currently in our roadmap and we hope to release it in the near future. 

Thanks

**Comment by fedek** [comment]
The Forgot Password feature has been added ins previous releases. Thanks for the feedback. Closing the issue during clean-up.
