### ISSUE TITLE
500 error using API

### ISSUE THREAD

**Issue by l0ft1369** [infobyte/faraday#405]
Please search the [Wiki](https://github.com/infobyte/faraday/wiki) for a solution before posting a ticket. Use the <strong>“New Support Request”</strong> button to the right of the screen to submit a ticket for technical support.

## Issue Type
 - Bug Report (I think?) Honestly - this could be a real me thing here. Not gonna try and lie about that. 

## Faraday version

Paste the output of the *./faraday.py --version* command

Faraday v3.11

I used faraday-server -v to get that result

## Component Name

If you know where the problem lays indicate it:
WebGui/GTKGui/Plugin/Console/Continuous Scanning/Etc.

I believe it's the WebSockets API? I am seeing 500 errors when I try and use the shodan python example, but I am also seeing 500 errors when I launch the client. 

## Steps to reproduce

Provide detailed steps on how the issue happened so we can try to reproduce it. If the issue is random, please provide as much information as possible.

1.) Launch the Server -> sudo faraday-server --debug
2.) Launch the client -> sudo faraday-client (I know using sudo for everything is not great....the night was late and mistakes were made)
3.) Check console output of the server:
2020-08-19T11:49:20-0500 - faraday.server.app - ERROR {PoolThread-twisted.internet.reactor-3} [app.py:1975 - finalize_request()]  Request finalizing failed with an error while handling an error
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/flask/app.py", line 2446, in wsgi_app
    ctx.push()
  File "/usr/lib/python3.8/site-packages/flask/ctx.py", line 390, in push
    self.session = session_interface.open_session(self.app, self.request)
  File "/usr/lib/python3.8/site-packages/flask_kvsession/__init__.py", line 155, in open_session
    s = self.session_class(self.serialization_method.loads(
EOFError: Ran out of input

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/flask/app.py", line 1970, in finalize_request
    response = self.process_response(response)
  File "/usr/lib/python3.8/site-packages/flask/app.py", line 2267, in process_response
    response = handler(response)
  File "/usr/lib/python3.8/site-packages/flask_login/login_manager.py", line 399, in _update_remember_cookie
    if '_remember' not in session and \
  File "/usr/lib/python3.8/site-packages/werkzeug/local.py", line 379, in <lambda>
    __contains__ = lambda x, i: i in x._get_current_object()
TypeError: argument of type 'NoneType' is not iterable
2020-08-19T11:49:20-0500 - faraday.server.websocket_factories - DEBUG {MainThread} [websocket_factories.py:238 - join_workspace()]  Join workspace chinasecure
2020-08-19T11:49:20-0500 - faraday.server.websocket_factories - DEBUG {MainThread} [websocket_factories.py:240 - join_workspace()]  registered client tcp4:127.0.0.1:36778

## Expected results

What did you expect to happen when following the steps above?

to not get 500 and Out of Input errors

### Debugging tracebacks (current results)

Try to reproduce the bug with the server and/or gtk client in debug mode and check the logs for the ERROR string.
Add here any errors you find while running in debug mode or, if possible, Faraday’s log files (located at *$HOME/.faraday/logs/*).

2020-08-19T11:49:20-0500 - faraday.server.app - ERROR {PoolThread-twisted.internet.reactor-3} [app.py:1975 - finalize_request()]  Request finalizing failed with an error while handling an error
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/flask/app.py", line 2446, in wsgi_app
    ctx.push()
  File "/usr/lib/python3.8/site-packages/flask/ctx.py", line 390, in push
    self.session = session_interface.open_session(self.app, self.request)
  File "/usr/lib/python3.8/site-packages/flask_kvsession/__init__.py", line 155, in open_session
    s = self.session_class(self.serialization_method.loads(
EOFError: Ran out of input

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/flask/app.py", line 1970, in finalize_request
    response = self.process_response(response)
  File "/usr/lib/python3.8/site-packages/flask/app.py", line 2267, in process_response
    response = handler(response)
  File "/usr/lib/python3.8/site-packages/flask_login/login_manager.py", line 399, in _update_remember_cookie
    if '_remember' not in session and \
  File "/usr/lib/python3.8/site-packages/werkzeug/local.py", line 379, in <lambda>
    __contains__ = lambda x, i: i in x._get_current_object()
TypeError: argument of type 'NoneType' is not iterable
2020-08-19T11:49:20-0500 - faraday.server.websocket_factories - DEBUG {MainThread} [websocket_factories.py:238 - join_workspace()]  Join workspace chinasecure
2020-08-19T11:49:20-0500 - faraday.server.websocket_factories - DEBUG {MainThread} [websocket_factories.py:240 - join_workspace()]  registered client tcp4:127.0.0.1:36778

020-08-19T11:49:20-0500 - faraday_client.persistence.server.changes_stream - INFO {background_process} [changes_stream.py:113 - __init__()]  Connecting to websocket url ws://localhost:9000/
2020-08-19T11:49:20-0500 - faraday_client.Server-GTK IO - WARNING {background_process} [decorators.py:24 - wrapper()]  Couldn't get a valid response from the server when requesting to URL http://localhost:5985/_api/v2/ws/chinasecure and function <function get at 0x7fc0898b13a0>. Response was <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>500 Internal Server Error</title>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.</p>

Server output is first then the client output is next

If you need help on how to execute in debug mode [click here for more information](https://github.com/infobyte/faraday/wiki/troubleshooting).

Please attach the result of:

pip freeze > requirements_freeze.txt

acme==1.7.0
adal==1.2.4
adblockparser==0.7
aenum==2.2.4
ailment==8.20.7.27
aiocmd==0.1.5
aiodns==2.0.0
aiodnsbrute==0.3.2
aiohttp==3.6.2
aiohttp-socks==0.4.2
aiohttp-xmlrpc==0.8.1
aiomultiprocess==0.8.0
aiorun==2020.6.1
aiosqlite==0.15.0
aiowinreg==0.0.3
airdrop-ng==1.1
airgraph-ng==1.1
ajpy==0.0.5
alabaster==0.7.12
alembic==1.4.2
amoco==2.9.4
amqp==2.6.1
ana==0.6
androguard==3.4.0a1
angr==8.20.7.27
angr-management==8.20.7.6
angrop==8.20.7.27
aniso8601==8.0.0
ansi2html==1.5.2
antlerinator==4.8
antlr4-python3-runtime==4.8
anyascii==0.1.6
anyjson==0.3.3
anytree==2.8.0
apipkg==1.5
apispec==3.3.1
apispec-webframeworks==0.5.2
apkid==2.1.0
apparmor==2.13.4
appdirs==1.4.4
APScheduler==3.6.3
archinfo==8.20.7.27
archiveis==0.0.9
argcomplete==1.11.1
argh==0.26.2
arpreq==0.3.3
arrow==0.15.8
arybo==1.1.0
asciitree==0.3.3
asgiref==3.2.10
asn1crypto==1.4.0
astroid==2.4.2
async-timeout==3.0.1
asyncio==3.4.3
asysocks==0.0.3
atom==0.5.2
atomicwrites==1.4.0
attrs==19.3.0
autobahn==20.7.1
Automat==20.2.0
autopep8==1.5.4
autopwn==2.0.0
awscli==1.18.120
aztarna==1.2.1
azure-common==1.1.25
azure-mgmt-storage==11.1.0
Babel==2.8.0
backcall==0.2.0
backports.csv==1.0.7
backports.shutil-get-terminal-size==1.0.0
bandicoot==0.5.3
bashfuscator==0.0.1
bcrypt==3.2.0
Beaker==1.11.0
beautifulsoup4==4.9.1
beautifultable==1.0.0
billiard==3.6.3.0
binaryornot==0.4.4
bintrees==2.1.0
binwalk==2.2.0
biplist==1.0.3
biscuits==0.2.1
bitarray==1.5.1
bitstring==3.1.7
bleach==3.1.5
blessed==1.17.8
blessings==1.7
blinker==1.4
booby-ng==0.8.4
boto==2.49.0
boto3==1.14.43
botocore==1.17.43
bottle==0.12.18
branca==0.4.1
Brotli==1.0.7
brotlipy==0.7.0
brute==5.0
bs4==0.0.1
btlejack==2.0.0
btrfsutil==1.2.0
bump2version==0.5.11
buster==1.0.0
CacheControl==0.12.6
cached-property==1.5.1
cachetools==4.1.1
cairocffi==1.1.0
CANToolz==3.7.0
capfuzz==0.0.1
capstone==4.0.2
case==1.5.3
cchardet==2.1.6
celery==4.4.7
cement==2.10.12
censys==0.0.8
ceph-volume==1.0.0
cephfs==2.0.0
cephfs-shell==0.0.1
Cerberus==1.3.2
certbot==1.7.0
certbot-dns-cloudflare==1.7.0
certifi==2020.6.20
cffi==1.14.2
cfscrape==2.1.1
chardet==3.0.4
checksumdir==1.2.0
cheroot==8.4.4
CherryPy==18.6.0
chiasm-shell==1.0.0a9
chipsec==1.5.3
claripy==8.20.7.27
cle==8.20.7.27
cli-helpers==2.1.0
click==7.1.2
click-log==0.3.2
click-plugins==1.1.1
click-shell==2.0
clint==0.5.1
cloudflare==2.8.13
cmd2==1.3.3
cmsmap==1.0
codecov==2.1.8
colorama==0.4.3
colorclass==2.2.0
colored==1.4.2
coloredlogs==14.0
colorlog==4.1.0
colour==0.1.5
commandparse==1.0.8
commonmark==0.9.1
ConfigArgParse==1.2.3
configobj==5.0.6
conpot==0.6.0
consolemd==0.5.1
constantly==15.1.0
contextlib2==0.6.0.post1
cookiecutter==1.7.2
cookiejar==0.0.3
cooldict==1.4
CouchDB==1.2
coverage==4.5.4
coveralls==2.0.0
cpppo==4.0.6
crackmapexec==5.1.0.dev0
crayons==0.3.1
crc16==0.1.1
crccheck==0.6
crcelk==1.3
cryptography==3.0
crysp==1.1
crytic-compile==0.1.8
cssselect==1.1.0
cursor==1.3.4
cx-Oracle==7.3.0
cybox==2.1.0.17
cycler==0.10.0
cymruwhois==1.6
Cython==0.29.21
cytoolz==0.10.1
ddt==1.4.1
decorator==4.4.2
deen==2.1.0
defang==0.5.3
defusedxml==0.6.0
delegator.py==0.1.1
demjson==2.2.4
Deprecated==1.2.10
deprecation==2.1.0
detectem==0.7.3
dhcplib==0.1.1
dicttoxml==1.7.4
dirhunt==0.7.0
distlib==0.3.1
distro==1.5.0
dizzy==2.0
Django==3.1
django-extensions==3.0.5
django-rest-framework==0.1.0
django-tables2==2.3.1
dlib==19.21.0
dnsdiag==1.7.0
dnsdumpster==0.5
dnslib==0.9.14
dnspython==1.16.0
dnstwist==20200707
doc2dash==2.3.0
docker==4.3.0
docker-pycreds==0.4.0
dockerscan==1.0.0a4
docopt==0.6.2
docutils==0.16
domain-stats==0.0.7
dorkbot==0.2.3+git
dpkt==1.9.3
droopescan==1.43.0
dropbox==10.3.0
drupwn==1.0.3
ds-store==1.1.2
dukpy==0.3
easygui==0.98.0
EasyInject==0.3
EasyProcess==0.3
ecdsa==0.15
editdistance==0.5.3
EditorConfig==0.12.2
elasticsearch==7.8.1
email-validator==1.1.1
enaml==0.11.2
enlighten==1.6.1
enteletaor==1.1.1
entrypoints==0.3
enum-compat==0.0.3
esprima==4.0.1
et-xmlfile==1.0.1
eth-hash==0.2.0
eth-typing==2.2.1
eth-utils==1.9.3
event-bus==1.0.2
eventlet==0.26.1
evillimiter==1.5.0
exabgp==4.2.6
execnet==1.7.1
ExifRead==2.1.2
exrex==0.10.6
face-recognition==1.3.0
face-recognition-models==0.3.0
facebook-sdk==3.1.0
factordb-pycli==1.2.0
factory-boy==3.0.1
fake-useragent==0.1.11
Faker==4.1.2
faraday-client==1.0.0
faraday-plugins==1.2.3
faradaysec==3.11
feedparser==5.2.1
fierce==1.4.0
file-magic==0.4.0
filebytes==0.10.2
filedepot==0.8.0
filelock==3.0.12
filemagic==1.6
filequeue==0.4.1
filteralchemy-fork==0.1.0
first==2.0.2
flake8==3.7.8
flasgger==0.9.5
Flask==1.1.2
Flask-API==2.0
Flask-APScheduler==1.11.0
Flask-BabelEx==0.9.4
Flask-Classful==0.14.2
Flask-Classy==0.6.10
Flask-Compress==1.5.0
Flask-HTTPAuth==3.3.0
Flask-KVSession-fork==0.6.3
Flask-Login==0.5.0
Flask-Mail==0.9.1
flask-mongoengine==0.9.5
Flask-Negotiation==0.1.9
Flask-Principal==0.4.0
Flask-RESTful==0.3.8
Flask-Restless==0.17.0
flask-restplus==0.13.0
Flask-Security==3.0.0
Flask-SocketIO==4.3.1
Flask-SQLAlchemy==2.4.4
Flask-WTF==0.14.3
flickrapi==2.4.0
folium==0.11.0
Forensic1394==0.1
foresight==0.1
freezegun==0.3.15
frida==12.11.7
fs==2.4.11
ftpscout==0.1
FullContact.py==0.0.6
furl==2.1.0
future==0.18.2
fuzzywuzzy==0.18.0
gdbgui==0.13.2.0
geographiclib==1.50
GeoIP==1.3.2
geoip2==4.0.2
geopy==2.0.0
getsploit==0.3.3
gevent==20.6.2
gitdb==4.0.5
gitem==0.9.2
github3.py==1.3.0
GitPython==3.1.7
gmpy2==2.1.0b5
google==3.0.0
google-api-core==1.22.0
google-api-python-client==1.10.0
google-auth==1.20.1
google-auth-httplib2==0.0.4
google-cloud-container==2.0.1
google-cloud-core==1.4.1
google-cloud-logging==1.15.1
google-cloud-monitoring==1.0.0
google-cloud-resource-manager==0.30.2
google-cloud-storage==1.30.0
google-play-scraper==0.1
google-resumable-media==0.7.1
Google-Search-API==1.1.14
google-streetview==1.2.9
googleapis-common-protos==1.52.0
googletransx==2.4.2
goop==0.1.1
gps==3.21
gpsoauth==0.4.1
grammarinator==19.3+50.g8a7372f
grandalf==0.7
greenery==3.2
greenlet==0.4.16
grequests==0.6.0
grpcio==1.30.2
gunicorn==20.0.4
h11==0.9.0
h2==3.2.0
h8mail==2.5.4
habu==0.1.36
halo==0.0.30
HammerTime-http==0.7.0
harpoon==0.1.3
helpdev==0.7.1
hexdump==3.3
howmanypeoplearearound==0.5.0
hpack==3.0.0
hpfeeds==3.0.0.dev0
html2text==2019.8.11
html5lib==1.1
HTMLParser==0.0.2
http-parser==0.9.0
http-tools==1.1.1
httplib2==0.18.1
httpretty==1.0.2
huepy==1.2.1
humanfriendly==8.2
humanize==0.5.1
hurry.filesize==0.9
hyperframe==5.2.0
hyperlink==20.0.1
hypothesis==5.26.0
iampoliciesgonewild==1.0.6.2
icmplib==1.1.1
idna==2.10
idna-ssl==1.1.0
imageio==2.9.0
imagemounter==3.1.0
imagesize==1.2.0
imgcat==0.5.0
impacket==0.9.21
importlib-metadata==1.6.1
inception==0.4.2
incremental==17.5.0
infinity==1.4
inflection==0.5.0
influxdb==5.2.3
iniconfig==1.0.1
inquirer==2.6.3
InstagramAPI==1.0.2
intensio-obfuscator==1.0.10.6
Interlace==1.8.2
intervals==0.8.1
intervaltree==3.1.0
iotop==0.6
IP2Location==8.4.1
ipaddr==2.2.0
ipdb==0.13.3
ipgetter==0.7
ipparser==0.3.6
iptools==0.7.0
ipwhois==1.1.0
IPy==1.0
ipykernel==5.3.4
ipython==7.17.0
ipython-genutils==0.1.0
ipywidgets==7.5.1
isc==2.0
isc-dhcp-leases==0.9.1
isodate==0.6.0
isort==5.2.2
itanium-demangler==1.0
itemadapter==0.1.0
itemloaders==1.0.1
itsdangerous==1.1.0
ivre==0.9.15.dev88
jaraco.classes==2.0
jaraco.collections==2.1
jaraco.functools==2.0
jaraco.itertools==4.4.2
jaraco.logging==2.0
jaraco.stream==2.0
jaraco.text==3.1
jdcal==1.4.1
jedi==0.17.0
jeepney==0.4.3
Jinja2==2.11.2
jinja2-time==0.2.0
jmespath==0.10.0
joblib==0.16.0
josepy==1.4.0
jsbeautifier==1.12.0
jsmin==2.2.2
json2html==1.3.0
jsonlines==1.2.0
jsonpickle==1.4.1
jsonrpclib-pelix==0.4.1
jsonschema==3.2.0
jupyter-client==6.1.3
jupyter-console==6.1.0
jupyter-core==4.6.3
jwcrypto==0.6.0
kaitaistruct==0.8
kamene==0.32
keylogger==2.7.3
keyring==21.3.0
keystone==0.9
kismet-rest==2020.5.1
KismetCaptureFreaklabsZigbee==2018.7.0
KismetCaptureRtl433==2019.9.1
KismetCaptureRtladsb==2019.10.1
KismetCaptureRtlamr==2019.10.1
kismon==1.0.2
kiwisolver==1.2.0
kombu==4.6.11
kube-hunter==0.3.2.dev5+g78e1672.d20200615
kwconfig==1.1.7
lazy-object-proxy==1.5.1
ldap0==1.1.0
ldap3==2.8
ldapdomaindump==0.9.3
ldeep==1.0.7
LibAppArmor==2.13.4
libarchive-c==2.9
libfdt==1.6.0
libkeepass==0.3.1.post1
libmagic==1.0
libsast==1.1.4
libtaxii==1.1.116
lief==0.10.1
lit==0.10.1.dev0
lml==0.0.9
lockfile==0.12.2
log-symbols==0.0.14
Logbook==1.5.3
loguru==0.5.1
logutils==0.3.5
louis==3.14.0
lsassy==2.1.2
lxml==4.5.2
M2Crypto==0.36.0
mac-alias==2.0.7
machinae==1.4.8
macholib==1.14
maclookup==1.0.3
Mako==1.1.3
malboxes==0.5.0
manticore==0.3.4
Markdown==3.2.2
MarkupSafe==1.1.1
marshmallow==3.7.1
marshmallow-sqlalchemy==0.23.1
mat2==0.11.0
matplotlib==3.3.1
maxminddb==2.0.2
mccabe==0.6.1
MechanicalSoup==0.12.0
mechanize==0.4.5
mercurial==5.5
metame==0.4
mido==1.2.9
mimerender==0.6.0
minidump==0.0.13
minikerberos==0.2.1
mispy==0.5
mistune==0.8.4
mitmproxy==5.2
mixbox==1.0.3
mmbot==1.1.1
mock==3.0.5
mockito==1.2.1
mongoengine==0.20.0
monotonic==1.5
more-itertools==8.4.0
moviepy==1.0.3
mpmath==1.1.0
msgpack==1.0.0
msldap==0.3.4
msoffcrypto-tool==4.10.2
msrest==0.6.18
msrestazure==0.6.4
mulpyplexer==0.8
multidict==4.7.6
munge==1.0.0
mutagen==1.45.1
mypy-extensions==0.4.3
names==0.3.0
nassl==3.0.0
natsort==7.0.1
nbconvert==5.6.1
nbformat==5.0.6
ndg-httpsclient==0.5.1
neo4j==4.0.dev0
netaddr==0.7.19
netifaces==0.10.9
networkx==2.4
Netzob==1.0.2
nili==0.1.1
nose==1.3.7
notebook==6.1.1
nplusone==1.0.0
ntlm-auth==1.5.0
ntlmrecon==0.4b0
numpy==1.19.1
oauth2==1.9.0.post1
oauth2client==4.1.3
oauthlib==3.1.0
odfpy==1.4.1
olefile==0.46
oletools==0.55.1
one-lin3r==2.1
onionshare==2.2
openpyxl==3.0.4
opinel==3.3.4
optparse-pretty==0.1.1
ordered-set==4.0.2
ordereddict==1.1
orderedmultidict==1.0.1
oscrypto==1.2.1
osrframework==0.20.2b1
OTXv2==1.5.10
packaging==20.4
pager==3.3
pandas==1.1.0
pandocfilters==1.4.2
paramiko==2.7.1
parse==1.15.0
parsedatetime==2.6
parsel==1.6.0
parso==0.8.0
passivetotal==1.0.31
passlib==1.7.2
patator==0.9
pathtools==0.1.2
pbkdf2==1.3
pbr==5.4.5
pcapy==0.11.5.dev0
pcodedmp==1.2.6
pdfkit==0.6.1
pdfminer.six==20200726
pdfminer3k==1.3.1
pefile==2019.4.18
peframe==6.0.3
pem==20.1.0
pep517==0.8.2
pexpect==4.8.0
pgcli==3.0.0
pgspecial==1.11.10
phoenixAES==0.0.2
phonenumbers==8.12.8
pick==0.6.7
pickleshare==0.7.5
pika==1.1.0
Pillow==7.2.0
pip-shims==0.5.3
piplapis-python==5.2.1
pkginfo==1.5.0.1
plasma==1.0
play-scraper==0.6.0
plecost==1.1.3
plette==0.2.3
plotly==4.9.0
PLTable==1.0.1
pluggy==0.13.1
pluginbase==1.0.0
plumbum==1.6.9
ply==3.11
Pmw==2.0.1
poormanslogging==1.1
portend==2.6
PowerStager==0.2.5
poyo==0.5.0
ppdeep==20200505
prettytable==0.7.2
probequest==0.7.2
progress==1.5
progressbar2==3.51.4
prometheus-client==0.8.0
prompt-toolkit==3.0.6
property==2.2
Protego==0.1.16
protobuf==3.12.4
proxy-db==0.2.5
psutil==5.7.2
psycopg2==2.8.5
ptyprocess==0.6.0
publicsuffix2==2.20191221
publicsuffixlist==0.7.4
pwntools==4.2.1
pwquality==1.4.2
py==1.9.0
py-altdns==1.0.0
pyaes==1.6.1
pyaml==20.4.0
pyasn==1.6.0b1
pyasn1==0.4.8
pyasn1-modules==0.2.8
PyAudio==0.2.11
PyAutoGUI==0.9.50
pybinaryedge==0.5
pycairo==1.19.1
pycares==3.1.1
pycodestyle==2.5.0
pycparser==2.20
pycrtsh==0.3.2
pycryptodome==3.9.8
pycryptodomex==3.9.7
pycurl==7.43.0.5
pydantic==1.6.1
pydeep==0.4
pyDes==2.0.1
PyDispatcher==2.0.5
pydot==1.4.1
pydotplus==2.0.2
pyee==7.0.2
pyelftools==0.26
pyenchant==3.1.1
pyevmasm==0.2.3
pyexcel==0.6.3
pyexcel-io==0.5.20
pyexcel-ods==0.5.6
pyexcel-text==0.2.7.1
pyexcel-xls==0.5.8
pyexcel-xlsx==0.5.8
PyExifTool==0.1.1
pyfiglet==0.8.post0
pyflakes==2.1.1
pygdbmi==0.9.0.3
pygeoip==0.3.2
pygexf==0.2.2
pyghmi==1.5.16
pygit2==1.2.1
PyGithub==1.53
Pygments==2.6.1
PyGObject==3.36.1
pygraphviz==1.5
pygreynoisev1==0.1
PyHamcrest==1.9.0
pyhibp==4.1.0
pyhunter==1.7
pyinotify==0.9.6
pyja3==1.0.0
PyJWT==1.7.1
PyLaTeX==1.3.4
pylint==2.5.3
pylnk3==0.3.0
pylstar==0.1.2
pylzma==0.5.0
pyminifier==2.1
pymisp==2.4.128
pymongo==3.11.0
PyMySQL==0.10.0
PyNaCl==1.3.0
pyngrok==4.1.10
pynput==1.6.8
pyodbc==4.0.28.0
pyof==0.1.0
PyOpenGL==3.1.5
pyOpenSSL==19.1.0
pypandoc==1.5
pyparsing==2.4.7
PyPDF2==1.26.0
pypdns==1.5.1
pype32==0.1a5
pyperclip==1.7.0
pypermacc==0.1.1
pyportify==0.4.1
pyppeteer2==0.2.2
pypsrp==0.5.0
pypssl==2.1
pypugjs==5.9.4
pypykatz==0.3.9
PyQt4-sip==4.19.19
PyQt5==5.15.0
PyQt5-sip==12.8.0
pyqtgraph==0.11.0
pyquery==1.4.1
pyRFC3339==1.1
PyRIC==0.1.6.4
pyrsistent==0.16.0
pysafebrowsing==0.1.1
pyserial==3.4
pysha3==1.0.2
pyside==1.2.4
pysigset==0.3.2
pysmb==1.2.1
pysmi==0.3.4
PySMT==0.9.0
pysnmp==4.4.12
PySocks==1.7.1
pyspnego==0.1.0
pysqlite3==0.4.3
pystache==0.5.4
pyStrich==0.8
pytanque==1.1.0
pytesseract==0.3.5
pytest==6.0.1
pytest-cov==2.10.1
pytest-factoryboy==2.0.3
pytest-forked==1.3.0
pytest-xdist==2.0.0
python-can==3.3.2
python-cli-ui==0.7.5
python-daemon==2.2.4
python-dateutil==2.8.1
python-docx==0.8.10
python-dxf==7.7.1
python-editor==1.0.4
python-emailahoy3==0.1.3
python-engineio==3.13.1
python-geoip==1.2
python-jose==3.2.0
python-Levenshtein==0.12.0
python-libnmap==0.7.0
python-libpcap==0.2.3
python-libtorrent==1.2.8
python-magic==0.4.18
python-memcached==1.58
python-mimeparse==1.6.0
python-nmap==0.6.1
python-openflow==2020.1
python-pam==1.8.4
python-pptx==0.6.18
python-ptrace==0.9.5
python-pushsafer==0.4
python-pytun==2.3.0
python-slugify==4.0.1
python-socketio==4.6.0
python-utils==2.4.0
python-whois==0.7.3
python-xapp==2.0.0
python-xlib==0.27
pythreatgrid2==0.1.1
pytoml==0.1.21
pytsk3==20200117
pytz==2020.1
pyusb==1.0.2
pyvex==8.20.7.27
PyVirtualDisplay==1.3.2
pyvit==0.2.1
PyWavelets==1.1.1
pywinrm==0.4.1
PyYAML==5.3.1
pyzmq==19.0.1
QDarkStyle==2.8.1
qrcode==6.1
qt4reactor==1.6
qtconsole==4.7.3
QtPy==1.9.0
queuelib==1.5.0
r2pipe==1.4.2
raccoon-scanner==0.8.5
rados==2.0.0
rarfile==4.0
rbd==2.0.0
rdap==1.0.1
rdpy==1.3.2
readability-lxml==0.8.1
readchar==2.0.0
readme-renderer==26.0
Reconnoitre==1.0
redis==3.5.3
regex==2020.7.14
relatime==1.1.0
request==1.0.117
requests==2.24.0
requests-cache==0.5.2
requests-file==1.5.1
requests-futures==1.0.0
requests-html==0.10.0
requests-mock==1.8.0
requests-ntlm==1.1.0
requests-oauthlib==1.3.0
requests-toolbelt==0.9.1
requests-unixsocket==0.2.0
requestsexceptions==1.4.0
resolvelib==0.4.0
responses==0.10.16
restkit==4.2.2
retdec-python==0.5.2
retrying==1.3.3
rfc3986==1.4.0
rgw==2.0.0
rjsmin==1.1.0
rlp==1.2.0
roguehostapd==1.1.2
root==4.1.0
ROPGadget==6.3
ropper==1.13.5
routersploit==3.4.0
rpm==4.15.1
rpyc==4.1.5
rq==1.5.0
rsa==4.6
rsatool==1.0
ruamel.yaml==0.16.10
ruamel.yaml.clib==0.2.0
s3cmd==2.1.0
s3transfer==0.3.3
scandir==1.10.0
scanless==2.1.3
scapy===git-archive.dev304758016
scapy-http==1.8.2
schedule==0.6.0
schema==0.7.3
scikit-image==0.17.2
scikit-learn==0.23.1
scipy==1.5.2
scp==0.13.2
Scrapy==2.3.0
screenutils==0.0.1.6.2
scruffington==0.3.8.1
scruffy==0.3
SecretStorage==3.1.2
secure==0.2.1
selenium==3.141.0
semgrep==0.18.0
Send2Trash==1.5.0
service-identity==18.1.0
setproctitle==1.1.10
setuptools-git==1.2
setuptools-markdown==0.4.1
setuptools-scm==4.1.2
sh==1.13.1
shellen==0.3.0
shelljob==0.5.6
shodan==1.23.0
sickle==2.0.2
simhash==1.10.2
simple-requests==1.1.1
simplejson==3.17.2
simplekv==0.14.1
simuvex==7.7.9.8
sip==4.19.23
sipvicious==0.3.1
six==1.15.0
slowaes==0.1a1
smmap==3.0.4
smoke-zephyr==2.0.0
snallygaster==0.0.8
sniffles==3.4.3
snowballstemmer==2.0.0
socketpool==0.5.3
sortedcontainers==2.2.2
soupsieve==2.0.1
spark-parser==1.8.9
speaklater==1.3
SpeechRecognition==3.8.1
Sphinx==1.8.5
sphinx-rtd-theme==0.5.0
sphinxcontrib-applehelp==1.0.2
sphinxcontrib-devhelp==1.0.2
sphinxcontrib-htmlhelp==1.0.3
sphinxcontrib-httpdomain==1.7.0
sphinxcontrib-jsmath==1.0.1
sphinxcontrib-qthelp==1.0.3
sphinxcontrib-serializinghtml==1.1.4
sphinxcontrib-websupport==1.1.2
spinners==0.0.24
SpoofMAC==2.1.1
spyonweb==0.1
spyse.py==0.13.3.9
SQLAlchemy==1.3.19
SQLAlchemy-Utils==0.35.0
sqlparse==0.3.1
ssdeep==3.4
ssh-audit==2.2.0
sshtunnel==0.1.5
sshuttle==1.0.3
sslyze==3.0.8
stem==1.8.0
stix==1.2.0.10
stix-validator==2.5.0
stopit==1.1.2
strictyaml==1.1.0
StringDist==1.0.9
sublert==1.0.0
suricata==5.0.3
sympy==1.6.2
syslog-rfc5424-formatter==1.2.2
tabulate==0.8.7
tachyon3==3.3.0
team==1.0
Telethon==1.13.0
tempora==4.0.0
termcolor==1.1.0
terminado==0.8.3
terminaltables==3.1.0
terminator==1.92
termineter==1.0.5
testpath==0.4.4
text-unidecode==1.3
texttable==1.6.2
tftpy==0.8.0
threadpoolctl==2.1.0
tinycss==0.4
tinycss2==1.0.2
tinydb==4.1.1
tld==0.12.2
tldextract==2.2.3
tls-parser==1.2.2
tlsfuzzer==0.0.1
tlslite-ng==0.7.5
toml==0.10.1
tomlkit==0.7.0
toolz==0.10.0
tornado==6.0.4
torrequest==0.1.0
tox==3.14.0
tqdm==4.48.2
trackerjacker==1.9.0
traitlets==4.3.3
trans==2.1.0
truffleHog==2.0.98
truffleHogRegexes==0.0.7
TrustTrees==3.0.2
tweepy==3.8.0
twine==1.14.0
twint==2.1.21
Twisted==20.3.0
twitter==1.18.0
txaio==20.4.1
typing==3.7.4.3
typing-extensions==3.7.4.3
tzlocal==2.1
uefi-firmware==1.9
ujson==0.0.0
uncompyle6==3.7.0
unicodecsv==0.14.1
unicorn==1.0.1
Unidecode==1.1.1
urh==2.8.8
uritemplate==3.0.1
url-normalize==1.4.2
urllib3==1.25.10
urlnorm==1.1.4
urwid==2.1.1
user-agent==0.1.9
uvloop==0.14.0
V3n0M==425
valhallaAPI==0.3.0
validate-email==1.3
validator-collection==1.4.1
validators==0.17.1
vcrpy==4.1.0
veles==2018.5.0
veryprettytable==0.8.1
VHostScan==1.21
vine==1.3.0
viper-framework==2.0rc10
virtualenv==20.0.23
virustotal-api==1.1.11
vistir==0.5.2
visualize-logs==20161112.2
voltron==0.1.7
vulners==1.5.7
w3af-api-client==3.0.1
w3lib==1.22.0
wafw00f==2.1.0
wapiti3==3.0.3
watchdog==0.9.0
waybackpack==0.3.6
wcwidth==0.2.5
weakrefmethod==1.0.3
web2ldap==1.5.75
webargs==6.1.0
webencodings==0.5.1
websocket-client==0.57.0
websockets==8.1
websploit==4.0.4
webtech==1.2.7
Werkzeug==1.0.1
wget==3.2
whatportis==0.8.1
whichcraft==0.6.1
whitenoise==5.2.0
Whoosh==2.7.4
widgetsnbextension==3.5.1
wifiphisher==1.4
wifipumpkin3==1.0.0
win-inet-pton==1.1.0
winacl==0.0.4
wincertstore==0.2
winsspi==0.0.9
wireless==0.3.3
wrapt==1.12.1
wsaccel==0.6.2
wsproto==0.15.0
WTForms==2.2.1
www-authenticate==0.9.2
xcat==1.0.4
xdis==5.0.3
xlrd==1.2.0
XlsxWriter==1.3.2
xlutils==2.0.0
xlwt==1.3.0
xmltodict==0.12.0
xortool==0.99
xpath-expressions==1.0.2
xsrfprobe==2.3.1
YAAF==1.0
yara-python==3.11.0
yarl==1.5.1
yaswfp==0.9.3
yattag==1.14.0
yawast==0.11.0.dev1+g5e9e7a3
youtube-dl==2020.7.28
zc.lockfile==2.0
zipp==3.1.0
zlib-wrapper==0.1.3
zope.component==4.6.2
zope.deferredimport==4.3.1
zope.deprecation==4.4.0
zope.event==4.4
zope.hookable==5.0.1
zope.interface==5.1.0
zope.proxy==4.3.5
zstandard==0.14.0

I didn't dump it to a file; I just let it spam my console

### Configuration files

Mention any settings you have changed/added/removed.

Bone stock. Nothing really changed as far as I know? Usually if I am going to change something I do it through the Command Line first

### Reports/Extra data

If you are having issues with plugins, please attach relevant files if possible.
(strip your reports of all sensitive information beforehand).

### OS

Provide information on your operating system. Example:

$ cat /etc/lsb-release
LSB_VERSION=1.4
DISTRIB_ID=Arch
DISTRIB_RELEASE=rolling
DISTRIB_DESCRIPTION="Arch Linux"

it's blackarch. Since I essentially built everything from source I wanted to come and complain here first. I am not a web guy (yet) so I can't help too much with that.

**Comment by fedek** [comment]
This is a known issue on one or our dependencies. Thanks for the feedback, closing this issue during clean-up.
