### ISSUE TITLE
Wrong sort order of IPv4 addresses in WebGui

### ISSUE THREAD

**Issue by zetta3000** [infobyte/faraday#417]
## Issue Type
Bug Report

## Faraday version

Faraday v3.12 (deb)

## Component Name

WebGui

## Steps to reproduce

I uploaded an nmap XML file with the following scanned hosts:
```
192.168.0.1
192.168.0.2
192.168.0.3
192.168.0.10
192.168.0.20
192.168.0.100
192.168.0.200
```

In the WebGui these hosts are sorted incorrectly:

![hosts](https://user-images.githubusercontent.com/72920563/96254695-02c71c80-0fb6-11eb-9d2a-698a59e434b5.png)

Apparently, Faraday sorts the IP addresses lexicographically instead of how IPv4 addresses are normally sorted.

This bug also occurs when selecting services from the "Service report" section.

## Expected results

The WebGui should sort these IPv4 addresses like this:
```
192.168.0.1
192.168.0.2
192.168.0.3
192.168.0.10
192.168.0.20
192.168.0.100
192.168.0.200
```

### OS

Provide information on your operating system. Example:

```
$ cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.1 LTS"
```

**Comment by aenima-x** [comment]
The "ip" field really can hold any string.
For example in case a report from a tool has the hostname of the target but faraday cant resolve the ip address.
That is why the sorting.
