### ISSUE TITLE
Filters not working

### ISSUE THREAD

**Issue by sibwara** [infobyte/faraday#419]
Please search the [Wiki](https://github.com/infobyte/faraday/wiki) for a solution before posting a ticket. Use the <strong>“New Support Request”</strong> button to the right of the screen to submit a ticket for technical support.

## Issue Type
 - Bug Re port

## Faraday version

Faraday 3.12

## Steps to reproduce

type the filter : `severity:"high"` in the filter field -> you see the "Oops: Invalid filter, please check the documentation: support.faradaysec.com" pop up.

Click on the status of a vulnerability to make faraday automatically put `severity:high` in the filter field. Without changing anything, simply click on the search button. The "Oops" pop up raises again.

## Expected results

the filter must be editable by the user.

### Debugging tracebacks (current results)

here is the debugging stack of the browser:
![Sans titre](https://user-images.githubusercontent.com/42293505/96730838-e6145580-13b6-11eb-8a8b-acb9c99ee1af.png)

### OS

Linux 5.7.0-kali3-amd64 #1 SMP Debian 5.7.17-1kali1 (2020-08-26) x86_64 GNU/Linux

**Comment by fedek** [comment]
The angular WebUI has been deprecated since 4.0. This issue has been addressed in the new WebUI. Thanks for the bug report!
