### ISSUE TITLE
API Examples always get 404 responses

### ISSUE THREAD

**Issue by gister9000** [infobyte/faraday#420]
## Issue Type
 - Documentation Report

## Steps to reproduce

1. Go to https://api.faradaysec.com/
2. Click "Try it out" on ANY example
3. Receive 404

**Comment by EricHorvat** [comment]
Hi @gister9000 !
We know it! When we launch 3.12; we had some problems with the OPTIONS endpoints and some configuration there. For the new release it will be available.

**Comment by gister9000** [comment]
3.12 was already launched in september.

I assume you meant 3.13 and I'm looking forward to the new update! Thanks

**Comment by EricHorvat** [comment]
@gister9000 Typo, sorry, I was telling you what happened. `We we *launched*..`
