### ISSUE TITLE
SARIF support

### ISSUE THREAD

**Issue by prabhu** [infobyte/faraday#422]
**What's the problem this feature will solve?**

Integrate [scan](https://slscan.io) with faraday by supporting [SARIF](https://slscan.io/en/latest/integrations/sarif/) format

**Describe the solution you'd like**

Native way of importing SARIF reports.

Scan is a free opensource DevSecOps tool powered by numerous other open-source [tools](https://github.com/ShiftLeftSecurity/sast-scan/). It could be nice integration here.

**Alternative Solutions**

**Additional context**

**Comment by dwisiswant0** [comment]
+1

**Comment by ezk06eer** [comment]
@prabhu hi prabhu we have a plugins repository and you can create the issue there, can you please share a json sarif file in the report? remember we have templates for feature request. Cheers!

**Comment by ezk06eer** [comment]
we have sarif support now! please check about it!

**Comment by prabhu** [comment]
@ezk06eer This is super cool! Can I add another issue to add support for CycloneDX 1.5 support?

**Comment by f-amato** [comment]
Thanks for the issues. Keep in mind that Faraday is open source. You can help us develop this new issues too. We are going to add it to the roadmap. Do you have an export file example to add this issue? Normally we support .XML, .json, CSV, etc

**Comment by prabhu** [comment]
Thanks @f-amato I think we can attrract contributors once we have a branch going. I'm happy to help during the design to make the product suitable for supply-chain, VEX and VDR use cases. Below are some links:

https://cyclonedx.org/docs/1.5/json/

Examples repo
https://github.com/CycloneDX/bom-examples/

Juice-shop example
https://github.com/CycloneDX/bom-examples/blob/master/SBOM/juice-shop/v11.1.2/bom.json
