### ISSUE TITLE
Can't install client and server on the same machine?

### ISSUE THREAD

**Issue by bt-nia** [infobyte/faraday#423]
I just followed the install process for the server and wanted to upload a report. 
From what I understand this has to happen via the client, so I installed that. However, after installing it, the server was removed. 
How/why is that?

**Comment by aenima-x** [comment]
@bt-nia you can upload the report in te server.
Go to Manage and click in the upload icon.
Select the report, and then "upload file"

**Comment by bt-nia** [comment]
@aenima-x thank you. I was aware of this, but I'm looking for away to upload reports programmatically. Since I'm looking for a way to add reports from a scheduled scan. Is there an other option?

Is there some kind of ETA for the new command line tool?

**Comment by aenima-x** [comment]
@bt-nia https://github.com/infobyte/faraday-cli

but keep in mind that it might change

**Comment by aenima-x** [comment]
@bt-nia feel free to leave feedback and open issue if you have problems

**Comment by bt-nia** [comment]
@aenima-x awesome! That's what I was looking for. The auth call does seem to require some manual input, but overall the necessary functions are there.
