### ISSUE TITLE
Issue upload openvas report

### ISSUE THREAD

**Issue by DanieleCalzetti** [infobyte/faraday#427]
## OS
CentOS 7

## Faraday-tool used

Web UI 3.14.0

## Issue

I generated a xml report with openvas.
The openvas version is 20.08.1. 
When I upload the reports by using the webui it doesn't upload the CVE information for a given vulnerability, it correctly parse the xml field used to fill the description and resolution fields but it doesn't add any CVE to the reference section inside the web UI.

**Comment by fedek** [comment]
This issue has already been addressed and fixed, please refer to [OpenVAS Parsing](https://github.com/infobyte/faraday_plugins/issues/18)

Thanks for the feedback
