### ISSUE TITLE
Ability to modify host/service of a vuln after creation. 

### ISSUE THREAD

**Issue by gister9000** [infobyte/faraday#428]
**What's the problem this feature will solve?**
AFAIK, I can't change host/service of a vulnerability via web UI.

**Describe the solution you'd like**
I'd like to see host/service fields in web UI, after clicking the vulnerability edit button.

If this is possible, please let me know how

**Comment by aenima-x** [comment]
sorry @gister9000 that is not posible right know.
It is technically possible because the api allow that, but is not implemented in the UI.

May be in the future
