### ISSUE TITLE
Docker Error on Run

### ISSUE THREAD

**Issue by caseybecking** [infobyte/faraday#437]
## Issue Type
Bug

## Faraday version
Latest - Cant paste due to docker

## Component Name

docker: Error response from daemon: OCI runtime create failed: container_linux.go:349: starting container process caused "exec: \"-v\": executable file not found in $PATH": unknown.
ERRO[0004] error waiting for container: context canceled

## Steps to reproduce
docker pull infobyte/faraday
docker run infobyte/faraday -v /home/MYUSERNAME/database:/var/lib/postgresql/10/main

## Expected results
I expected the container to run and not error out as well i would expect it to be running but nothing is when i list out docker ps

### Debugging tracebacks (current results)
None, it's docker 

### OS

DISTRIB_ID=Debian
DISTRIB_RELEASE=10
DISTRIB_CODENAME=buster
DISTRIB_DESCRIPTION="Debian GNU/Linux 10 (buster)"

### Docker
docker version
Client: Docker Engine - Community
 Version:           20.10.8
 API version:       1.41
 Go version:        go1.16.6
 Git commit:        3967b7d
 Built:             Fri Jul 30 19:54:02 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.8
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.6
  Git commit:       75249d8
  Built:            Fri Jul 30 19:52:10 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.9
  GitCommit:        e25210fe30a0a703442421b0f60afac609f950a3
 runc:
  Version:          1.0.1
  GitCommit:        v1.0.1-0-g4144b63
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

**Comment by aenima-x** [comment]
You are trying to mount a database in the container??

**Comment by caseybecking** [comment]
I'm following these instructions - https://github.com/infobyte/faraday/wiki/Installation-Docker-Community

**Comment by aenima-x** [comment]
That image is very out of date, I recommend that you install it in a virtualenv

**Comment by caseybecking** [comment]
:+1: Thank you!
