### ISSUE TITLE
I've installed what's next

### ISSUE THREAD

**Issue by Mybehu** [infobyte/faraday#440]
Install from repo
$ pip install virtualenv
$ virtualenv faraday_venv
$ source faraday_venv/bin/activate
$ git clone git@github.com:infobyte/faraday.git
$ cd faraday
$ git clone https://github.com/infobyte/faraday_angular_frontend.git faraday/frontend
$ pip install .

I've done the above installation via Kali Linux userland on my device then what next I'm really confused

**Comment by ezk06eer** [comment]
please follow our guide here:

https://docs.faradaysec.com/Install-guide-pypigithub/

Cheers!

**Comment by ezk06eer** [comment]
@Mybehu any news? if not ill close this issue.

Have a great new year!
