### ISSUE TITLE
Why does RHEL 8.6 regard the newest version 4.0.4 x86-64 .RPM package of Faraday as invalid?

### ISSUE THREAD

**Issue by fehertamaskyndryl** [infobyte/faraday#449]
## Issue Type
 - Bug Report

## Faraday version

version 4.0.4 (Gorrabot)

## Component Name

RedHat EL 8.6.0-20220627 codename Ootpa (x86-64bit, Hyper-V guest in Windows 10 Enterprise host)
yum version 4.7.0 / rpm version 4.14.3

## Steps to reproduce

sudo rpm -ivh: error: faraday-server_amd64.rpm: not an rpm package (or package manifest)
sudo yum install: Can not load RPM file: faraday-server_amd64.rpm

## Expected results

Successful install of Faraday v4.0.4 server was expected but regrettably didn't happen

## Environment information

RedHat EL 8.6.0-20220627 (x86-64, Hyper-V guest in Windows 10 host)
yum 4.7.0 / rpm 4.14.3

### OS

$ cat /etc/lsb-release
DISTRIB_ID=ReHat
DISTRIB_RELEASE=8.6
DISTRIB_CODENAME=Ootpa
DISTRIB_DESCRIPTION="RHEL 8.6.0"

**Comment by fehertamaskyndryl** [comment]
FYIF: the Faraday version 3.19.0 RPM file does start installing on the above described system, so I think the very fresh v4.0.4 may have a packaging problem.

(By the way, I have a different problem with Faraday server v3.19.0: during the install process it suddenly asks for "Current Password:" and I havent been able to figure out which password that should mean. It's not the logged-in Linux user's password.  There is no hint provided and simple ones like admin, password or 1235456 are also not accepted. It times out after a while, so install ends unsuccessfully.)

**Comment by aenima-x** [comment]
@fehertamaskyndryl when you run ```faraday-manage initdb``` it gives you de password.

you can change it with ```faraday-manage change-password```

**Comment by aenima-x** [comment]
@fehertamaskyndryl what do you mean with "during the install"?

**Comment by fehertamaskyndryl** [comment]
Hello,

> @fehertamaskyndryl when you run `faraday-manage initdb` it gives you de password.
> you can change it with `faraday-manage change-password`

The command you mentioned isn't available until after one has installed Faraday but the Faraday v3.1.9 RPM is asking me for "Current password" during its installation, so a kind of Catch-22 situation. Whatever I type, e.g. my Linux password or 123456, it just feeds a new line and asks "Current password" again and again, until it times out.

**Comment by aenima-x** [comment]
@fehertamaskyndryl can you download again de 4.0.4 rpm and tell me if it work ok?

**Comment by fehertamaskyndryl** [comment]
Hello,

> @fehertamaskyndryl can you download again de 4.0.4 rpm and tell me if it work ok?

Thanks! Installation now starts with the Faraday 4.0.4 RPM package which has been uploaded a few minutes ago.

**Comment by aenima-x** [comment]
@fehertamaskyndryl Thanks to you.
