### ISSUE TITLE
docker-compose up error

### ISSUE THREAD

**Issue by andyoulovexy** [infobyte/faraday#459]
mv: cannot move '/server.ini' to '/home/faraday/.faraday/config/.': No such file or directory
![image](https://user-images.githubusercontent.com/38940994/208012064-e6628bc6-48d9-458b-b887-3fa399ae4dfc.png)
how to solve it?tks

**Comment by aenima-x** [comment]
@andyoulovexy I think you have an old version of the image.
Do a pull first

**Comment by andyoulovexy** [comment]
> @andyoulovexy I think you have an old version of the image. Do a pull first

https://github.com/infobyte/faraday/blob/master/docker-compose.yaml .i used

**Comment by aenima-x** [comment]
@andyoulovexy  thats the compose, I talk about the version of the docker image
run this
```docker pull faradaysec/faraday```

and then run again the ```docker-compose up```

**Comment by andyoulovexy** [comment]
> @andyoulovexy thats the compose, I talk about the version of the docker image run this `docker pull faradaysec/faraday`
> 
> and then run again the `docker-compose up`

it's ok,thanks
