### ISSUE TITLE
How to generate frontend code ?

### ISSUE THREAD

**Issue by bulacho** [infobyte/faraday#464]
I'm trying to find a way to customize Frontend but I don't find the frontend code for custom ?
So tell me, where is the frontend code, and how to customize that frontend code ?

**Comment by ezk06eer** [comment]
Hello @bulacho, thank you for reaching out. The code you're looking for is located in the server folder under www. However, please note that the Front End has been built using React and therefore we may not have the ability to customize it further. Please let us know if there's anything else we can assist you with.

**Comment by bulacho** [comment]
I want to customize more FE, can public source code React FE, not source built  ?

**Comment by ezk06eer** [comment]
@bulacho 
Thank you for your interest in our front-end code. While we appreciate your request, we have decided not to publish our source code at this time. We understand that you may be disappointed, but we have made this decision based on a number of factors, including the protection of our intellectual property and the privacy of our users.

We hope you can understand our decision, and we appreciate your interest in our work. If you have any further questions or concerns, please don't hesitate to reach out.
