### ISSUE TITLE
how can i generate the password installing fadaday on docker

### ISSUE THREAD

**Issue by tnspaolo** [infobyte/faraday#466]
i installed faraday on docker.. how can i generate the firsta password

**Comment by ezk06eer** [comment]
Hi @tnspaolo , at the time of the instance creation with docker-compose you will see  message in your console like this:

```log
faraday_app    | Admin user created with username: faraday password: |e{:d^(29}O6R
faraday_app    | Wed Mar  8 14:31:24 UTC 2023 Running migrations ...
faraday_a
```
If you are using some sort of desktop app you should see the message in the log output.


Thanks for asking, if you have some issues you can ask us about it.
