### ISSUE TITLE
Semgrep plugin

### ISSUE THREAD

**Issue by dwisiswant0** [infobyte/faraday#467]
**What's the problem this feature will solve?**

**Describe the solution you'd like**

**Alternative Solutions**

**Additional context**

**Comment by ezk06eer** [comment]
@dwisiswant0 hi, we will think about it, i think it is a good tool and would be included in next releases, thinking about SAST / DAST solutions and integration with the model CI/CD and DevSecOps, i think will be great to include it. if you have it in hand a .json out sanitized will be great.

Thanks!

**Comment by dwisiswant0** [comment]
@ezk06eer - Here I attach an example of the Semgrep findings with both JSON & (JUnit) XML formats: [dvpwa-out.zip](https://github.com/infobyte/faraday/files/11073240/dvpwa-out.zip).

**Comment by dwisiswant0** [comment]
Thank you guys! 🔥
