### ISSUE TITLE
Nuclei plugin but in JSON/SARIF format

### ISSUE THREAD

**Issue by dwisiswant0** [infobyte/faraday#468]
**What's the problem this feature will solve?**

**Describe the solution you'd like**

**Alternative Solutions**

**Additional context**

**Comment by ezk06eer** [comment]
@dwisiswant0 Hello there! Thank you for reaching out.

To ensure that we can assist you properly, we kindly ask that you follow all the process requests and provide a detailed explanation of your inquiry. This will help us understand your situation better and provide you with the best possible solution.

Furthermore, we would like to inform you that the plugin you have requested is already implemented in our solution. Please let us know if you need any further assistance with this.

Thank you for your cooperation, and we look forward to hearing back from you soon.
