### ISSUE TITLE
"Run" button is not active

### ISSUE THREAD

**Issue by cadet225** [infobyte/faraday#472]
Hi Team!
I can't start the agent because the "Run" button is not active. What could be the problem?
Thanks!
![123](https://github.com/infobyte/faraday/assets/44412207/9d8a04d2-a2e8-4aa6-92dd-0d59719c0938)

![faraday-dispatcher run](https://github.com/infobyte/faraday/assets/44412207/47c8a8b2-6a77-4244-8060-b5382bb94d83)
![faraday](https://github.com/infobyte/faraday/assets/44412207/94c65f9e-76fa-48be-882e-eb2adcb7427a)
![faraday-dispatcher](https://github.com/infobyte/faraday/assets/44412207/64c93059-3c90-4e8b-a078-d2381940cd40)

**Comment by ezk06eer** [comment]
@cadet225 could you please update to our latest release? we are on 4.5.1
