### ISSUE TITLE
Can't start faraday on Kali purple

### ISSUE THREAD

**Issue by ChipTechChaos** [infobyte/faraday#473]
Hello together.

I'm using faraday on 3 Kali-installations. 2 of them are "regular" Kali Security installations, one of them is Kali purple. On the first both machines, I have zero issues and everything's running fine, but on the last, I can't start faraday while the startsequence stated missing rights to the /root- or my user-directory

`$ sudo faraday`
`[sudo] Passwort für administrator: `
`could not change directory to "/home/administrator": Keine Berechtigung`

`This script will  create a new postgres user  and  save faraday-server settings (server.ini).`
`ERROR: could not change directory to "/home/administrator": Keine Berechtigung`
`WARNUNG:  Version von Sortierfolge für Datenbank »postgres« stimmt nicht überein`
`DETAIL:  Die Datenbank wurde mit Sortierfolgenversion 2.36 erzeugt, aber das Betriebssystem hat Version 2.37.`
`TIP:  Bauen Sie alle Objekte in dieser Datenbank, die die Standardsortierfolge verwenden, neu und führen Sie ALTER DATABASE postgres` 
`REFRESH COLLATION VERSION aus, oder bauen Sie PostgreSQL mit der richtigen Bibliotheksversion.`
`FEHLER:  Rolle »faraday_postgresql« existiert bereits`

I allready tried to delete the /root/.faraday-directory and also deleted the whole postgres-database, but the problem is persistent. Has anyone any idea where I can search for problems? Can I provide additional logs to find a solution?

regards

**Comment by ezk06eer** [comment]
@ChipTechChaos sending you a PM.

**Comment by ezk06eer** [comment]
Hi @ChipTechChaos i had a fresh install of kali here in my machine, and fresh spinned kali/rolling doesnt present any issue.

![screenshot](https://github.com/infobyte/faraday/assets/25327825/67416fdd-cfa7-45cc-a2ff-39e879ec11ae)

i think something in your implementation is messing up the env.

let me know if you still have this issue and we go from there. follow this guide please: https://docs.faradaysec.com/Install-guide-community/

remember you should drop any install of faraday before doing the install in kali.

we have the .deb file in our project releases tag: https://github.com/infobyte/faraday/releases

if you still need help ill try to sort it out with you.

**Comment by ChipTechChaos** [comment]
Hi @ezk06eer,

thank you for the work and effort.
Meanwhile I'm sure that this is not a problem of faraday but of kali. I installed 3 different kali purple machines (https://gitlab.com/kalilinux/kali-purple/documentation/-/wikis/home) on different hardware and every single machine showed the same problem. In 2 "normal" kali-instances there are no issues at all, so I'm sure it's a problem that belongs to the package maintainer from kali. I'll try to reach out to that guys.

Cheers

**Comment by ezk06eer** [comment]
so, i've been doing a little research, so if you want to make an upgrade to your faraday install first you should do:

```
dpkg -r faraday
dpkg -r faraday-agent dispatcher
dpkg -r faraday-cli
```

then either download the .deb file from our github and install it in your kali with dpkg -i, if you are "administrator" you should do sudo dpkg -i anyways.

try it out, if you already created the db as root you should copy the files under .faraday to your "administrator" account.

then, if you want to start it just run "sudo faraday" as i did, this will execute the customized script from the kali team under 

just edit :
```/usr/bin/faraday```

and change the 
`sudo systemctl start faraday` to: `sudo systemctl start faraday-server.service`


this will startup the db and also start the faraday-server.service 

let me know how it goes.


Cheers!
