### ISSUE TITLE
faraday-manage initdb failed!

### ISSUE THREAD

**Issue by JayMiguel** [infobyte/faraday#480]
I have started PostgreSQL. Then I execute the 'faraday manage initdb' command. It runs incorrectly:
`┌──(kali㉿attacker)-[~]
└─$ faraday-manage initdb
2023-12-25T02:48:32-0500 - faraday.server.app - INFO {MainThread} [pid:50311] [app.py:479 - create_app()]  Missing [database] section on server.ini. Please configure the database before running the server.
/nix/store/q77nskf89iv0ararp6ab87h48qldhw1a-python3.10-flask-sqlalchemy-2.5.1/lib/python3.10/site-packages/flask_sqlalchemy/__init__.py:851: UserWarning: Neither SQLALCHEMY_DATABASE_URI nor SQLALCHEMY_BINDS is set. Defaulting SQLALCHEMY_DATABASE_URI to "sqlite:///:memory:".
  warnings.warn(
This script will  create a new postgres user  and  save faraday-server settings (server.ini).
[sudo] kali 的密码：
ERROR: psql: 错误: 连接到套接字"/var/run/postgresql/.s.PGSQL.5432"上的服务器失败:没有那个文件或目录
	Is the server running locally and accepting connections on that socket?
`

**Comment by ezk06eer** [comment]
@JayMiguel have you followed the steps in: https://docs.faradaysec.com/Install-guide-Linux/ 
If you will use kali, the installation doesnt need an initdb, because its already up. If  you will do a reinstall you should remove the old kali install.
