### ISSUE TITLE
Cannot connect to host :9000 

### ISSUE THREAD

**Issue by xxx-qwe3** [infobyte/faraday#482]
server:5.0.1

port 9000 cannot connect

![image](https://github.com/infobyte/faraday/assets/47934398/bd5b69cb-01af-41ad-965f-78c001f99dab)

**Comment by ezk06eer** [comment]
Hi @xxx-qwe3 youre not supposed to connect to 9000, its only websockets. connecting to 5985 should be just fine.

Cheers!
