### ISSUE TITLE
[BUG][DEPRECATE][FIXED][Faraday_v2] Fonts don't respect system settings

### ISSUE THREAD

**Issue by Zapotek** [infobyte/faraday#5]
The fonts of interface don't seem to respect the system settings and appear small and choppy in high-ish resolutions.

Resolution: 1920x1080
OS: Ubuntu 13.10
Python: 2.7.5+
![faraday](https://f.cloud.github.com/assets/375743/1779709/dbe6a4c0-6853-11e3-9ee8-8031731e8f72.png)

Steps:

    sudo ./install.sh
    ./faraday

**Comment by Ezequieltbh** [comment]
Hi Zapotek!
Our QT interface is now deprecated.
GTK is the new Graphical interface for Faraday.
We are closing this ticket for this.
Cheers!
