### ISSUE TITLE
install on mac os  error

### ISSUE THREAD

**Issue by freetest** [infobyte/faraday#53]
pip freeze 

backports.ssl-match-hostname==3.4.0.2
colorama==0.3.2
couchdbkit==0.6.5
Flask==0.10.1
http-parser==0.8.3
IPy==0.75
itsdangerous==0.24
Jinja2==2.8
MarkupSafe==0.23
mockito==0.5.1
psycopg2==2.5.4
requests==2.7.0
restkit==4.2.2
socketpool==0.5.3
tornado==3.2
Werkzeug==0.10.4
wheel==0.24.0
Whoosh==2.5.5

python faraday.py

![error](https://cloud.githubusercontent.com/assets/5380255/10877512/cea1bd92-8181-11e5-93b4-48cd5110bb3a.png)

launchctl load ~/Library/LaunchAgents/homebrew.mxcl.couchdb.plist

![db](https://cloud.githubusercontent.com/assets/5380255/10877586/7f62cf9a-8182-11e5-94de-7dba81c192d0.png)

**Comment by f-amato** [comment]
Hi @freetest 
1) Edit the following file: ~/.faraday/config/user.xml
2) Search for the following tags (couch_uri) and set them, normally is like this
http://127.0.0.1:5984

3) start faraday by running: ./faraday.py
4) Using a browser go to http://127.0.0.1:5984/reports/_design/reports/index.html (if you are using couch in a different IP, set it to the right address)

You will find more information here:
https://github.com/infobyte/faraday/wiki/Couchdb

Let me know if this works,

**Comment by freetest** [comment]
thanks a lot~  it worked now~
