### ISSUE TITLE
Missing file

### ISSUE THREAD

**Issue by epick** [infobyte/faraday#54]
Hi, I tested Faraday but only work in Qt. When I run ./faraday I get the message Please config Couchdb for fancy HTML5 Dashboard. When I want edit file user.xml this not there in .faraday/config/user.xml

Thanks

**Comment by epick** [comment]
Sorry I found the file user.xml when I edit this I can't see Web UI. When I tried to access to http://[COUCHDB]:5984/reports/_design/reports/index.html  I get this {"error":"not_found","reason":"no_db_file"}

**Comment by f-amato** [comment]
Hi @epick,
Thanks for reaching out. What is happening is that you have not yet configured couchdb.

If you are using the QT GUI:
https://github.com/infobyte/faraday/wiki/Couchdb

If you are using the --gui=no-gui option
1) Edit the following file: ~/.faraday/config/user.xml
2) Search for the following tags (couch_uri) and set them, normally is like this
http://127.0.0.1:5984

3) Start couchdb: sudo service couchdb start
4) start faraday by running: ./faraday.py
4) Using a browser go to http://127.0.0.1:5984/reports/_design/reports/index.html (if you are using couch in a different IP, set it to the right address)

Let me know if this works,

**Comment by epick** [comment]
Hi Francisco

I still get the message when I go to http://127.0.0.1:5984/reports/_design/reports/index.html 

{"error":"not_found","reason":"no_db_file"}

I attach screenshot from my terminal
![faraday](https://cloud.githubusercontent.com/assets/425968/11167304/0605d8aa-8b22-11e5-911b-b4185a1b2a01.png)

I'm not expert on Couchdb, please give me a guidance

Thanks

**Comment by f-amato** [comment]
Hi @epick 
Could you please send me an screenshot of http://127.0.0.1:5984/_utils/
From the msg I can see "WARNING - No route to couchdb server on:127.0.0.1:5984"
Could you please send us your ~/.faraday/config/user.xml

Best

**Comment by f-amato** [comment]
Hi @epick,
Do you have feedback about it?
Best
