### ISSUE TITLE
CIS Configuration Assessment Tool (CIS-CAT) support request

### ISSUE THREAD

**Issue by mablanco** [infobyte/faraday#55]
Hello. First of all, thanks a lot for such a great tool!

There's a really handy tool called CIS-CAT (http://benchmarks.cisecurity.org/) whose reports would be very interesting to import into Faraday. Could you have a look at the possibility of doing so? It's a commercial tool, so I can help with demo reports and so. CIS-CAT builds its reports in HTML and can export them to XML and CSV.

Thanks in advance.

**Comment by f-amato** [comment]
Hi @mablanco,
Thanks for trying Faraday. We are going to add your request for the interactions list to work on. 
Could you send us an XML example? thanks
Best

**Comment by mablanco** [comment]
Yes, of course. I can generate a XML report in a test machine. How would you like me to send the file?

**Comment by f-amato** [comment]
Could you please send us to 
<img width="154" alt="screen shot 2015-11-05 at 2 33 28 pm" src="https://cloud.githubusercontent.com/assets/4266445/11339104/9c6e83b8-91d6-11e5-9ff8-2c9399cc60b7.png">

Best
