### ISSUE TITLE
wpscan plugin

### ISSUE THREAD

**Issue by re8el** [infobyte/faraday#56]
Hi i would like to suggest a plugin for WPSCAN

**Comment by f-amato** [comment]
Hi @re8el ,
Thanks for trying Faraday. We are going to add your request for the interactions list to work on. 
Best

**Comment by Ezequieltbh** [comment]
Hi re8el!
In this new version of Faraday 2.1, we added a Wpscan plugin!
Maybe you can try this, and give us something of feedback?
Cheers!
