### ISSUE TITLE
Issues running propecia in Faraday 

### ISSUE THREAD

**Issue by the-nepo** [infobyte/faraday#68]
Just downloaded and run the latest Kali VM image, 
In Faraday i configured Couch DB and created a workspace, the workspace is selected and trying to run propecia as follows **[root@kali:/usr/share/python-faraday]>$ propecia 192.168.0 22** .
This fails with:
 - the following message *bash: propecia: command not found* -  in the interface shell
 - the terminal window shows the following messages:
  -  *2016-02-15 04:42:41,947 - faraday - INFO - No hosts detected*
  -  *2016-02-15 04:42:41,949 - faraday - INFO - Plugin finished: propecia, (a4bfa9d05574262aebbd2566079b1478c798d82)*

as you can see I am logged in as root.

Thanks,
Nepo

**Comment by fedek** [comment]
Hi Nepo,

It seems you don't have propecia installed or is not in your PATH 

> bash: propecia: command not found

Cheers!
