### ISSUE TITLE
Issue importing report from NeXpose

### ISSUE THREAD

**Issue by Dargin** [infobyte/faraday#73]
Good afternoon,

I was looking at testing the view and data from importing a scan from NeXpose. However when i drop the file in the reports/workspace folder i get the below information:

2016-03-17 15:01:34,067 - faraday - INFO - Report file is /root/.faraday/report/test3/test2.xml
2016-03-17 15:01:34,080 - faraday - INFO - The file is /root/.faraday/report/test3/test2.xml, 
2016-03-17 15:01:34,092 - faraday - INFO - Executing ./ /root/.faraday/report/test3/test2.xml
2016-03-17 15:01:34,533 - tornado.access - WARNING - 400 POST /cmd/output (127.0.0.1) 169.09ms

Couchdb is up and running at 127.0.0.1, the webui is up and working, i'm running as root for this demo. I've tried xml 1 and 2. when i look at the folder the file has been moved to the process folder, but no data shows up in the Web or UI. I ran faraday with -d but it doesn't show me any more info, nor can i seem to locate a log for tornado. 

thanks.

**Comment by rgerman** [comment]
Hi Dargin!

Thanks for reporting this. What version of NeXpose are you using? Would it be possible for you to send us the report to <img width="154" alt="devel email" src="https://cloud.githubusercontent.com/assets/4266445/10976376/3adaa47a-83ca-11e5-8b62-e9d6ce41f425.png">? If not, please open the file with a text editor and send us the first few lines (we're looking for the NeXpose tag).

Cheers!

**Comment by Dargin** [comment]
We're on NeXpose 6.1.14 - here are the first few lines. thanks for the quick response.

<?xml version="1.0"?>

-<NexposeReport version="2.0">

**Comment by Dargin** [comment]
Sorry, it cut the next line:

NexposeReport version="2.0"

**Comment by rgerman** [comment]
Would you attach the first few lines as file here (not sure if Github removes some characters and/or symbols)? That way we can test if Faraday recognize the report. From the output above it looks like Faraday didn't understand the initial tag.

Thanks!

**Comment by Dargin** [comment]
Attached here, i'm working on getting a report out of my personal lab aswell so you can have the full report. The only difference between the two reports is one is version 1.0 and one is 2.0 for the NexposeReport version line. Thanks again.
[first_line.zip](https://github.com/infobyte/faraday/files/179574/first_line.zip)

**Comment by rgerman** [comment]
Hi Dargin, you can apply this patch for now. We'll be adding this to the next release.

Move to the faraday root, save the diff in a file like "nexpose.patch" and then run: `patch -p1 < nexpose.patch`)

```patch
diff --git a/managers/reports_managers.py b/managers/reports_managers.py
index 6b460ae..1ebb916 100755
--- a/managers/reports_managers.py
+++ b/managers/reports_managers.py
@@ -194,7 +194,7 @@ class ReportParser(object):
         if report_type == "zip":
             result = "maltego"
 
-        elif report_type == "xml":
+        else:
 
             try:
                 for event, elem in ET.iterparse(f, ('start', )):
```

Thank's for reporting this!

**Comment by Dargin** [comment]
Thanks again for such quick response and work! That patch worked like a charm so getting ready to demo it to the higher ups!
