### ISSUE TITLE
Upgrade free version to commercial version

### ISSUE THREAD

**Issue by bmurphy5th** [infobyte/faraday#74]
I have the free version of Faraday installed on an Ubuntu server and recently purchased the commercial version.  Is it possible to use the files from the Kali ISO  we received when we purchased a license to upgrade our Ubuntu server installation, or are we required to used the included ISO?

**Comment by fedek** [comment]
@bmurphy5th ,
Yes it's possible to upgrade or install on a fresh install. From our costumer portal you can download the tarball and install it using the following instructions: https://github.com/infobyte/faraday/wiki/Faraday-Server

Tell me if this works for you,

Cheers
