### ISSUE TITLE
I Cannot Install in Darwin

### ISSUE THREAD

**Issue by danieljoppi** [infobyte/faraday#76]
```bash
sudo ./install.sh 
[+] Install Darwin 15.3.0 x86_64
[-] Could not find a install for Darwin 15.3.0 (x86_64 15.3.0)
```

**Comment by fedek** [comment]
Hi @danieljoppi,

Could you try the instructions from our wiki? https://github.com/infobyte/faraday/wiki/Installation#faraday

Basically try running faraday directly: _./faraday.py_

let us know how it goes,

cheers

**Comment by fedek** [comment]
Any feedback regarding this issue?

Thanks
