### ISSUE TITLE
still on python 2.7?

### ISSUE THREAD

**Issue by ChrisFernandez** [infobyte/faraday#95]
this is why I rather use ruby tools, everytime I try to run some python tool some are for 3 other for 2.x even tho is been YEARS since the update to 3.x ... I like to use 2016 software on my arch GNU/Linux there is no way i'm downgrading to OLD python... so after my rant(sorry is been as of now many frustrations with this issue in python....) when is this going to be able to run on now new(now old) python... in the meantime back to VIM for notes.

**Comment by Someguy123** [comment]
@ChrisFernandez You don't need to "downgrade". Python2 and 3 can be run side-by-side.

Although I agree faraday should be upgraded to work with Python3.
