### ISSUE TITLE
You are missing Gobject Instrospection. Please install version 3.14 or above

### ISSUE THREAD

**Issue by Someguy123** [infobyte/faraday#98]
I've tried to install gobject-introspection several times, but Faraday refuses to see it. I also noticed there's no such thing as gobject-introspection 3.14, since the current bleeding edge version is 1.48...

`You are missing Gobject Instrospection. Please install version 3.14 or above`

Using Arch Linux, with Faraday installed directly from pacman (BlackArch).

I've also tested with it directly from GitHub, with the same error.

**Comment by Someguy123** [comment]
Figured it out. Needed `python2-gobject` from pacman. 

Hopefully this helps some other people who are frustrated by this.

**Comment by aisbaa** [comment]
Have the same issue on ubuntu 14.04.

**Comment by joaquinlpereyra** [comment]
Hey @aisbaa! Have you tried installing the package `gobject-introspection`.  It is supposedly [available in the Ubuntu 14.04 repositories.

**Comment by jamesjara** [comment]
gobject-introspection is not enough we need py gobject apt-get  install python-gobject

**Comment by aisbaa** [comment]
Cool thank you guys, I manged solve those issues. Hope to put everything into Dockerfile, might make faraday even more accessible.

**Comment by joaquinlpereyra** [comment]
@jamesjara thanks for the help and we're glad you managed to solve your problem @aisbaa !

**Comment by julysallari** [comment]
I have the same issue on max os Captain:
You are missing Gobject Instrospection. Please install version 3.14 or above (recommended) or 3.12
and then:
gobject-introspection-1.48.0 already installed
I could really use the help, thx!

**Comment by joaquinlpereyra** [comment]
Hi @julysallari! Have you installed all other (requirements)[https://github.com/infobyte/faraday/wiki/installation-client]?

**Comment by joaquinlpereyra** [comment]
@julysallari Hi! Are you using the last version? 'Current workspace: untitled' was deprecated a while ago. And you should be just running:

`./faraday.py' to access the gtk interface :)

**Comment by julysallari** [comment]
@joaquinlpereyra yes, just cloned it again and run ./faraday.py (AND in dev mode) but still the same issue...
=(

**Comment by christinacelee** [comment]
@julysallari I am also using Mac OS El Capitain and am running into the exact same problem :( have you figured out how to fix this?

**Comment by vwhissell** [comment]
Fresh new ubuntu server:

`You are missing Gobject Instrospection. Please install version 3.14 or above (recommended) or 3.12`

That issue should not be closed.

**Comment by omaidf** [comment]
I have this issue as well
